Repository AliMD/alwatr, pull requests merged in 2022-03, with the labels that each got.

#34 chore(github): add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#38 Signal documents and examples.
  package/signal/README.md
Labels: documentation

#43 Improve signal
  package/signal/src/signal.ts
  package/signal/src/type.ts
Labels: enhancement

#27 New package: router, elegant powerful routing based on the simplicity of signals
  .eslintrc.yaml
  .vscode/settings.json
  package/router/README.md
  package/router/package.json
  package/router/src/core.ts
  package/router/src/router.ts
  package/router/src/trigger-click.ts
  package/router/src/trigger-popstate.ts
  package/router/src/type.ts
  package/router/tsconfig.json
  tsconfig.json
Labels: enhancement

#45 chore(CONTRIBUTING): code of conduct link
  CONTRIBUTING.md
Labels: bug

#46 Github issue and pull request template
  .github/ISSUE_TEMPLATE/1-bug-report.yaml
  .github/ISSUE_TEMPLATE/2-feature-request.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation

#47 Fix/debug
  package/logger/src/logger.ts
  package/logger/src/meta.ts
  package/router/package.json
  package/router/src/core.ts
  package/router/src/router.ts
  package/signal/src/core.ts
  package/signal/src/signal.ts
  package/signal/src/type.ts
Labels: bug, enhancement

#51 New package for i18n/l10n
  .gitignore
  package/i18n/README.md
  package/i18n/package.json
  package/i18n/src/core.ts
  package/i18n/src/i18n.ts
  package/i18n/src/type.ts
  package/i18n/tsconfig.json
  package/signal/src/signal.ts
  package/signal/src/type.ts
  tsconfig.json
Labels: enhancement

#53 Improve fetch document
  .gitconfig
  package/fetch/README.md
Labels: documentation

#61 Review and update all scripts
  .editorconfig
  .github/ISSUE_TEMPLATE/1-bug-report.yaml
  .github/pull_request_template.md
  package.json
  tsconfig.json
Labels: enhancement

#77 Complete refactor logger and fix all packages type issues
  demo/logger/index.ts
  package.json
  package/fetch/src/fetch.ts
  package/i18n/src/core.ts
  package/i18n/src/i18n.ts
  package/logger/README.md
  package/logger/src/logger.ts
  package/logger/src/meta.ts
  package/logger/src/type.ts
  package/router/src/core.ts
  package/router/src/router.ts
  package/router/src/trigger-click.ts
  package/router/src/trigger-popstate.ts
  package/router/src/type.ts
  package/signal/src/core.ts
  package/signal/src/signal.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#78 Release: v0.4.0
  .editorconfig
  .gitconfig
  .github/ISSUE_TEMPLATE/1-bug-report.yaml
  .github/pull_request_template.md
  CHANGELOG.md
  demo/CHANGELOG.md
  demo/logger/index.ts
  demo/package.json
  lerna.json
  package.json
  package/fetch/CHANGELOG.md
  package/fetch/README.md
  package/fetch/package.json
  package/fetch/src/fetch.ts
  package/i18n/CHANGELOG.md
  package/i18n/package.json
  package/i18n/src/core.ts
  package/i18n/src/i18n.ts
  package/logger/CHANGELOG.md
  package/logger/README.md
  package/logger/package.json
  package/logger/src/logger.ts
  package/logger/src/meta.ts
  package/logger/src/type.ts
  package/router/CHANGELOG.md
  package/router/package.json
  package/router/src/core.ts
  package/router/src/router.ts
  package/router/src/trigger-click.ts
  package/router/src/trigger-popstate.ts
  package/router/src/type.ts
  package/signal/CHANGELOG.md
  package/signal/package.json
  package/signal/src/core.ts
  package/signal/src/signal.ts
  tsconfig.json
  yarn.lock
Labels: release

#85 feat(workflow): add verify workflow
  .github/workflows/tests.yml
Labels: enhancement

#92 Release: v0.5.0
  .github/workflows/tests.yml
  CHANGELOG.md
  demo/CHANGELOG.md
  demo/package.json
  lerna.json
  package/fetch/CHANGELOG.md
  package/fetch/package.json
  package/i18n/CHANGELOG.md
  package/i18n/package.json
  package/i18n/src/core.ts
  package/i18n/src/i18n.ts
  package/logger/CHANGELOG.md
  package/logger/README.md
  package/logger/package.json
  package/logger/src/logger.ts
  package/router/CHANGELOG.md
  package/router/package.json
  package/router/src/core.ts
  package/router/src/router.ts
  package/router/src/trigger-click.ts
  package/router/src/trigger-popstate.ts
  package/signal/CHANGELOG.md
  package/signal/README.md
  package/signal/package.json
  package/signal/src/core.ts
  package/signal/src/signal.ts
Labels: release

#94 [BREAKING CHANGES] Rename `vatr` to `alwatr`
  .github/ISSUE_TEMPLATE/1-bug-report.yaml
  .github/ISSUE_TEMPLATE/2-feature-request.yaml
  .github/pull_request_template.md
  .vscode/settings.json
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  demo/CHANGELOG.md
  demo/logger/index.ts
  demo/package.json
  package.json
  package/fetch/CHANGELOG.md
  package/fetch/README.md
  package/fetch/package.json
  package/fetch/src/fetch.ts
  package/i18n/CHANGELOG.md
  package/i18n/README.md
  package/i18n/package.json
  package/i18n/src/core.ts
  package/i18n/src/type.ts
  package/logger/CHANGELOG.md
  package/logger/README.md
  package/logger/package.json
  package/logger/src/logger.ts
  package/logger/src/type.ts
  package/router/CHANGELOG.md
  package/router/README.md
  package/router/package.json
  package/router/src/core.ts
  package/router/src/trigger-click.ts
  package/router/src/trigger-popstate.ts
  package/router/src/type.ts
  package/signal/CHANGELOG.md
  package/signal/README.md
  package/signal/package.json
  package/signal/src/core.ts
  package/signal/src/signal.ts
  package/signal/src/type.ts
Labels: enhancement

#96 New package: @alwatr/math
  .github/workflows/tests.yml
  package/math/README.md
  package/math/package.json
  package/math/src/math.ts
  package/math/src/type.ts
  package/math/tsconfig.json
Labels: enhancement

#101 [Logger] Add debug property and improve documents
  package/logger/README.md
  package/logger/src/logger.ts
  package/logger/src/type.ts
Labels: enhancement

#99 Fix router tigger-click bug
  package/router/src/trigger-click.ts
Labels: bug

#103 Fix signal update state issue
  demo/index.html
  demo/logger/index.html
  demo/router/index.html
  demo/router/index.ts
  demo/signal/index.html
  package/router/src/core.ts
Labels: bug

#104 Fix signal _dispatchSignal/__callListeners issue
  demo/router/index.html
  demo/router/index.ts
  package/signal/src/core.ts
Labels: bug

#105 Refactor(i18n): make seperate file for signals
  package/i18n/src/core.ts
  package/i18n/src/i18n.ts
  package/i18n/src/signal.ts
  package/i18n/src/type.ts
Labels: bug

#106 refactor(router): use seperate signal file
  package/router/src/core.ts
  package/router/src/router.ts
  package/router/src/signal.ts
  package/router/src/trigger-click.ts
  package/router/src/trigger-popstate.ts
  package/router/src/type.ts
Labels: enhancement

#111 Router outlet and new API
  demo/router/index.html
  demo/router/index.ts
  package/router/README.md
  package/router/src/router.ts
  package/router/src/type.ts
Labels: enhancement

#120 Enhance signal: add seperate api interface for listeners (ListenerInterface)
  package/signal/README.md
  package/signal/src/core.ts
  package/signal/src/signal.ts
Labels: documentation, enhancement

#121 fix(i18n): access signal issue
  package/i18n/src/i18n.ts
  package/i18n/src/signal.ts
Labels: enhancement

#122 docs(router): full example with lit
  package/router/README.md
Labels: documentation

#124 Feat/lint
  .eslintrc.yaml
  demo/package.json
  demo/router/index.ts
  package.json
  package/i18n/src/core.ts
  package/i18n/src/i18n.ts
  package/i18n/src/signal.ts
  package/router/src/core.ts
  package/router/src/router.ts
  package/router/src/signal.ts
  package/signal/src/core.ts
  package/signal/src/signal.ts
  yarn.lock
Labels: enhancement

#125 feat(font): init
  package/font/CHANGELOG.md
  package/font/README.md
  package/font/font.css
  package/font/package.json
  package/font/src/font.ts
  package/font/tsconfig.json
Labels: enhancement
