Repository AliMD/alwatr, pull requests merged in 2022-08, with the labels that each got.

#176 Fix nano server/service requetBody and lint issue
  packages/core/nano-server/src/nano-server.ts
  packages/starter/nanoservice/.eslintrc.json
Labels: bug, enhancement

#180 Storage Nanoservice API
  demo/storage/big-data-test.ts
  demo/storage/index.ts
  packages/core/nano-server/src/nano-server.ts
  packages/core/storage/src/provider.ts
  packages/core/storage/src/storage.ts
  packages/core/storage/src/type.ts
  packages/core/storage/src/util.ts
  packages/service/storage/Dockerfile
  packages/service/storage/demo.http
  packages/service/storage/package.json
  packages/service/storage/src/index.ts
  packages/service/storage/src/lib/config.ts
  packages/service/storage/src/lib/storage-provider.ts
  packages/service/storage/src/lib/token.ts
  packages/service/storage/src/lib/type.ts
  packages/service/storage/src/route/echo.ts
  packages/service/storage/src/route/get.ts
  packages/service/storage/src/route/update.ts
  packages/starter/nanoservice/src/index.ts
  packages/starter/nanoservice/src/route/echo.ts
Labels: enhancement

#181 New package: @alwatr/token
  demo/token/benchmark.ts
  demo/token/index.ts
  demo/tsconfig.json
  packages/core/math/src/math.ts
  packages/core/token/README.md
  packages/core/token/package.json
  packages/core/token/src/token.ts
  packages/core/token/src/type.ts
  packages/core/token/tsconfig.json
  tsconfig.json
Labels: enhancement

#185 Add readme for packages category
  packages/core/README.md
  packages/kubernetes/README.md
  packages/lab/README.md
  packages/service/README.md
  packages/starter/README.md
  packages/ui/README.md
Labels: documentation

#186 chore: add logo
  README.md
  logo.svg
Labels: enhancement

#187 feat(traefik): add service proxy
  packages/container/README.md
  packages/kubernetes/README.md
  packages/service/.gitignore
  packages/service/traefik-proxy/docker-compose.yml
  packages/service/traefik-proxy/traefik.toml
  packages/service/traefik-proxy/up.sh
Labels: enhancement

#188 feat(xz-example): such a wow!
  packages/lab/zx-example/README.md
  packages/lab/zx-example/package.json
  packages/lab/zx-example/src/zx-example.ts
  packages/lab/zx-example/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#184 Add nano-server jsdoc
  .vscode/settings.json
  packages/core/logger/README.md
  packages/core/nano-server/README.md
  packages/core/nano-server/src/nano-server.ts
Labels: documentation

#190 traefik deploy script
  packages/service/traefik-proxy/.env.example
  packages/service/traefik-proxy/README.md
  packages/service/traefik-proxy/_up.sh
  packages/service/traefik-proxy/deploy.sh
  packages/service/traefik-proxy/docker-compose.yml
Labels: enhancement

#191 New service: mariadb
  packages/service/mariadb/.env.example
  packages/service/mariadb/_up.sh
  packages/service/mariadb/deploy.sh
  packages/service/mariadb/docker-compose.yml
Labels: enhancement

#192 New service: adminer
  packages/service/adminer/.env.example
  packages/service/adminer/_up.sh
  packages/service/adminer/deploy.sh
  packages/service/adminer/docker-compose.yml
Labels: enhancement

#194 feat(services): improve all docker deployment
  .vscode/settings.json
  packages/service/adminer/.env.example
  packages/service/adminer/deploy.sh
  packages/service/adminer/docker-compose.yml
  packages/service/mariadb/.env.example
  packages/service/mariadb/deploy.sh
  packages/service/mariadb/docker-compose.yml
  packages/service/traefik-proxy/.env.example
  packages/service/traefik-proxy/deploy.sh
  packages/service/traefik-proxy/docker-compose.yml
Labels: enhancement

#196 Add multi .env file support to deploy script
  packages/lab/wordpress/deploy.sh
  packages/service/adminer/deploy.sh
  packages/service/mariadb/deploy.sh
  packages/service/traefik-proxy/deploy.sh
Labels: dependencies

#197 Refactor services
  .gitignore
  packages/classic-cloud/README.md
  packages/classic-cloud/adminer/.env.example
  packages/classic-cloud/adminer/_up.sh
  packages/classic-cloud/adminer/deploy.sh
  packages/classic-cloud/adminer/docker-compose.yml
  packages/classic-cloud/mariadb/.env.example
  packages/classic-cloud/mariadb/_up.sh
  packages/classic-cloud/mariadb/deploy.sh
  packages/classic-cloud/mariadb/docker-compose.yml
  packages/classic-cloud/traefik-proxy/.env.example
  packages/classic-cloud/traefik-proxy/README.md
  packages/classic-cloud/traefik-proxy/_up.sh
  packages/classic-cloud/traefik-proxy/deploy.sh
  packages/classic-cloud/traefik-proxy/docker-compose.yml
  packages/classic-cloud/traefik-proxy/traefik.toml
  packages/classic-cloud/wordpress/.env.example
  packages/classic-cloud/wordpress/README.md
  packages/classic-cloud/wordpress/_up.sh
  packages/classic-cloud/wordpress/deploy.sh
  packages/classic-cloud/wordpress/docker-compose.yml
  packages/classic-cloud/wordpress/nginx/.dockerignore
  packages/classic-cloud/wordpress/nginx/Dockerfile
  packages/classic-cloud/wordpress/nginx/conf.d/fastcgi.conf
  packages/classic-cloud/wordpress/nginx/conf.d/mime-expire.conf
  packages/classic-cloud/wordpress/nginx/conf.d/mime.conf
  packages/classic-cloud/wordpress/nginx/conf.d/nocache.conf
  packages/classic-cloud/wordpress/nginx/conf.d/secure.conf
  packages/classic-cloud/wordpress/nginx/nginx.conf
  packages/classic-cloud/wordpress/nginx/toggle-cache.html
  packages/classic-cloud/wordpress/php/.dockerignore
  packages/classic-cloud/wordpress/php/Dockerfile
  packages/classic-cloud/wordpress/php/fix-permition.sh
  packages/classic-cloud/wordpress/php/php.conf.ini
  packages/nanoservice/README.md
  packages/nanoservice/storage/CHANGELOG.md
  packages/nanoservice/storage/Dockerfile
  packages/nanoservice/storage/README.md
  packages/nanoservice/storage/demo.http
  packages/nanoservice/storage/package.json
  packages/nanoservice/storage/src/index.ts
  packages/nanoservice/storage/src/lib/config.ts
  packages/nanoservice/storage/src/lib/nano-server.ts
  packages/nanoservice/storage/src/lib/storage-provider.ts
  packages/nanoservice/storage/src/lib/token.ts
  packages/nanoservice/storage/src/lib/type.ts
  packages/nanoservice/storage/src/route/get.ts
  packages/nanoservice/storage/src/route/home.ts
  packages/nanoservice/storage/src/route/update.ts
  packages/nanoservice/storage/tsconfig.json
  packages/service/README.md
Labels: enhancement

#204 fix(classic-cloud): docker-compose external syntax
  packages/classic-cloud/adminer/docker-compose.yml
  packages/classic-cloud/mariadb/docker-compose.yml
  packages/classic-cloud/traefik-proxy/docker-compose.yml
  packages/classic-cloud/wordpress/docker-compose.yml
Labels: enhancement

#208 Refactor cloud scripts
  packages/classic-cloud/adminer/_up.sh
  packages/classic-cloud/adminer/compose.yml
  packages/classic-cloud/adminer/deploy.sh
  packages/classic-cloud/mariadb/.env.example
  packages/classic-cloud/mariadb/_up.sh
  packages/classic-cloud/mariadb/compose.yml
  packages/classic-cloud/mariadb/deploy.sh
  packages/classic-cloud/php-apache/.env.example
  packages/classic-cloud/php-apache/compose.yml
  packages/classic-cloud/php-apache/deploy.sh
  packages/classic-cloud/traefik-proxy/_up.sh
  packages/classic-cloud/traefik-proxy/compose.yml
  packages/classic-cloud/traefik-proxy/deploy.sh
  packages/classic-cloud/wordpress/.env.example
  packages/classic-cloud/wordpress/_up.sh
  packages/classic-cloud/wordpress/compose.yml
  packages/classic-cloud/wordpress/deploy.sh
  packages/classic-cloud/wordpress/nginx/Dockerfile
  packages/classic-cloud/wordpress/nginx/nginx.conf
Labels: enhancement

#217 refactor(signal): add a global `signalCounter` instead of `Symbol` & …
  packages/core/signal/src/core.ts
  packages/core/signal/src/signal.ts
  packages/core/signal/src/type.ts
Labels: enhancement, feature request

#219 refactor: php docker files
  packages/classic-cloud/php-apache/php/Dockerfile
  packages/classic-cloud/wordpress/.env.example
  packages/classic-cloud/wordpress/compose.yml
  packages/classic-cloud/wordpress/php/Dockerfile
Labels: enhancement

#220 Improve classic deploy script
  packages/classic-cloud/adminer/deploy.sh
  packages/classic-cloud/lib/deploy.sh
  packages/classic-cloud/mariadb/deploy.sh
  packages/classic-cloud/php-apache/deploy.sh
  packages/classic-cloud/traefik-proxy/deploy.sh
  packages/classic-cloud/wordpress/deploy.sh
Labels: enhancement

#225 Update workflow
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
Labels: enhancement

#222 Fix signal set porvider issue
  demo/signal/index.ts
  package.json
  packages/classic-cloud/static-file/.env.example
  packages/classic-cloud/static-file/README.md
  packages/classic-cloud/static-file/_up.sh
  packages/classic-cloud/static-file/compose.yml
  packages/classic-cloud/static-file/deploy.sh
  packages/core/signal/README.md
  packages/core/signal/src/core.ts
  packages/core/signal/src/signal.ts
  packages/core/signal/src/type.ts
Labels: bug

#229 fix(workflow): run issue
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/lint.yaml
Labels: enhancement

#232 feat(container): alpine with CI deploy and improve workflows
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
  .github/workflows/publish-container.yml
  .github/workflows/publish-npm.yml
  packages/container/alpine/Dockerfile
Labels: enhancement

#238 New container: TDLib!
  .github/workflows/publish-container.yml
  packages/container/tdlib/Dockerfile
Labels: enhancement

#240 Fix tdlib auto build and deploy
  packages/container/tdlib/Dockerfile
Labels: bug

#242 fix: remove npm token from install dependencies
  .github/workflows/publish-npm.yml
Labels: bug
