Repository AliMD/alwatr, pull requests merged in 2022-12, with the labels that each got.

#450 fix(logger): optimize for browserify builds
  packages/core/logger/src/logger.ts
Labels: bugfix

#451 fix: set correct dependencies and refrences
  packages/core/math/tsconfig.json
  packages/ui/icon/package.json
  packages/ui/icon/tsconfig.json
Labels: minor, bugfix

#452 feat(i18n): improve i18n and fix bugs
  packages/core/i18n/src/i18n.ts
  packages/core/i18n/src/type.ts
Labels: bugfix

#457 feat: improve build and serve
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  package.json
  packages/core/math/src/unicode-digits.ts
  tsconfig.json
  web-dev-server.config.js
  yarn.lock
Labels: enhancement, ci

#458 feat(logger): log incident in production mode
  packages/core/logger/src/logger.ts
Labels: enhancement, minor

#466 feat(storage-client): dynamic storage name
  packages/core/storage-client/src/storage-client.ts
  packages/core/storage-client/src/type.ts
Labels: new-feature

#437 chore(.vscode): update extension recommendation
  .vscode/extensions.json
Labels: documentation, minor

#486 fix(workflows/build): build all child packages
  .github/workflows/build.yaml
Labels: ci

#481 Signal Lit Element mixin for remove listeners
  .DS_Store
  ui-kit/element/package.json
  ui-kit/element/src/element.ts
  ui-kit/element/tsconfig.json
Labels: enhancement

#489 feat(services/telegram-notifier): dynamic storage path
  services/telegram-notifier/src/lib/config.ts
  services/telegram-notifier/src/lib/storage.ts
Labels: enhancement

#491 feat: esbuild (:
  services/comment/package.json
  services/comment/tsconfig.json
  services/flight-crawler/package.json
  services/flight-crawler/tsconfig.json
  services/starter/package.json
  services/starter/tsconfig.json
  services/storage-server/package.json
  services/storage-server/tsconfig.json
  services/telegram-notifier/package.json
  services/telegram-notifier/tsconfig.json
  uniquely/flight-finder-api/package.json
  uniquely/flight-finder-api/tsconfig.json
Labels: new-feature

#488 feat: deployment flight finder
  .gitignore
  cloud/classic/flight-finder/compose.yml
  cloud/classic/flight-finder/deploy.sh
  cloud/classic/flight-finder/env/example.env
  services/telegram-notifier/esbuild.config.js
  services/telegram-notifier/package.json
  services/telegram-notifier/src/lib/bot.ts
  yarn.lock
Labels: new-feature

#490 refactor: access token env
  cloud/lab/wireguard/env/example.env
  services/comment/src/lib/config.ts
  services/comment/src/route/all.ts
  services/comment/src/route/patch.ts
  services/storage-server/src/lib/config.ts
  services/storage-server/src/route/all.ts
  services/storage-server/src/route/delete.ts
  services/storage-server/src/route/get.ts
  services/storage-server/src/route/has.ts
  services/storage-server/src/route/keys.ts
  services/storage-server/src/route/patch.ts
  services/telegram-notifier/src/lib/config.ts
  services/telegram-notifier/src/route/notify.ts
  uniquely/flight-finder-api/src/lib/config.ts
  uniquely/flight-finder-api/src/route/job/delete.ts
  uniquely/flight-finder-api/src/route/job/get.ts
  uniquely/flight-finder-api/src/route/job/put.ts
Labels: enhancement

#493 feat(storage-server): SAVE_DEBOUNCE config
  services/storage-server/src/config.ts
  services/storage-server/src/lib/nano-server.ts
  services/storage-server/src/lib/storage-provider.ts
  services/storage-server/src/route/all.ts
  services/storage-server/src/route/delete.ts
  services/storage-server/src/route/get.ts
  services/storage-server/src/route/has.ts
  services/storage-server/src/route/keys.ts
  services/storage-server/src/route/patch.ts
  uniquely/flight-finder-api/src/config.ts
  uniquely/flight-finder-api/src/lib/nano-server.ts
Labels: new-feature

#497 feat: city list
  services/flight-crawler/package.json
  services/flight-crawler/src/crawl.ts
  services/flight-crawler/src/lib/city-list.ts
  uniquely/flight-finder-pwa/src/component/job-item.ts
Labels: enhancement

#494 fix(ff-*): launch issues
  .github/workflows/publish-alwatr-container.yml
  cloud/classic/flight-finder/compose.yml
  cloud/classic/flight-finder/env/example.env
  cloud/classic/lib/deploy.sh
  cloud/container/alwatr-services.dockerfile
  cloud/lab/v2fly/deploy.sh
  core/fetch/src/fetch.ts
  core/fetch/src/type.ts
  core/logger/src/logger.ts
  core/logger/src/type.ts
  core/nano-server/src/nano-server.ts
  services/comment/package.json
  services/flight-crawler/package.json
  services/flight-crawler/src/crawl.ts
  services/flight-crawler/src/lib/city-list.ts
  services/flight-crawler/src/lib/type.ts
  services/starter/package.json
  services/storage-server/package.json
  services/telegram-notifier/package.json
  services/telegram-notifier/src/bot/bot.ts
  services/telegram-notifier/src/bot/command/start.ts
  services/telegram-notifier/src/bot/launch.ts
  services/telegram-notifier/src/bot/send-message.ts
  services/telegram-notifier/src/config.ts
  services/telegram-notifier/src/index.ts
  services/telegram-notifier/src/lib/bot.ts
  uniquely/flight-finder-api/package.json
  uniquely/flight-finder-pwa/config.js
  uniquely/flight-finder-pwa/index.html
  uniquely/flight-finder-pwa/manifest.json
  uniquely/flight-finder-pwa/package.json
  uniquely/flight-finder-pwa/rollup.config.js
  uniquely/flight-finder-pwa/src/component/job-item.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
  uniquely/flight-finder-pwa/src/director/job-add.ts
  uniquely/flight-finder-pwa/src/director/job-delete.ts
  uniquely/flight-finder-pwa/src/director/job-list.ts
  uniquely/flight-finder-pwa/src/type.ts
Labels: ci, bugfix

#504 fix(ff-*): reported issues
  services/flight-crawler/src/crawl.ts
  services/flight-crawler/src/lib/type.ts
  services/telegram-notifier/src/bot/command/start.ts
  uniquely/flight-finder-pwa/src/component/job-item.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
  uniquely/flight-finder-pwa/src/type.ts
Labels: new-feature, bugfix

#513 feat(fetch): serviceRequest
  core/fetch/src/fetch.ts
  core/fetch/src/type.ts
Labels: new-feature

#512 refactor(storage-*)!: breaking changes
  core/fetch/src/fetch.ts
  core/fetch/src/type.ts
  core/storage-client/README.md
  core/storage-client/src/storage-client.ts
  core/storage-engine/src/storage-engine.ts
  core/storage-engine/src/type.ts
  demo/storage-client/benchmark.ts
  demo/storage-client/index.ts
  demo/storage-engine/benchmark.ts
  services/comment/demo.http
  services/comment/src/index.ts
  services/comment/src/route/storage.ts
  services/flight-crawler/src/crawl.ts
  services/flight-crawler/src/lib/storage.ts
  services/storage-server/demo.http
  services/storage-server/src/index.ts
  services/storage-server/src/route/all.ts
  services/storage-server/src/route/delete.ts
  services/storage-server/src/route/get.ts
  services/storage-server/src/route/has.ts
  services/storage-server/src/route/keys.ts
  services/storage-server/src/route/patch.ts
  services/storage-server/src/route/storage.ts
  tsconfig.base.json
  uniquely/flight-finder-api/src/lib/storage.ts
  uniquely/flight-finder-api/src/route/job/delete.ts
  uniquely/flight-finder-api/src/route/job/get.ts
  uniquely/flight-finder-api/src/route/job/put.ts
  uniquely/flight-finder-pwa/workbox-config.js
Labels: major, new-feature, breaking-change, bugfix

#514 fix(nano-server): handle utf8 reply issue
  core/nano-server/src/nano-server.ts
Labels: bugfix

#515 feat: improve error debugging
  core/fetch/src/fetch.ts
  core/i18n/src/i18n.ts
  core/logger/README.md
  core/logger/src/type.ts
  core/nano-server/src/nano-server.ts
  core/signal/src/core.ts
  core/storage-client/README.md
  core/storage-client/src/storage-client.ts
  demo/logger/index.ts
  demo/storage-client/benchmark.ts
  services/comment/src/lib/storage.ts
  services/comment/src/route/patch.ts
  services/comment/src/route/storage.ts
  services/flight-crawler/src/crawl.ts
  services/storage-server/demo.http
  services/telegram-notifier/src/bot/launch.ts
  services/telegram-notifier/src/bot/send-message.ts
  ui-kit/icon/src/icon.ts
  uniquely/flight-finder-api/src/route/job/delete.ts
  uniquely/flight-finder-api/src/route/job/get.ts
  uniquely/flight-finder-api/src/route/job/put.ts
Labels: enhancement, new-feature

#511 feat(ff): deploy and test new version
  .github/workflows/publish-alwatr-container.yml
  cloud/classic/flight-finder/compose.yml
  cloud/classic/flight-finder/env/example.env
  services/flight-crawler/package.json
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
Labels: ci, bugfix

#516 fix(storage-server): prevent to modify storage by reply
  services/storage-server/src/route/storage.ts
Labels: bugfix

#517 feat(flight-crawler): format prices
  services/flight-crawler/src/crawl.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
Labels: new-feature

#518 fix(ff-pwa): render issues
  uniquely/flight-finder-pwa/robots.txt
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
Labels: bugfix

#526 fix(logger, nano-server): review latest PRs
  core/logger/src/logger.ts
  core/logger/src/type.ts
  core/nano-server/src/nano-server.ts
  core/storage-client/src/storage-client.ts
Labels: minor, bugfix

#529 fix(fetch): revalidateCallback issue
  core/fetch/src/fetch.ts
Labels: bugfix

#530 fix(container): build nodes in production env
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/alwatr-services.dockerfile
Labels: ci, performance, bugfix

#531 fix(alwatr-pwa.dockerfile): syntax issue
  cloud/container/alwatr-pwa.dockerfile
Labels: bugfix

#533 feat(flight-crawler): update message
  core/fetch/src/fetch.ts
  core/signal/src/signal.ts
  services/flight-crawler/src/crawl.ts
Labels: enhancement

#524 fix(ff-pwa): ui issue
  uniquely/flight-finder-pwa/l10n/fa-IR.json
  uniquely/flight-finder-pwa/src/component/job-add-form.ts
  uniquely/flight-finder-pwa/src/component/job-item.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
  uniquely/flight-finder-pwa/src/director/index.ts
  uniquely/flight-finder-pwa/src/director/job-add.ts
  uniquely/flight-finder-pwa/src/director/job-delete.ts
  uniquely/flight-finder-pwa/src/director/job-document-storage.ts
  uniquely/flight-finder-pwa/src/director/job-list.ts
  uniquely/flight-finder-pwa/src/type.ts
Labels: enhancement, bugfix

#532 breaking-changes: nano-server reply
  core/nano-server/src/nano-server.ts
  core/nano-server/src/type.ts
  services/comment/src/route/home.ts
  services/comment/src/route/patch.ts
  services/comment/src/route/storage.ts
  services/starter/src/route/echo.ts
  services/starter/src/route/home.ts
  services/storage-server/src/route/delete.ts
  services/storage-server/src/route/get.ts
  services/storage-server/src/route/has.ts
  services/storage-server/src/route/keys.ts
  services/storage-server/src/route/patch.ts
  services/storage-server/src/route/storage.ts
  services/telegram-notifier/src/route/home.ts
  services/telegram-notifier/src/route/notify.ts
  uniquely/flight-finder-api/src/route/home.ts
  uniquely/flight-finder-api/src/route/job/delete.ts
  uniquely/flight-finder-api/src/route/job/get.ts
  uniquely/flight-finder-api/src/route/job/put.ts
Labels: major, breaking-change

#536 fix(uniquely/flight-crawler): prevent set storage repeated
  services/flight-crawler/src/crawl.ts
Labels: minor, bugfix

#538 feat(flight-crawler): time filter
  services/flight-crawler/src/crawl.ts
  services/flight-crawler/src/lib/type.ts
  uniquely/flight-finder-api/demo.http
  uniquely/flight-finder-api/src/lib/type.ts
  uniquely/flight-finder-pwa/l10n/fa-IR.json
  uniquely/flight-finder-pwa/src/component/job-add-form.ts
  uniquely/flight-finder-pwa/src/component/job-item.ts
  uniquely/flight-finder-pwa/src/type.ts
Labels: new-feature

#554 feat(ff-deploy): depend on
  cloud/classic/flight-finder/compose.yml
Labels: minor, bugfix

#546 feat: labs
  cloud/lab/zx-example/README.md
  cloud/labs/README.md
  cloud/labs/ipsec/compose.yml
  cloud/labs/ipsec/deploy.sh
  cloud/labs/ipsec/env/example.env
  cloud/labs/openvpn/compose.yml
  cloud/labs/openvpn/deploy.sh
  cloud/labs/openvpn/env/example.env
  cloud/labs/shadowsocks/compose.yml
  cloud/labs/shadowsocks/deploy.sh
  cloud/labs/shadowsocks/env/example.env
  cloud/labs/v2fly/compose.yml
  cloud/labs/v2fly/config/client-vmess-socks.json
  cloud/labs/v2fly/config/server-vmess-ws.json
  cloud/labs/v2fly/deploy.sh
  cloud/labs/v2fly/env/example.env
  cloud/labs/wireguard/compose.yml
  cloud/labs/wireguard/deploy.sh
  cloud/labs/wireguard/env/example.env
  labs/rnnoise-model/README.md
  labs/rnnoise-model/general-record.rnnn
  labs/rnnoise-model/general.rnnn
  labs/rnnoise-model/speech-record.rnnn
  labs/rnnoise-model/voice-record.rnnn
  labs/rnnoise-model/voice.rnnn
  labs/zx-example/CHANGELOG.md
  labs/zx-example/README.md
  labs/zx-example/package.json
  labs/zx-example/src/zx-example.ts
  labs/zx-example/tsconfig.json
  package.json
  tsconfig.json
  uniquely/starter-pwa/package.json
  yarn.lock
Labels: enhancement, minor

#555 fix(flight-crawler): min&max hour in make message
  services/flight-crawler/src/crawl.ts
Labels: minor, bugfix

#560 chore(deps): fix versions
  core/fetch/package.json
  core/i18n/package.json
  core/nano-server/package.json
  core/router/package.json
  core/signal/package.json
  core/storage-client/package.json
  core/storage-engine/package.json
  core/token/package.json
  demo/package.json
  package.json
  services/comment/package.json
  services/flight-crawler/package.json
  services/starter/package.json
  services/storage-server/package.json
  services/telegram-notifier/package.json
  ui/element/package.json
  ui/icon/package.json
  ui/ui-kit/package.json
  uniquely/flight-finder-api/package.json
  uniquely/flight-finder-pwa/package.json
  uniquely/starter-pwa/package.json
  yarn.lock
Labels: dependencies

#561 refactor(ui): rename demo-pwa
  tsconfig.json
  ui/demo-pwa/README.md
  ui/demo-pwa/image/favicon.ico
  ui/demo-pwa/image/icon-180.png
  ui/demo-pwa/image/icon-192-maskable.png
  ui/demo-pwa/image/icon-192.png
  ui/demo-pwa/image/icon-512-maskable.png
  ui/demo-pwa/image/icon-512.png
  ui/demo-pwa/index.html
  ui/demo-pwa/l10n/en-US.json
  ui/demo-pwa/manifest.json
  ui/demo-pwa/package.json
  ui/demo-pwa/robots.txt
  ui/demo-pwa/rollup.config.js
  ui/demo-pwa/src/alwatr-page-home.ts
  ui/demo-pwa/src/alwatr-pwa.ts
  ui/demo-pwa/tsconfig.json
  ui/demo-pwa/web-dev-server.config.js
  ui/demo-pwa/workbox.config.js
Labels: enhancement

#559 refactor: use alwatr element instead lit
  core/router/README.md
  ui/demo-pwa/src/alwatr-page-home.ts
  ui/demo-pwa/src/alwatr-pwa.ts
  ui/element/src/element.ts
  ui/icon/package.json
  ui/icon/src/icon.ts
  uniquely/flight-finder-pwa/package.json
  uniquely/flight-finder-pwa/src/alwatr-pwa.ts
  uniquely/flight-finder-pwa/src/component/job-add-form.ts
  uniquely/flight-finder-pwa/src/component/job-item.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
  uniquely/flight-finder-pwa/src/style/ionic.normalize.ts
  uniquely/flight-finder-pwa/src/style/ionic.theming.ts
Labels: enhancement

#562 feat(ui/element): seprate mixins
  ui/element/src/element.ts
  ui/element/src/mixins/logging.ts
  ui/element/src/mixins/signal.ts
Labels: enhancement

#542 feat(ui-kit/chat): avatar element (3)
  ui/ui-kit/chat/chat-avatar.ts
  ui/ui-kit/tsconfig.json
Labels: enhancement

#563 fix(ui/element): listener list type
  ui/demo-pwa/src/alwatr-page-home.ts
  ui/element/src/mixins/signal.ts
Labels: enhancement

#564 refactor(demo-pwa): chat base demo
  ui/demo-pwa/index.html
  ui/demo-pwa/src/demo-chat.ts
  ui/demo-pwa/src/pwa-root.ts
  ui/demo-pwa/tsconfig.json
  ui/element/src/element.ts
Labels: new-feature

#557 feat(ff-pwa): root html, metas, manifest, icons
  uniquely/flight-finder-pwa/image/banner.jpg
  uniquely/flight-finder-pwa/image/icon-180.png
  uniquely/flight-finder-pwa/index.html
  uniquely/flight-finder-pwa/manifest.json
Labels: enhancement

#566 feat(element): AlwatrRootElement
  ui/demo-pwa/src/demo-chat.ts
  ui/demo-pwa/src/pwa-root.ts
  ui/element/package.json
  ui/element/src/element.ts
  ui/element/src/root.ts
  ui/element/tsconfig.json
  ui/icon/src/icon.ts
  uniquely/flight-finder-pwa/src/alwatr-pwa.ts
  uniquely/flight-finder-pwa/src/component/job-add-form.ts
  uniquely/flight-finder-pwa/src/component/job-item.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
Labels: new-feature

#565 feat(pwa): global style and root layout
  ui/demo-pwa/index.html
  ui/demo-pwa/l10n/fa-IR.json
  ui/demo-pwa/src/global.css
  ui/demo-pwa/src/pwa-root.ts
  ui/ui-kit/chat/chat-avatar.ts
Labels: new-feature

#544 feat(ui-kit/chat): bubble element (4)
  core/router/README.md
  ui/demo-pwa/src/demo-chat.ts
  ui/element/src/root.ts
  ui/ui-kit/chat/chat-avatar.ts
  ui/ui-kit/chat/chat-bubble.ts
  uniquely/flight-finder-pwa/src/alwatr-pwa.ts
  uniquely/flight-finder-pwa/src/component/job-add-form.ts
  uniquely/flight-finder-pwa/src/component/job-item.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
Labels: enhancement

#568 feat(chat-message): new chat element
  ui/ui-kit/src/chat/chat-avatar.ts
  ui/ui-kit/src/chat/chat-bubble.ts
  ui/ui-kit/src/chat/chat-message.ts
  ui/ui-kit/tsconfig.json
Labels: new-feature

#569 feat(ui): demo chat basic elements
  .vscode/settings.json
  ui/demo-pwa/index.html
  ui/demo-pwa/src/demo-chat.ts
  ui/demo-pwa/src/global.css
  ui/demo-pwa/src/page-chat.ts
  ui/demo-pwa/src/pwa-root.ts
  ui/element/src/root.ts
  ui/ui-kit/src/chat/chat-avatar.ts
  ui/ui-kit/src/chat/chat-bubble.ts
Labels: new-feature

#570 feat(ui-kit): material style tokens
  ui/demo-pwa/index.html
  ui/demo-pwa/src/global.css
  ui/demo-pwa/src/page-chat.ts
  ui/demo-pwa/style/helper/colors.css
  ui/demo-pwa/style/helper/elevation.css
  ui/demo-pwa/style/helper/motion.css
  ui/demo-pwa/style/helper/shape.css
  ui/demo-pwa/style/helper/state.css
  ui/demo-pwa/style/helper/typography.css
  ui/demo-pwa/style/index.css
  ui/demo-pwa/style/root.css
  ui/demo-pwa/style/safe-area.css
  ui/demo-pwa/style/theme/dark.css
  ui/demo-pwa/style/theme/light.css
  ui/demo-pwa/style/tokens/elevation.css
  ui/demo-pwa/style/tokens/motion.css
  ui/demo-pwa/style/tokens/palette.css
  ui/demo-pwa/style/tokens/shape.css
  ui/demo-pwa/style/tokens/state.css
  ui/demo-pwa/style/tokens/typography.css
  ui/ui-kit/src/chat/chat-bubble.ts
  ui/ui-kit/src/chat/chat-message.ts
  ui/ui-kit/src/elavation/style.ts
Labels: new-feature

#573 feat(page-chat): new demo
  ui/demo-pwa/src/page-chat.ts
  ui/element/src/root.ts
  ui/ui-kit/src/chat/chat-avatar.ts
  ui/ui-kit/src/chat/chat-bubble.ts
  ui/ui-kit/src/chat/chat-message.ts
Labels: new-feature

#580 feat(chat-list): new element for list of chats
  ui/demo-pwa/src/page-chat.ts
  ui/ui-kit/package.json
  ui/ui-kit/src/chat/chat-list.ts
  ui/ui-kit/tsconfig.json
Labels: new-feature

#582 feat(ui/tokens): spacing system
  ui/demo-pwa/src/page-chat.ts
  ui/demo-pwa/style/index.css
  ui/demo-pwa/style/tokens/spacing.css
  ui/ui-kit/src/chat/chat-avatar.ts
  ui/ui-kit/src/chat/chat-bubble.ts
  ui/ui-kit/src/chat/chat-list.ts
  ui/ui-kit/src/chat/chat-message.ts
Labels: new-feature

#585 feat(ui/tokens): new spacing columns
  ui/demo-pwa/src/page-chat.ts
  ui/demo-pwa/style/tokens/spacing.css
Labels: new-feature

#587 feat(chat): self property, gap and spaces
  ui/element/src/root.ts
  ui/ui-kit/src/chat/chat-bubble.ts
  ui/ui-kit/src/chat/chat-list.ts
  ui/ui-kit/src/chat/chat-message.ts
Labels: new-feature

#572 feat(core/type): make package
  core/type/README.md
  core/type/package.json
  core/type/tsconfig.json
  tsconfig.json
Labels: enhancement

#581 feat(element): DirectionMixin, LocalizeMixin
  ui/demo-pwa/src/page-chat.ts
  ui/element/package.json
  ui/element/src/dummy-element.ts
  ui/element/src/index.ts
  ui/element/src/mixins/direction.ts
  ui/element/src/mixins/localize.ts
  ui/element/src/mixins/logging.ts
  ui/element/src/mixins/signal.ts
  ui/element/src/root-element.ts
  ui/element/src/smart-element.ts
  ui/ui-kit/src/chat/chat-bubble.ts
  ui/ui-kit/src/chat/chat-message.ts
Labels: enhancement

#591 fix(core/router): preventDefault on svg link click
  core/router/src/trigger-click.ts
Labels: bugfix

#588 feat(ui-kit/icon-button): new component
  ui/demo-pwa/src/page-chat.ts
  ui/demo-pwa/style/tokens/state.css
  ui/ui-kit/src/icon-button/standard-icon-button.ts
Labels: enhancement

#593 feat(tokens): new motions and z-index
  .vscode/settings.json
  ui/demo-pwa/style/index.css
  ui/demo-pwa/style/tokens/motion.css
  ui/demo-pwa/style/tokens/z-index.css
Labels: new-feature

#594 feat(ui/icon): direction mixin
  ui/icon/src/icon.ts
Labels: enhancement

#595 feat(ui-kit/icon-button): icon flip-rtl
  ui/ui-kit/src/icon-button/standard-icon-button.ts
Labels: enhancement

#571 feat(ui/ui-kit): `chat-text-input` component
  core/signal/src/core.ts
  ui/demo-pwa/l10n/en-US.json
  ui/demo-pwa/l10n/fa-IR.json
  ui/demo-pwa/src/page-chat.ts
  ui/ui-kit/src/chat/chat-avatar.ts
  ui/ui-kit/src/chat/chat-text-input.ts
  ui/ui-kit/src/icon-button/standard-icon-button.ts
Labels: enhancement

#586 feat(ui-kit/chat-footer): component
  ui/demo-pwa/src/page-chat.ts
  ui/ui-kit/src/chat/chat-footer.ts
  ui/ui-kit/src/chat/chat-text-input.ts
Labels: enhancement

#596 feat(ui/chat): new alwatr-chat element
  ui/demo-pwa/src/page-chat.ts
  ui/demo-pwa/style/index.css
  ui/demo-pwa/style/tokens/scrollbar.css
  ui/ui-kit/src/chat/chat-footer.ts
  ui/ui-kit/src/chat/chat-list.ts
  ui/ui-kit/src/chat/chat.ts
Labels: new-feature

#597 feat: new ui design system
  .vscode/settings.json
  ui/demo-pwa/src/page-chat.ts
  ui/demo-pwa/style/helper/colors.css
  ui/demo-pwa/style/helper/elevation.css
  ui/demo-pwa/style/helper/motion.css
  ui/demo-pwa/style/helper/shape.css
  ui/demo-pwa/style/helper/state.css
  ui/demo-pwa/style/helper/typography.css
  ui/demo-pwa/style/index.css
  ui/demo-pwa/style/root.css
  ui/demo-pwa/style/theme/dark.css
  ui/demo-pwa/style/theme/light.css
  ui/demo-pwa/style/tokens/elevation.css
  ui/demo-pwa/style/tokens/motion.css
  ui/demo-pwa/style/tokens/palette.css
  ui/demo-pwa/style/tokens/scrollbar.css
  ui/demo-pwa/style/tokens/shape.css
  ui/demo-pwa/style/tokens/spacing.css
  ui/demo-pwa/style/tokens/state.css
  ui/demo-pwa/style/tokens/typography.css
  ui/demo-pwa/style/tokens/z-index.css
  ui/font/sahel.css
  ui/font/vazirmatn-roundot.css
  ui/font/vazirmatn.css
  ui/ui-kit/src/chat/chat-avatar.ts
  ui/ui-kit/src/chat/chat-bubble.ts
  ui/ui-kit/src/chat/chat-footer.ts
  ui/ui-kit/src/chat/chat-list.ts
  ui/ui-kit/src/chat/chat-message.ts
  ui/ui-kit/src/chat/chat-text-input.ts
  ui/ui-kit/src/chat/chat.ts
  ui/ui-kit/src/elavation/style.ts
  ui/ui-kit/src/icon-button/standard-icon-button.ts
Labels: new-feature

#600 feat(type): chat
  core/fetch/package.json
  core/fetch/src/fetch.ts
  core/fetch/src/type.ts
  core/fetch/tsconfig.json
  core/type/package.json
  core/type/src/chat.ts
  core/type/src/index.ts
  core/type/src/service-response.ts
  core/type/src/storage.ts
  demo/storage-engine/benchmark.ts
  demo/storage-engine/index.ts
  services/comment/package.json
  services/comment/src/lib/storage.ts
  services/comment/src/lib/type.ts
  services/comment/src/route/patch.ts
  services/comment/tsconfig.json
  ui/ui-kit/package.json
  ui/ui-kit/src/chat/chat-list.ts
  ui/ui-kit/src/chat/chat-message.ts
  ui/ui-kit/src/chat/chat.ts
  ui/ui-kit/tsconfig.json
Labels: enhancement
