Repository AliMD/alwatr, pull requests merged in 2022-10, with the labels that each got.

#298 Add UnicodeDigits document
  demo/index.html
  demo/math/index.html
  demo/math/translate-unicode-digits.ts
  packages/core/math/README.md
  packages/core/math/src/math.ts
  packages/core/math/src/unicode-digits.ts
Labels: documentation

#297 refactor(math): rewrite UnicodeDigits to improve performance
  demo/index.html
  demo/math/index.html
  demo/math/translate-unicode-digits.ts
  packages/core/math/README.md
  packages/core/math/src/math.ts
  packages/core/math/src/unicode-digits.ts
Labels: performance, breaking-change

#331 feat(classic-cloud): fix traefik network, Add data command to deploy script
  packages/classic-cloud/lib/deploy.sh
  packages/classic-cloud/traefik-proxy/_up.sh
Labels: major, new-feature, bugfix

#332 feat(fetch): retry pattern and refactor api
  demo/fetch/index.html
  demo/fetch/index.ts
  demo/fetch/style.css
  demo/index.html
  packages/core/fetch/README.md
  packages/core/fetch/src/fetch.ts
Labels: major, new-feature

#333 refactor(logger): lower incident attentions buy using disable tracing
  packages/core/logger/README.md
  packages/core/logger/src/logger.ts
  packages/core/logger/src/type.ts
Labels: enhancement, minor

#340 feat(fetch): cache strategy
  demo/fetch/index.html
  demo/fetch/index.ts
  demo/fetch/style.css
  packages/core/fetch/README.md
  packages/core/fetch/package.json
  packages/core/fetch/src/fetch.ts
  packages/core/i18n/src/i18n.ts
Labels: major, new-feature, breaking-change

#341 Release: v0.18.0
  .github/workflows/publish-container.yml
  CHANGELOG.md
  demo/CHANGELOG.md
  demo/fetch/index.html
  demo/fetch/index.ts
  demo/fetch/style.css
  demo/package.json
  lerna.json
  package.json
  packages/core/element/CHANGELOG.md
  packages/core/element/package.json
  packages/core/fetch/CHANGELOG.md
  packages/core/fetch/README.md
  packages/core/fetch/package.json
  packages/core/fetch/src/fetch.ts
  packages/core/i18n/CHANGELOG.md
  packages/core/i18n/package.json
  packages/core/i18n/src/i18n.ts
  packages/core/logger/CHANGELOG.md
  packages/core/logger/package.json
  packages/core/math/CHANGELOG.md
  packages/core/math/package.json
  packages/core/nano-server/CHANGELOG.md
  packages/core/nano-server/package.json
  packages/core/router/CHANGELOG.md
  packages/core/router/package.json
  packages/core/signal/CHANGELOG.md
  packages/core/signal/package.json
  packages/core/storage/CHANGELOG.md
  packages/core/storage/package.json
  packages/core/token/CHANGELOG.md
  packages/core/token/package.json
  packages/lab/zx-example/CHANGELOG.md
  packages/lab/zx-example/package.json
  packages/nanoservice/storage/CHANGELOG.md
  packages/nanoservice/storage/package.json
  packages/starter/nanoservice/CHANGELOG.md
  packages/starter/nanoservice/package.json
  packages/ui/font/CHANGELOG.md
  packages/ui/font/package.json
  yarn.lock
Labels: release

#350 fix: Import error in webpack
  packages/core/element/src/element.ts
  packages/core/i18n/src/i18n.ts
  packages/core/logger/src/logger.ts
  packages/core/math/src/math.ts
  packages/core/router/src/core.ts
  packages/core/router/src/router.ts
  packages/core/router/src/signal.ts
  packages/core/router/src/trigger-click.ts
  packages/core/router/src/trigger-popstate.ts
  packages/core/signal/src/core.ts
  packages/core/signal/src/signal.ts
  packages/core/storage/src/provider.ts
Labels: bugfix
