Repository AliMD/alwatr, pull requests merged in 2022-07, with the labels that each got.

#164 Feat/update packages
  package.json
  packages/core/fetch/src/fetch.ts
  packages/starter/microservice/package.json
  yarn.lock
Labels: enhancement

#165 fix(i18n): load resources issue
  packages/core/i18n/src/core.ts
  packages/core/i18n/src/i18n.ts
  packages/core/i18n/src/type.ts
Labels: bug

#166 feat(logger): node coloring support
  demo/logger/index.ts
  packages/core/logger/README.md
  packages/core/logger/src/logger.ts
Labels: enhancement

#167 New package: @alwatr/storage
  .gitignore
  demo/storage/big-data-test.ts
  demo/storage/index.ts
  demo/tsconfig.json
  packages/core/jatabase/README.md
  packages/core/jatabase/src/jatabase.ts
  packages/core/jatabase/src/type.ts
  packages/core/math/README.md
  packages/core/math/src/math.ts
  packages/core/micro-server/src/micro-server.ts
  packages/core/storage/README.md
  packages/core/storage/package.json
  packages/core/storage/src/storage.ts
  packages/core/storage/src/type.ts
  packages/core/storage/src/util.ts
  packages/core/storage/tsconfig.json
  tsconfig.json
Labels: documentation

#170 Storage: add API doc
  CHANGELOG.md
  README.md
  demo/CHANGELOG.md
  demo/storage/big-data-test.ts
  demo/storage/index.ts
  demo/tsconfig.json
  lerna.json
  packages/core/element/CHANGELOG.md
  packages/core/fetch/CHANGELOG.md
  packages/core/i18n/CHANGELOG.md
  packages/core/i18n/src/core.ts
  packages/core/i18n/src/type.ts
  packages/core/logger/CHANGELOG.md
  packages/core/math/CHANGELOG.md
  packages/core/micro-server/CHANGELOG.md
  packages/core/router/CHANGELOG.md
  packages/core/signal/CHANGELOG.md
  packages/core/storage/README.md
  packages/core/storage/src/storage.ts
  packages/core/storage/tsconfig.json
  packages/starter/microservice/CHANGELOG.md
  packages/ui/font/CHANGELOG.md
Labels: documentation

#171 Refactor and review nano-server and Nanoservice Starter kit
  .vscode/settings.json
  CHANGELOG.md
  packages/core/micro-server/CHANGELOG.md
  packages/core/micro-server/README.md
  packages/core/nano-server/CHANGELOG.md
  packages/core/nano-server/README.md
  packages/core/nano-server/package.json
  packages/core/nano-server/src/nano-server.ts
  packages/core/nano-server/src/type.ts
  packages/core/nano-server/tsconfig.json
  packages/starter/microservice/.env.example
  packages/starter/microservice/CHANGELOG.md
  packages/starter/microservice/src/app.ts
  packages/starter/nanoservice/.editorconfig
  packages/starter/nanoservice/.eslintignore
  packages/starter/nanoservice/.eslintrc.json
  packages/starter/nanoservice/.gitignore
  packages/starter/nanoservice/.prettierrc.json
  packages/starter/nanoservice/.vscode/extensions.json
  packages/starter/nanoservice/.vscode/settings.json
  packages/starter/nanoservice/CHANGELOG.md
  packages/starter/nanoservice/README.md
  packages/starter/nanoservice/demo.http
  packages/starter/nanoservice/package.json
  packages/starter/nanoservice/src/app.ts
  packages/starter/nanoservice/src/config.ts
  packages/starter/nanoservice/src/index.ts
  packages/starter/nanoservice/src/route/echo.ts
  packages/starter/nanoservice/src/route/home.ts
  packages/starter/nanoservice/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: enhancement
