Repository AliMD/alwatr, pull requests merged in 2022-04, with the labels that each got.

#128 New package: @alwatr/font
  .vscode/settings.json
  demo/font/index.html
  demo/index.html
  package/font/README.md
  package/font/font.css
  package/font/package.json
  package/font/vazirmatn/note.txt
  package/font/vazirmatn/vazirmatn-100.woff
  package/font/vazirmatn/vazirmatn-200.woff
  package/font/vazirmatn/vazirmatn-300.woff
  package/font/vazirmatn/vazirmatn-400.woff
  package/font/vazirmatn/vazirmatn-500.woff
  package/font/vazirmatn/vazirmatn-600.woff
  package/font/vazirmatn/vazirmatn-700.woff
  package/font/vazirmatn/vazirmatn-800.woff
  package/font/vazirmatn/vazirmatn-900.woff
  package/font/vazirmatn/vazirmatn-rd-100.woff
  package/font/vazirmatn/vazirmatn-rd-200.woff
  package/font/vazirmatn/vazirmatn-rd-300.woff
  package/font/vazirmatn/vazirmatn-rd-400.woff
  package/font/vazirmatn/vazirmatn-rd-500.woff
  package/font/vazirmatn/vazirmatn-rd-600.woff
  package/font/vazirmatn/vazirmatn-rd-700.woff
  package/font/vazirmatn/vazirmatn-rd-800.woff
  package/font/vazirmatn/vazirmatn-rd-900.woff
  package/font/vazirmatn/vazirmatn-rd[wght].woff2
  package/font/vazirmatn/vazirmatn[wght].woff2
Labels: enhancement

#134 Prettier config
  .editorconfig
  .eslintrc.yaml
  .prettierrc.json
  package.json
  yarn.lock
Labels: enhancement

#136 Release: v0.9.0
  CHANGELOG.md
  demo/CHANGELOG.md
  demo/package.json
  lerna.json
  package/fetch/CHANGELOG.md
  package/fetch/package.json
  package/i18n/CHANGELOG.md
  package/i18n/package.json
  package/i18n/src/i18n.ts
  package/i18n/src/signal.ts
  package/logger/CHANGELOG.md
  package/logger/README.md
  package/logger/package.json
  package/math/CHANGELOG.md
  package/math/package.json
  package/router/CHANGELOG.md
  package/router/README.md
  package/router/package.json
  package/router/src/router.ts
  package/router/src/type.ts
  package/signal/CHANGELOG.md
  package/signal/README.md
  package/signal/package.json
  package/signal/src/core.ts
  package/signal/src/signal.ts
Labels: release

#137 Release: v0.10.1
  .eslintrc.yaml
  .github/workflows/build.yaml
  .github/workflows/lint.yml
  .vscode/settings.json
  CHANGELOG.md
  demo/CHANGELOG.md
  demo/font/index.html
  demo/index.html
  demo/package.json
  demo/router/index.ts
  lerna.json
  package.json
  package/fetch/CHANGELOG.md
  package/fetch/package.json
  package/font/CHANGELOG.md
  package/font/README.md
  package/font/font.css
  package/font/package.json
  package/font/vazirmatn/note.txt
  package/font/vazirmatn/vazirmatn-100.woff
  package/font/vazirmatn/vazirmatn-200.woff
  package/font/vazirmatn/vazirmatn-300.woff
  package/font/vazirmatn/vazirmatn-400.woff
  package/font/vazirmatn/vazirmatn-500.woff
  package/font/vazirmatn/vazirmatn-600.woff
  package/font/vazirmatn/vazirmatn-700.woff
  package/font/vazirmatn/vazirmatn-800.woff
  package/font/vazirmatn/vazirmatn-900.woff
  package/font/vazirmatn/vazirmatn-rd-100.woff
  package/font/vazirmatn/vazirmatn-rd-200.woff
  package/font/vazirmatn/vazirmatn-rd-300.woff
  package/font/vazirmatn/vazirmatn-rd-400.woff
  package/font/vazirmatn/vazirmatn-rd-500.woff
  package/font/vazirmatn/vazirmatn-rd-600.woff
  package/font/vazirmatn/vazirmatn-rd-700.woff
  package/font/vazirmatn/vazirmatn-rd-800.woff
  package/font/vazirmatn/vazirmatn-rd-900.woff
  package/font/vazirmatn/vazirmatn-rd[wght].woff2
  package/font/vazirmatn/vazirmatn[wght].woff2
  package/i18n/CHANGELOG.md
  package/i18n/package.json
  package/i18n/src/core.ts
  package/i18n/src/i18n.ts
  package/i18n/src/signal.ts
  package/logger/CHANGELOG.md
  package/logger/package.json
  package/math/CHANGELOG.md
  package/math/package.json
  package/router/CHANGELOG.md
  package/router/package.json
  package/router/src/core.ts
  package/router/src/router.ts
  package/router/src/signal.ts
  package/signal/CHANGELOG.md
  package/signal/package.json
  package/signal/src/core.ts
  package/signal/src/signal.ts
  yarn.lock
Labels: release

#141 chore(vscode): recommend extentions and update settings
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
  .vscode/extensions.json
  .vscode/settings.json
  README.md
Labels: enhancement, release

#146 Font sahel demo and fix font-weight
  demo/font/index.html
  packages/ui/font/font.css
Labels: enhancement

#148 Prettier all files
  .editorconfig
  .eslintrc.json
  CHANGELOG.md
  CONTRIBUTING.md
  demo/CHANGELOG.md
  demo/font/index.html
  demo/logger/index.ts
  demo/router/index.html
  demo/tsconfig.json
  lerna.json
  packages/core/element/CHANGELOG.md
  packages/core/element/tsconfig.json
  packages/core/fetch/CHANGELOG.md
  packages/core/fetch/src/fetch.ts
  packages/core/fetch/tsconfig.json
  packages/core/i18n/CHANGELOG.md
  packages/core/i18n/src/core.ts
  packages/core/i18n/src/i18n.ts
  packages/core/i18n/src/type.ts
  packages/core/i18n/tsconfig.json
  packages/core/logger/CHANGELOG.md
  packages/core/logger/README.md
  packages/core/logger/src/logger.ts
  packages/core/logger/src/type.ts
  packages/core/logger/tsconfig.json
  packages/core/math/CHANGELOG.md
  packages/core/math/README.md
  packages/core/math/src/math.ts
  packages/core/math/src/type.ts
  packages/core/math/tsconfig.json
  packages/core/micro-server/src/micro-server.ts
  packages/core/micro-server/src/type.ts
  packages/core/micro-server/tsconfig.json
  packages/core/router/CHANGELOG.md
  packages/core/router/README.md
  packages/core/router/src/core.ts
  packages/core/router/src/router.ts
  packages/core/router/src/trigger-click.ts
  packages/core/router/src/trigger-popstate.ts
  packages/core/router/src/type.ts
  packages/core/router/tsconfig.json
  packages/core/signal/CHANGELOG.md
  packages/core/signal/README.md
  packages/core/signal/src/core.ts
  packages/core/signal/src/signal.ts
  packages/core/signal/src/type.ts
  packages/core/signal/tsconfig.json
  packages/starter/microservice/.vscode/settings.json
  packages/ui/font/CHANGELOG.md
  packages/ui/font/README.md
  tsconfig.json
Labels: enhancement
