Repository AliMD/alwatr, pull requests merged in 2022-11, with the labels that each got.

#353 Feat/alwatr font
  .vscode/settings.json
  demo/font/index.html
  demo/icon/index.html
  demo/index.html
  demo/logger/index.html
  demo/math/index.html
  demo/router/index.html
  demo/signal/index.html
  packages/ui/font/README.md
  packages/ui/font/font.css
  packages/ui/font/package.json
  packages/ui/font/sahel.css
  packages/ui/font/vazirmatn-roundot.css
  packages/ui/font/vazirmatn-roundot/vazirmatn-roundot-100.woff
  packages/ui/font/vazirmatn-roundot/vazirmatn-roundot-200.woff
  packages/ui/font/vazirmatn-roundot/vazirmatn-roundot-300.woff
  packages/ui/font/vazirmatn-roundot/vazirmatn-roundot-400.woff
  packages/ui/font/vazirmatn-roundot/vazirmatn-roundot-500.woff
  packages/ui/font/vazirmatn-roundot/vazirmatn-roundot-600.woff
  packages/ui/font/vazirmatn-roundot/vazirmatn-roundot-700.woff
  packages/ui/font/vazirmatn-roundot/vazirmatn-roundot-800.woff
  packages/ui/font/vazirmatn-roundot/vazirmatn-roundot-900.woff
  packages/ui/font/vazirmatn-roundot/vazirmatn-roundot[wght].woff2
  packages/ui/font/vazirmatn.css
  packages/ui/font/vazirmatn/note.txt
Labels: enhancement

#359 fix(storage): `_last` id issue, update cache keys issue
  packages/core/storage/src/storage.ts
  packages/core/storage/src/type.ts
Labels: minor, breaking-change, bugfix

#361 docs(storage): update readme
  packages/core/storage/README.md
Labels: documentation

#360 refactor(storage): new storage file structure
  packages/core/storage/README.md
  packages/core/storage/src/storage.ts
  packages/core/storage/src/type.ts
Labels: enhancement, minor

#363 feat(classic-cloud): uplaod/download data and new simpler script
  .gitattributes
  packages/classic-cloud/lib/deploy.sh
  packages/classic-cloud/lib/manage.sh
  packages/classic-cloud/wordpress/env/example.env
  packages/classic-cloud/wordpress/php/Dockerfile
Labels: priority-high, minor, new-feature

#364 refactor(fetch): separate handle methods
  packages/core/fetch/src/fetch.ts
  packages/ui/icon/src/icon.ts
Labels: enhancement, major

#367 fix(fetch): _handleRemoveDuplicate
  packages/core/fetch/README.md
  packages/core/fetch/src/fetch.ts
Labels: documentation, minor, new-feature

#368 fix(fetch): cacheStorageName issue
  demo/fetch/index.html
  demo/fetch/index.ts
  demo/fetch/style.css
  packages/core/fetch/README.md
  packages/core/fetch/src/fetch.ts
Labels: bugfix

#369 feat(fetch): revalidate callback for `stale_while_revalidate` cache strategy.
  demo/fetch/index.ts
  packages/core/fetch/README.md
  packages/core/fetch/src/fetch.ts
Labels: minor, new-feature

#370 refactor(router): initial options
  packages/core/router/src/router.ts
Labels: enhancement

#362 New Package: `@alwatr/icon`
  .vscode/settings.json
  demo/icon/index.html
  demo/icon/index.ts
  demo/index.html
  packages/ui/icon/src/icon.ts
Labels: enhancement, new-feature

#371 feat(fetch): retry delay
  packages/core/fetch/src/fetch.ts
Labels: new-feature

#372 Release: v0.20.0
  .gitattributes
  .vscode/settings.json
  CHANGELOG.md
  demo/CHANGELOG.md
  demo/fetch/index.html
  demo/fetch/index.ts
  demo/fetch/style.css
  demo/icon/index.html
  demo/icon/index.ts
  demo/index.html
  demo/package.json
  lerna.json
  packages/classic-cloud/lib/deploy.sh
  packages/classic-cloud/lib/manage.sh
  packages/classic-cloud/wordpress/env/example.env
  packages/classic-cloud/wordpress/php/Dockerfile
  packages/core/element/CHANGELOG.md
  packages/core/element/package.json
  packages/core/fetch/CHANGELOG.md
  packages/core/fetch/README.md
  packages/core/fetch/package.json
  packages/core/fetch/src/fetch.ts
  packages/core/i18n/CHANGELOG.md
  packages/core/i18n/package.json
  packages/core/logger/CHANGELOG.md
  packages/core/logger/package.json
  packages/core/math/CHANGELOG.md
  packages/core/math/package.json
  packages/core/nano-server/CHANGELOG.md
  packages/core/nano-server/package.json
  packages/core/router/CHANGELOG.md
  packages/core/router/package.json
  packages/core/router/src/router.ts
  packages/core/signal/CHANGELOG.md
  packages/core/signal/package.json
  packages/core/storage/CHANGELOG.md
  packages/core/storage/README.md
  packages/core/storage/package.json
  packages/core/storage/src/storage.ts
  packages/core/storage/src/type.ts
  packages/core/token/CHANGELOG.md
  packages/core/token/package.json
  packages/lab/zx-example/CHANGELOG.md
  packages/lab/zx-example/package.json
  packages/nanoservice/storage/CHANGELOG.md
  packages/nanoservice/storage/package.json
  packages/starter/nanoservice/CHANGELOG.md
  packages/starter/nanoservice/package.json
  packages/ui/font/CHANGELOG.md
  packages/ui/font/README.md
  packages/ui/font/package.json
  packages/ui/icon/CHANGELOG.md
  packages/ui/icon/package.json
  packages/ui/icon/src/icon.ts
Labels: release

#380 feat/nanoserver
  packages/core/nano-server/src/nano-server.ts
  packages/starter/nanoservice/.eslintrc.json
  packages/starter/nanoservice/.gitignore
  packages/starter/nanoservice/package.json
Labels: enhancement

#381 docs(fonts): update demo
  demo/font/simple.html
  packages/ui/font/README.md
Labels: documentation

#382 feat(classic-cloud): restore ssh agent for deploy scripts
  .gitattributes
  packages/classic-cloud/adminer/deploy.sh
  packages/classic-cloud/distribution/deploy.sh
  packages/classic-cloud/lib/deploy.sh
  packages/classic-cloud/lib/manage.sh
  packages/classic-cloud/mariadb/_up.sh
  packages/classic-cloud/mariadb/deploy.sh
  packages/classic-cloud/php-apache/_up.sh
  packages/classic-cloud/php-apache/deploy.sh
  packages/classic-cloud/static-file/deploy.sh
  packages/classic-cloud/traefik-proxy/_up.sh
  packages/classic-cloud/traefik-proxy/deploy.sh
  packages/classic-cloud/wordpress/_up.sh
  packages/classic-cloud/wordpress/deploy.sh
Labels: new-feature

#383 feat(cloud): add common vpn services
  packages/lab/ipsec/compose.yml
  packages/lab/ipsec/deploy.sh
  packages/lab/ipsec/env/example.env
  packages/lab/openvpn/compose.yml
  packages/lab/openvpn/deploy.sh
  packages/lab/openvpn/env/example.env
  packages/lab/shadowsocks/compose.yml
  packages/lab/shadowsocks/deploy.sh
  packages/lab/shadowsocks/env/example.env
  packages/lab/v2fly/compose.yml
  packages/lab/v2fly/config/client-vmess-socks.json
  packages/lab/v2fly/config/server-vmess-ws.json
  packages/lab/v2fly/deploy.sh
  packages/lab/v2fly/env/example.env
  packages/lab/wireguard/compose.yml
  packages/lab/wireguard/deploy.sh
  packages/lab/wireguard/env/example.env
Labels: new-feature

#384 chore: update all packages readme and desc
  packages/classic-cloud/adminer/README.md
  packages/classic-cloud/distribution/README.md
  packages/classic-cloud/mariadb/README.md
  packages/classic-cloud/php-apache/README.md
  packages/classic-cloud/static-file/README.md
  packages/classic-cloud/wordpress/README.md
  packages/container/README.md
  packages/container/alpine/README.md
  packages/container/nginx/README.md
  packages/container/tdlib/README.md
  packages/core/element/README.md
  packages/core/fetch/README.md
  packages/core/i18n/README.md
  packages/core/logger/README.md
  packages/core/math/README.md
  packages/core/nano-server/README.md
  packages/core/router/README.md
  packages/core/signal/README.md
  packages/core/storage/README.md
  packages/core/token/README.md
  packages/starter/pwa/README.md
  packages/ui/font/README.md
  packages/ui/font/package.json
  packages/ui/icon/README.md
  packages/ui/icon/package.json
Labels: documentation

#385 Refactor docs folder and add security
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/SECURITY.md
  docs/image/logo.svg
Labels: documentation

#386 docs(icon): readme with icon gallery
  packages/ui/icon/README.md
Labels: documentation

#387 docs(icon): use outline icons in readme
  packages/ui/icon/README.md
Labels: documentation

#392 fix(starter/nanoservice): review and improve
  .gitignore
  package.json
  packages/starter/nanoservice/package.json
  packages/starter/nanoservice/src/lib/config.ts
Labels: enhancement, bugfix

#394 feat(storage): keys issue and get all data
  packages/core/storage/src/storage.ts
Labels: new-feature, bugfix

#391 refactor(service/storage): rewrite structure
  packages/core/nano-server/README.md
  packages/core/nano-server/package.json
  packages/core/nano-server/src/nano-server.ts
  packages/core/nano-server/src/type.ts
  packages/core/storage/README.md
  packages/core/storage/src/storage.ts
  packages/nanoservice/storage/README.md
  packages/nanoservice/storage/demo.http
  packages/nanoservice/storage/package.json
  packages/nanoservice/storage/src/index.ts
  packages/nanoservice/storage/src/lib/config.ts
  packages/nanoservice/storage/src/lib/storage-provider.ts
  packages/nanoservice/storage/src/lib/token.ts
  packages/nanoservice/storage/src/lib/type.ts
  packages/nanoservice/storage/src/route/all.ts
  packages/nanoservice/storage/src/route/delete.ts
  packages/nanoservice/storage/src/route/get.ts
  packages/nanoservice/storage/src/route/home.ts
  packages/nanoservice/storage/src/route/keys.ts
  packages/nanoservice/storage/src/route/patch.ts
  packages/nanoservice/storage/src/route/update.ts
Labels: enhancement

#399 feat(fetch): support nodejs
  demo/fetch/node.ts
  packages/core/fetch/src/fetch.ts
Labels: bugfix

#401 refactor(service/storage): rename nanoservice/storage to service/storage-server
  packages/service/README.md
  packages/service/storage-server/CHANGELOG.md
  packages/service/storage-server/Dockerfile
  packages/service/storage-server/README.md
  packages/service/storage-server/demo.http
  packages/service/storage-server/package.json
  packages/service/storage-server/src/index.ts
  packages/service/storage-server/src/lib/config.ts
  packages/service/storage-server/src/lib/nano-server.ts
  packages/service/storage-server/src/lib/storage-provider.ts
  packages/service/storage-server/src/route/all.ts
  packages/service/storage-server/src/route/delete.ts
  packages/service/storage-server/src/route/get.ts
  packages/service/storage-server/src/route/keys.ts
  packages/service/storage-server/src/route/patch.ts
  packages/service/storage-server/tsconfig.json
Labels: major, breaking-change

#402 refactor(storage): rename to storage-engine
  demo/storage-engine/big-data-test.ts
  demo/storage-engine/index.ts
  demo/tsconfig.json
  packages/core/storage-engine/CHANGELOG.md
  packages/core/storage-engine/README.md
  packages/core/storage-engine/package.json
  packages/core/storage-engine/src/provider.ts
  packages/core/storage-engine/src/storage.ts
  packages/core/storage-engine/src/type.ts
  packages/core/storage-engine/src/util.ts
  packages/core/storage-engine/tsconfig.json
  packages/service/storage-server/package.json
  packages/service/storage-server/src/lib/storage-provider.ts
  packages/service/storage-server/src/route/patch.ts
  tsconfig.json
Labels: major, breaking-change

#400 refactor(fetch): remove getJson
  demo/fetch/node.ts
  packages/core/fetch/README.md
  packages/core/fetch/src/fetch.ts
  packages/core/i18n/src/i18n.ts
Labels: major, breaking-change

#403 refactor(storage-engine): rename AlwatrStorageEngine
  demo/storage-engine/big-data-test.ts
  demo/storage-engine/index.ts
  packages/core/storage-engine/README.md
  packages/core/storage-engine/package.json
  packages/core/storage-engine/src/provider.ts
  packages/core/storage-engine/src/storage-engine.ts
  packages/core/storage-engine/src/type.ts
  packages/core/storage-engine/src/util.ts
  packages/service/storage-server/src/lib/storage-provider.ts
Labels: major, breaking-change

#405 feat(nano-server): keep alive performance and options
  packages/core/nano-server/README.md
  packages/core/nano-server/src/nano-server.ts
  packages/core/nano-server/src/type.ts
Labels: minor, new-feature, performance

#406 fix(storage-client): nodejs memory leak issue and improve performance
  demo/storage-client/benchmark.ts
  demo/storage-client/big-data-test.ts
  packages/core/storage-client/src/storage-client.ts
  packages/core/storage-client/src/type.ts
Labels: minor, performance, bugfix

#407 perf(fetch): Improve performance and decrease memory usage
  packages/core/fetch/src/fetch.ts
Labels: minor, performance, bugfix

#408 chore: use @types/web
  package.json
  yarn.lock
Labels: dependencies

#409 feat(v2fly): mux
  packages/lab/v2fly/config/client-vmess-socks.json
  packages/lab/v2fly/config/server-vmess-ws.json
Labels: new-feature

#393 fix(logger): node issues
  .vscode/settings.json
  packages/core/logger/src/logger.ts
Labels: bugfix

#410 feat(storage-engine): storage meta and auto_increment id
  packages/core/storage-engine/src/storage-engine.ts
  packages/core/storage-engine/src/type.ts
Labels: new-feature

#411 fix(storage-client): handle 404 in benchmark
  demo/storage-client/benchmark.ts
  packages/core/storage-client/README.md
  packages/core/storage-client/src/storage-client.ts
Labels: bugfix

#414 feat(workflows): Add To GitHub projects
  .github/workflows/add-to-project.yml
  .github/workflows/lock-closed.yml
Labels: ci

#418 chore(deps): upgrade
  package.json
  packages/service/storage-server/package.json
  packages/starter/nanoservice/package.json
  yarn.lock
Labels: dependencies

#419 fix(storage-engine): auto_increment issue
  packages/core/storage-client/package.json
  packages/core/storage-client/src/storage-client.ts
  packages/core/storage-client/src/type.ts
  packages/core/storage-engine/src/storage-engine.ts
  packages/core/storage-engine/src/type.ts
  packages/service/storage-server/package.json
  packages/starter/nanoservice/package.json
Labels: bugfix

#420 lint: format all files
  demo/fetch/style.css
  demo/font/simple.html
  demo/icon/index.html
  demo/index.html
  demo/logger/index.html
  demo/math/index.html
  demo/math/translate-unicode-digits.ts
  demo/router/index.html
  demo/signal/index.html
  demo/storage-client/benchmark.ts
  demo/storage-client/index.ts
  demo/storage-engine/big-data-test.ts
  packages/container/nginx/www/html/index.html
  packages/core/fetch/src/fetch.ts
  packages/core/math/README.md
  packages/core/math/src/unicode-digits.ts
  packages/core/nano-server/src/nano-server.ts
  packages/core/signal/src/core.ts
  packages/core/signal/src/signal.ts
  packages/core/storage-client/README.md
  packages/core/storage-client/tsconfig.json
  packages/core/storage-engine/README.md
  packages/lab/ipsec/compose.yml
  packages/lab/openvpn/compose.yml
  packages/lab/v2fly/config/client-vmess-socks.json
  packages/lab/v2fly/config/server-vmess-ws.json
  packages/lab/wireguard/compose.yml
  packages/service/storage-server/src/route/delete.ts
  packages/service/storage-server/src/route/get.ts
  packages/service/storage-server/src/route/has.ts
  packages/ui/font/vazirmatn-roundot.css
  packages/ui/icon/README.md
  packages/ui/icon/tsconfig.json
  tsconfig.json
Labels: enhancement

#421 Fix/lint
  .vscode/extensions.json
  packages/core/nano-server/src/nano-server.ts
  packages/core/storage-engine/package.json
  packages/starter/nanoservice/.eslintrc.json
Labels: bugfix

#427 feat(token): new token option & improve types
  packages/core/fetch/src/fetch.ts
  packages/core/fetch/src/type.ts
  packages/core/nano-server/src/nano-server.ts
  packages/core/storage-client/src/storage-client.ts
Labels: minor, new-feature

#428 refactor(storage-server): default configs
  packages/service/storage-server/demo.http
  packages/service/storage-server/src/lib/config.ts
Labels: enhancement

#429 Release: v.23.0
  .github/workflows/add-to-project.yml
  CHANGELOG.md
  demo/CHANGELOG.md
  demo/package.json
  lerna.json
  package.json
  packages/core/element/CHANGELOG.md
  packages/core/element/package.json
  packages/core/fetch/CHANGELOG.md
  packages/core/fetch/package.json
  packages/core/fetch/src/fetch.ts
  packages/core/fetch/src/type.ts
  packages/core/i18n/CHANGELOG.md
  packages/core/i18n/package.json
  packages/core/logger/CHANGELOG.md
  packages/core/logger/package.json
  packages/core/math/CHANGELOG.md
  packages/core/math/package.json
  packages/core/nano-server/CHANGELOG.md
  packages/core/nano-server/package.json
  packages/core/nano-server/src/nano-server.ts
  packages/core/router/CHANGELOG.md
  packages/core/router/package.json
  packages/core/signal/CHANGELOG.md
  packages/core/signal/package.json
  packages/core/storage-client/CHANGELOG.md
  packages/core/storage-client/package.json
  packages/core/storage-client/src/storage-client.ts
  packages/core/storage-engine/CHANGELOG.md
  packages/core/storage-engine/package.json
  packages/core/token/CHANGELOG.md
  packages/core/token/package.json
  packages/lab/zx-example/CHANGELOG.md
  packages/lab/zx-example/package.json
  packages/service/storage-server/CHANGELOG.md
  packages/service/storage-server/demo.http
  packages/service/storage-server/package.json
  packages/service/storage-server/src/lib/config.ts
  packages/starter/nanoservice/CHANGELOG.md
  packages/starter/nanoservice/package.json
  packages/ui/font/CHANGELOG.md
  packages/ui/font/package.json
  packages/ui/icon/CHANGELOG.md
  packages/ui/icon/package.json
  yarn.lock
Labels: release

#431 refactor(storage-client): separate port and host in config
  demo/storage-client/benchmark.ts
  demo/storage-client/index.ts
  packages/core/storage-client/src/storage-client.ts
  packages/core/storage-client/src/type.ts
Labels: breaking-change

#432 fix(demo/storage-client): set default token
  demo/storage-client/index.ts
Labels: minor, bugfix

#433 fix(nano-server): handle preflight request
  packages/core/nano-server/src/nano-server.ts
  packages/core/nano-server/src/type.ts
Labels: minor, new-feature

#435 feat(storage-service): dockerize #434
  .github/workflows/publish-container.yml
  packages/container/nginx/README.md
  packages/service/storage-server/Dockerfile
  packages/service/storage-server/src/lib/config.ts
Labels: enhancement, new-feature

#438 fix: use ~ for package version
  demo/package.json
  package.json
  packages/core/element/package.json
  packages/core/fetch/package.json
  packages/core/i18n/package.json
  packages/core/logger/package.json
  packages/core/math/package.json
  packages/core/nano-server/package.json
  packages/core/router/package.json
  packages/core/signal/package.json
  packages/core/storage-client/package.json
  packages/core/storage-engine/package.json
  packages/core/token/package.json
  packages/lab/zx-example/package.json
  packages/service/storage-server/package.json
  packages/starter/nanoservice/package.json
  packages/ui/icon/package.json
  yarn.lock
Labels: minor, bugfix

#439 fix(storage-server): docker build process
  packages/container/nginx/README.md
  packages/service/storage-server/.dockerignore
  packages/service/storage-server/Dockerfile
Labels: ci, performance, bugfix

#436 breaking-change: document object and server response types
  .github/workflows/publish-container.yml
  demo/storage-client/benchmark.ts
  demo/storage-client/index.ts
  demo/storage-engine/big-data-test.ts
  demo/storage-engine/index.ts
  packages/core/fetch/src/fetch.ts
  packages/core/fetch/src/type.ts
  packages/core/nano-server/package.json
  packages/core/nano-server/src/nano-server.ts
  packages/core/nano-server/src/type.ts
  packages/core/nano-server/tsconfig.json
  packages/core/storage-client/README.md
  packages/core/storage-client/src/storage-client.ts
  packages/core/storage-client/src/type.ts
  packages/core/storage-engine/README.md
  packages/core/storage-engine/package.json
  packages/core/storage-engine/src/provider.ts
  packages/core/storage-engine/src/storage-engine.ts
  packages/core/storage-engine/src/type.ts
  packages/core/storage-engine/src/util.ts
  packages/core/storage-engine/tsconfig.json
  packages/service/storage-server/demo.http
  packages/service/storage-server/package.json
  packages/service/storage-server/src/route/patch.ts
Labels: major, breaking-change

#442 feat(storage-engine): improve provider debug
  packages/core/storage-engine/src/provider.ts
  packages/core/storage-engine/src/storage-engine.ts
Labels: enhancement
