Repository AliMD/alwatr, pull requests merged in 2022-09, with the labels that each got.

#257 Refactor deployment scrypts
  .gitattributes
  .gitignore
  packages/classic-cloud/adminer/.env.example
  packages/classic-cloud/adminer/_up.sh
  packages/classic-cloud/adminer/deploy.sh
  packages/classic-cloud/adminer/env/example.env
  packages/classic-cloud/lib/deploy.sh
  packages/classic-cloud/mariadb/.env.example
  packages/classic-cloud/mariadb/_up.sh
  packages/classic-cloud/mariadb/deploy.sh
  packages/classic-cloud/mariadb/env/example.env
  packages/classic-cloud/php-apache/.env.example
  packages/classic-cloud/php-apache/_up.sh
  packages/classic-cloud/php-apache/deploy.sh
  packages/classic-cloud/php-apache/env/example.env
  packages/classic-cloud/static-file/_up.sh
  packages/classic-cloud/static-file/deploy.sh
  packages/classic-cloud/traefik-proxy/.env.example
  packages/classic-cloud/traefik-proxy/_up.sh
  packages/classic-cloud/traefik-proxy/deploy.sh
  packages/classic-cloud/traefik-proxy/env/example.env
  packages/classic-cloud/wordpress/.env.example
  packages/classic-cloud/wordpress/_up.sh
  packages/classic-cloud/wordpress/deploy.sh
  packages/classic-cloud/wordpress/env/example.env
Labels: enhancement

#258 feat(rnnoise-model): ffmpge rnnoise models
  packages/lab/rnnoise-model/README.md
  packages/lab/rnnoise-model/general-record.rnnn
  packages/lab/rnnoise-model/general.rnnn
  packages/lab/rnnoise-model/speech-record.rnnn
  packages/lab/rnnoise-model/voice-record.rnnn
  packages/lab/rnnoise-model/voice.rnnn
Labels: enhancement

#221 New Package: Alwatr Accelerated Nginx Container
  .github/workflows/publish-container.yml
  packages/classic-cloud/lib/deploy.sh
  packages/classic-cloud/mariadb/_up.sh
  packages/classic-cloud/php-apache/_up.sh
  packages/classic-cloud/static-file/.env.example
  packages/classic-cloud/static-file/_up.sh
  packages/classic-cloud/static-file/compose.yml
  packages/classic-cloud/static-file/env/example.env
  packages/classic-cloud/traefik-proxy/_up.sh
  packages/classic-cloud/wordpress/_up.sh
  packages/classic-cloud/wordpress/env/example.env
  packages/container/nginx/.dockerignore
  packages/container/nginx/Dockerfile
  packages/container/nginx/README.md
  packages/container/nginx/conf/entrypoint.d/10-envsubst-on-templates.sh
  packages/container/nginx/conf/entrypoint.d/20-tune-worker-processes.sh
  packages/container/nginx/conf/entrypoint.sh
  packages/container/nginx/conf/nginx.conf
  packages/container/nginx/conf/templates/00-main.conf.template
  packages/container/nginx/conf/templates/10-event.conf.template
  packages/container/nginx/conf/templates/20-http-include.conf.template
  packages/container/nginx/conf/templates/http.d/00-main.conf.template
  packages/container/nginx/conf/templates/http.d/10-real-ip.conf.template
  packages/container/nginx/conf/templates/http.d/20-log.conf.template
  packages/container/nginx/conf/templates/http.d/30-mime-types.conf.template
  packages/container/nginx/conf/templates/http.d/40-map-expire.conf.template
  packages/container/nginx/conf/templates/http.d/41-map-status-text.conf.template
  packages/container/nginx/conf/templates/http.d/50-temp-path.conf.template
  packages/container/nginx/conf/templates/http.d/60-performance.conf.template
  packages/container/nginx/conf/templates/http.d/70-request-limit.conf.template
  packages/container/nginx/conf/templates/http.d/80-header.conf.template
  packages/container/nginx/conf/templates/location.d/10-error-page.conf.template
  packages/container/nginx/conf/templates/location.d/30-server-info.conf.template
  packages/container/nginx/conf/templates/location.d/40-secure.conf.template
  packages/container/nginx/conf/templates/location.d/90-secure-wp.conf.template
  packages/container/nginx/conf/templates/server/00-default.conf.template
  packages/container/nginx/www/_error.html
  packages/container/nginx/www/html/index.html
Labels: enhancement

#262 Fix/nginx
  packages/classic-cloud/adminer/compose.yml
  packages/classic-cloud/lib/deploy.sh
  packages/classic-cloud/mariadb/compose.yml
  packages/classic-cloud/php-apache/compose.yml
  packages/classic-cloud/static-file/compose.yml
  packages/classic-cloud/static-file/env/example.env
  packages/classic-cloud/static-file/nginx
  packages/classic-cloud/traefik-proxy/_up.sh
  packages/classic-cloud/traefik-proxy/compose.yml
  packages/classic-cloud/traefik-proxy/traefik.toml
  packages/classic-cloud/wordpress/compose.yml
  packages/container/nginx/Dockerfile
  packages/container/nginx/conf/templates/20-http-include.conf.template
  packages/container/nginx/conf/templates/http.d/00-main.conf.template
  packages/container/nginx/conf/templates/http.d/30-mime-types.conf.template
  packages/container/nginx/www/html/index.html
Labels: bug

#265 fix(classic-cloud): review and fix issues
  packages/classic-cloud/adminer/compose.yml
  packages/classic-cloud/adminer/env/example.env
  packages/classic-cloud/mariadb/compose.yml
  packages/classic-cloud/mariadb/env/example.env
  packages/classic-cloud/php-apache/compose.yml
  packages/classic-cloud/php-apache/php/fix-permition.sh
  packages/classic-cloud/traefik-proxy/compose.yml
  packages/classic-cloud/traefik-proxy/env/example.env
  packages/classic-cloud/wordpress/compose.yml
  packages/classic-cloud/wordpress/env/example.env
  packages/classic-cloud/wordpress/php/fix-permition.sh
  packages/container/nginx/Dockerfile
Labels: bug

#268 feat(storage): add forEach and fix cashed keys issue
  packages/classic-cloud/wordpress/compose.yml
  packages/core/storage/README.md
  packages/core/storage/src/storage.ts
Labels: bug, enhancement

#274 Fix/storagefeat(storage): force save and exit hook to prevent data lost
  packages/core/storage/package.json
  packages/core/storage/src/storage.ts
  packages/core/storage/src/type.ts
  packages/core/storage/src/util.ts
  yarn.lock
Labels: bug, enhancement

#275 Release: v0.16.1
  CHANGELOG.md
  lerna.json
  packages/classic-cloud/traefik-proxy/_up.sh
  packages/container/nginx/Dockerfile
  packages/container/nginx/conf/templates/http.d/00-main.conf.template
  packages/core/storage/CHANGELOG.md
  packages/core/storage/package.json
  packages/core/storage/src/storage.ts
  packages/core/storage/src/type.ts
  packages/core/storage/src/util.ts
  packages/nanoservice/storage/CHANGELOG.md
  packages/nanoservice/storage/package.json
  yarn.lock
Labels: release

#272 `accident` must inherit from `console.warn` not `console.error`
  packages/core/logger/src/logger.ts
Labels: bug, enhancement

#283 feat: add new workflows
  .github/CODEOWNERS
  .github/labels.yml
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/lint.yaml
  .github/workflows/lock-closed.yml
  .github/workflows/pr-labels.yml
  .github/workflows/publish-container.yml
  .github/workflows/publish-npm.yml
  .github/workflows/stale.yml
  .github/workflows/sync-labels.yml
Labels: enhancement

#286 refactor(storage): synchronous operations and fix many bugs
  demo/storage/big-data-test.ts
  demo/storage/index.ts
  packages/core/storage/README.md
  packages/core/storage/src/provider.ts
  packages/core/storage/src/storage.ts
  packages/core/storage/src/type.ts
  packages/core/storage/src/util.ts
Labels: breaking-change

#287 Improve eslint and prettier
  .editorconfig
  .eslintrc.json
  .github/dependabot.yml
  .github/labels.yml
  .github/workflows/codeql.yaml
  .github/workflows/lock-closed.yml
  .github/workflows/pr-labels.yml
  .github/workflows/publish-container.yml
  .github/workflows/stale.yml
  .prettierrc.json
  .vscode/settings.json
  CHANGELOG.md
  demo/logger/index.ts
  demo/storage/index.ts
  dev-server.mjs
  package.json
  packages/core/nano-server/src/nano-server.ts
  packages/core/router/src/core.ts
  packages/core/signal/src/core.ts
  packages/core/signal/src/signal.ts
  packages/core/storage/CHANGELOG.md
  packages/core/storage/src/storage.ts
  packages/core/storage/src/type.ts
  packages/core/storage/src/util.ts
  packages/core/token/src/token.ts
  packages/nanoservice/storage/CHANGELOG.md
  packages/nanoservice/storage/package.json
  packages/starter/nanoservice/package.json
  yarn.lock
Labels: enhancement, dependencies

#290 refactor(nanoservice/storage): compatible with new storage
  packages/core/storage/src/provider.ts
  packages/nanoservice/storage/src/lib/storage-provider.ts
  packages/nanoservice/storage/src/route/get.ts
  packages/nanoservice/storage/src/route/update.ts
Labels: enhancement

#288 refactor(i18n): rewrite from scratch!
  packages/core/i18n/src/core.ts
  packages/core/i18n/src/i18n.ts
  packages/core/i18n/src/signal.ts
  packages/core/i18n/src/type.ts
Labels: enhancement, major, new-feature, breaking-change

#291 Feat/math
  demo/math/translate-unicode-digits.ts
  packages/core/math/README.md
  packages/core/math/src/math.ts
Labels: new-feature

#254 Improve documention
  .eslintignore
  .eslintrc.json
  .github/ISSUE_TEMPLATE/2-feature-request.yaml
  .github/ISSUE_TEMPLATE/config.yml
  packages/core/logger/README.md
  packages/core/logger/src/logger.ts
  packages/core/nano-server/src/nano-server.ts
  packages/core/storage/src/storage.ts
Labels: documentation

#299 Classic private docker registry
  packages/classic-cloud/distribution/README.md
  packages/classic-cloud/distribution/compose.yml
  packages/classic-cloud/distribution/deploy.sh
  packages/classic-cloud/distribution/env/example.env
  packages/classic-cloud/php-apache/php/Dockerfile
  packages/classic-cloud/traefik-proxy/compose.yml
  packages/classic-cloud/traefik-proxy/env/example.env
  packages/classic-cloud/wordpress/nginx/Dockerfile
  packages/container/alpine/Dockerfile
  packages/container/nginx/Dockerfile
Labels: priority-high, new-feature

#305 Fix(nginx): healthcheck, workdir, publish versions
  .github/workflows/publish-container.yml
  packages/container/nginx/Dockerfile
  packages/container/nginx/README.md
Labels: minor, bugfix
