Repository AliMD/alwatr, pull requests merged in 2023-07, with the labels that each got.

#1330 fix(demo-pwa): cache bug
  core/fract/src/lit-html.ts
  ui/demo-pwa/src/ui/app.ts
  ui/demo-pwa/src/ui/lit-debug.ts
  ui/demo-pwa/src/ui/page-test.ts
Labels: bugfix

#1331 feat(demo-pwa): add postcss and tailwind to esbuild, add tailwind color
  ui/demo-pwa/esbuild.mjs
  ui/demo-pwa/package.json
  ui/demo-pwa/res/index.html
  ui/demo-pwa/src/ui/app.css
  ui/demo-pwa/src/ui/app.ts
  ui/demo-pwa/src/ui/css/alwatr-pwa.css
  ui/demo-pwa/src/ui/css/base.css
  ui/demo-pwa/src/ui/css/palettes/h300.css
  ui/demo-pwa/src/ui/css/pwa.css
  ui/demo-pwa/src/ui/css/theme-colors-auto.css
  ui/demo-pwa/tailwind.config.js
  ui/demo-pwa/theme-colors.ts
  yarn.lock
Labels: new-feature

#1347 feat(fract): export `classMap`
  core/fract/src/lit-html.ts
Labels: new-feature

#1351 feat(style): add z-index, update colors, fix fontWeight
  .vscode/settings.json
  ui/demo-pwa/esbuild.mjs
  ui/demo-pwa/res/play.html
  ui/style/lib/colors.css
  ui/style/lib/colors.ts
  ui/style/lib/tailwind.ts
  ui/style/lib/typography.ts
  ui/style/lib/z-index.ts
Labels: enhancement, new-feature, bugfix

#1361 fix(workflow): increase nodejs memory usage in lint
  .github/workflows/build-lint.yaml
Labels: ci, performance

#1364 feat: update postcss-preset-env and browserlist
  ui/demo-pwa/esbuild.mjs
  ui/demo-pwa/package.json
  ui/style/lib/tailwind.ts
  uniquely/com-pwa/package.json
  uniquely/flight-finder-pwa/package.json
  uniquely/keep-pwa/package.json
  uniquely/soffit-pwa/package.json
Labels: enhancement

#1370 feat: Alwatr EPN
  .gitattributes
  cloud/labs/v2fly/compose.yml
  cloud/labs/v2fly/config/client-vmess-socks.json
  cloud/labs/v2fly/config/server-vmess-ws.json
  cloud/labs/v2fly/connect.sh
  cloud/labs/v2fly/env/edge.env
  cloud/labs/v2fly/env/example.env
  cloud/labs/v2fly/env/middle.env
  cloud/labs/v2fly/secret/vmess-edge.json
  cloud/labs/v2fly/secret/vmess-tcp-client.json
  cloud/labs/v2fly/secret/vmess-tcp-middle.json
  cloud/labs/v2fly/secret/vmess-ws-client.json
  cloud/labs/v2fly/secret/vmess-ws-middle.json
Labels: new-feature

#1385 chore(deps): upgrade
  .vscode/settings.json
  package.json
  yarn.lock
Labels: dependencies

#1386 feat(style): screen breakpoints, stateLayers, scrim
  ui/style/lib/screen.ts
  ui/style/lib/state-layer.ts
  ui/style/lib/tailwind.ts
  ui/style/lib/z-index.ts
Labels: new-feature

#1395 fix(wp): secure xmlrpc
  cloud/classic/wordpress/nginx/conf.d/secure.conf
Labels: bugfix
