Repository AliMD/alwatr, pull requests merged in 2023-05, with the labels that each got.

#1098 feat(crypto): rename package & demo
  core/crypto/CHANGELOG.md
  core/crypto/README.md
  core/crypto/package.json
  core/crypto/src/hash.ts
  core/crypto/src/index.ts
  core/crypto/src/token.ts
  core/crypto/src/type.ts
  core/crypto/src/user.ts
  core/crypto/tsconfig.json
  core/token/README.md
  demo/crypto/benchmark.ts
  demo/crypto/hash.ts
  demo/crypto/token.ts
  demo/crypto/user.ts
  demo/package.json
  demo/tsconfig.json
  tsconfig.json
  uniquely/com-api/package.json
  uniquely/com-api/src/lib/config.ts
  uniquely/com-api/src/lib/token.ts
  uniquely/com-api/tsconfig.json
Labels: new-feature, breaking-change

#1099 feat(crypto): make prefix for userId
  core/crypto/src/user.ts
Labels: new-feature

#1081 feat(com-pwa): new preview and fix reported issues
  .eslintrc.json
  core/util/src/client-id.ts
  demo/fetch/index.ts
  demo/fetch/node.ts
  demo/icon/index.ts
  demo/router/index.ts
  ui/pwa-helper/src/signal/sw-user-notify.ts
  uniquely/com-api/demo.http
  uniquely/com-pwa/src/content/home-page-fa.ts
  uniquely/com-pwa/src/content/l18e-fa.json
  uniquely/com-pwa/src/manager/context-provider/chat-storage.ts
  uniquely/com-pwa/src/manager/context-provider/order-storage.ts
  uniquely/com-pwa/src/manager/context-provider/sign-in.ts
  uniquely/com-pwa/src/manager/context-provider/user.ts
  uniquely/com-pwa/src/manager/controller/order.ts
  uniquely/com-pwa/src/manager/index.ts
  uniquely/com-pwa/src/manager/submit-order-command-handler.ts
  uniquely/com-pwa/src/ui/alwatr-pwa.ts
  uniquely/com-pwa/src/ui/page/order-list.ts
  uniquely/com-pwa/src/ui/page/order.ts
  uniquely/com-pwa/src/ui/page/sign-in.ts
  uniquely/com-pwa/src/ui/stuff/order-shipping-form.ts
  uniquely/com-pwa/src/ui/stuff/select-product.ts
Labels: new-feature

#1033 feat(i18n): date method for convert date to active locale
  core/i18n/src/core.ts
  core/i18n/src/index.ts
  demo/es-bench/date-locale.ts
Labels: new-feature

#1034 feat(com-pwa): order created date in status box
  uniquely/com-pwa/src/content/l18e-fa.json
  uniquely/com-pwa/src/ui/stuff/order-status-box.ts
Labels: new-feature

#1104 fix(com-pwa): reported issue and deploy canary and beta
  cloud/classic/com-pwa/compose.yml
  cloud/classic/com-pwa/env/soffit-order-beta.env
  cloud/classic/com-pwa/env/soffit-order-canary.env
  cloud/classic/com-pwa/env/soffit-order.env
  cloud/container/nginx-pwa/conf/entrypoint.d/30-envsubst-on-config-js.sh
  uniquely/com-api/src/index.ts
  uniquely/com-api/src/route/patch-user.ts
  uniquely/com-api/src/route/put-order.ts
  uniquely/com-pwa/src/manager/context-provider/order-storage.ts
  uniquely/com-pwa/src/manager/context-provider/price-storage.ts
  uniquely/com-pwa/src/manager/context-provider/product-storage.ts
  uniquely/com-pwa/src/manager/context-provider/sign-in.ts
  uniquely/com-pwa/src/ui/alwatr-pwa.ts
  uniquely/com-pwa/src/ui/page/order.ts
Labels: enhancement

#1112 feat(nginx): enhance and dynamic request limit rate
  cloud/classic/com-pwa/compose.yml
  cloud/classic/com-pwa/env/soffit-order-beta.env
  cloud/classic/com-pwa/env/soffit-order-canary.env
  cloud/classic/com-pwa/env/soffit-order.env
  cloud/container/nginx-pwa/Dockerfile
  cloud/container/nginx-storage/Dockerfile
  cloud/container/nginx/Dockerfile
  cloud/container/nginx/conf/templates/http.d/20-log.conf.template
  cloud/container/nginx/conf/templates/http.d/70-request-limit.conf.template
Labels: new-feature

#1113 fix(soffit-order): reported issues
  .gitattributes
  core/type/src/customer-order-management.ts
  core/validator/src/validator.ts
  ui/pwa-helper/src/config.ts
  uniquely/com-api/demo-user.http
  uniquely/com-pwa/res/config.js
  uniquely/com-pwa/res/index.html
  uniquely/com-pwa/src/config.ts
  uniquely/com-pwa/src/manager/controller/order.ts
  uniquely/com-pwa/src/ui/stuff/order-status-box.ts
Labels: bugfix

#1110 feat(cloud): mashin-ro wp
  cloud/classic/adminer/env/example.env
  cloud/classic/adminer/env/srv1.env
  cloud/classic/adminer/env/srv3.env
  cloud/classic/flight-finder/env/example.env
  cloud/classic/mariadb/env/alwatr-srv1.env
  cloud/classic/mariadb/env/alwatr-srv3.env
  cloud/classic/mariadb/env/alwatr.env
  cloud/classic/wordpress/env/mashin-ro.env
  cloud/classic/wordpress/php/php.conf.ini
  cloud/labs/wireguard/compose.yml
  cloud/labs/wireguard/deploy.sh
  cloud/labs/wireguard/env/example.env
  cloud/labs/wireguard/env/srv3.env
Labels: enhancement

#1120 feat(type): UserAuth and user.permissions
  core/type/src/customer-order-management.ts
  core/type/src/user.ts
Labels: new-feature

#1121 feat(fetch, nano-server): user/auth
  core/fetch/src/fetch.ts
  core/fetch/src/type.ts
  core/nano-server/src/nano-server.ts
Labels: new-feature

#1122 feat(storage-client, server): touch method
  core/storage-client/src/storage-client.ts
  core/storage-engine/src/storage-engine.ts
  services/storage-server/src/route/touch.ts
Labels: new-feature

#1123 feat(util): node read write json helper methods
  .eslintrc.json
  core/util/src/node/_logger.ts
  core/util/src/node/fs.ts
  core/util/src/node/index.ts
  demo/es-bench/node-exist.ts
Labels: new-feature

#1125 feat(logger): add `duration time` to logger time label
  core/logger/src/logger.ts
Labels: new-feature

#1124 feat(storage-engine): none blocking save storage
  core/storage-engine/package.json
  core/storage-engine/src/storage-engine.ts
  core/storage-engine/src/util.ts
  core/storage-engine/tsconfig.json
  demo/storage-engine/benchmark.ts
Labels: new-feature

#1128 feat(util/node): makeLinkForce
  core/util/src/node/fs.ts
Labels: new-feature

#1129 feat(storage-client/server): cacheApiResponse method
  core/storage-client/src/storage-client.ts
  services/storage-server/demo.http
  services/storage-server/package.json
  services/storage-server/src/index.ts
  services/storage-server/src/route/cache-api-response.ts
  services/storage-server/tsconfig.json
Labels: new-feature

#1130 feat(nginx): add NGINX_DISABLE_SYMLINKS env and fix rate issue
  cloud/container/nginx/Dockerfile
  cloud/container/nginx/conf/templates/http.d/70-request-limit.conf.template
  cloud/container/nginx/conf/templates/location.d/30-secure.conf.template
  ui/pwa-helper/package.json
Labels: new-feature, bugfix

#1131 feat(pwa-helper): add build short sha to alwatr version
  ui/pwa-helper/esbuild.mjs
  ui/pwa-helper/package.json
  ui/pwa-helper/src/signal/sw-user-notify.ts
Labels: new-feature

#1132 fix(workflow/pwa): add git to docker build
  .github/workflows/publish-special-container.yml
  cloud/classic/com-pwa/env/soffit-order-beta.env
  cloud/classic/com-pwa/env/soffit-order-canary.env
  cloud/classic/com-pwa/env/soffit-order.env
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx-pwa/Dockerfile
  cloud/container/nginx-storage/Dockerfile
Labels: bugfix

#1140 feat(wp): new sites
  cloud/classic/adminer/compose.yml
  cloud/classic/traefik-proxy/env/srv1.env
  cloud/classic/traefik-proxy/env/srv2.env
  cloud/classic/traefik-proxy/env/srv3.env
  cloud/classic/traefik-proxy/traefik.toml
  cloud/classic/wordpress/compose.yml
  cloud/classic/wordpress/env/baran-demo.env
  cloud/classic/wordpress/env/baran-www.env
  cloud/classic/wordpress/env/example.env
  cloud/classic/wordpress/env/mashin-ro.env
  cloud/classic/wordpress/env/mashin.env
  cloud/classic/wordpress/env/mdpedia-ar.env
  cloud/classic/wordpress/env/mdpedia-en.env
  cloud/classic/wordpress/env/mdpedia-fa.env
  cloud/classic/wordpress/nginx/nginx.conf
  cloud/classic/wordpress/php/fix-permition.sh
  cloud/classic/wordpress/php/php.conf.ini
Labels: new-feature

#1146 feat(nginx-storage): new strategy for private storage behind auth token
  cloud/container/nginx-storage/.dockerignore
  cloud/container/nginx-storage/Dockerfile
  cloud/container/nginx-storage/_404.json
  cloud/container/nginx-storage/_error.json
  cloud/container/nginx-storage/conf/location.d/10-error-page.conf.template
  cloud/container/nginx-storage/conf/location.d/40-json.conf.template
  cloud/container/nginx-storage/conf/location.d/90-json.conf.template
  cloud/container/nginx-storage/index.json
Labels: major, new-feature

#1147 chore(nginx): update version to 1.4.0
  .github/workflows/publish-alwatr-container.yml
  .github/workflows/publish-special-container.yml
  cloud/alwatr/soffit-order/env/soffit-order-beta.env
  cloud/alwatr/soffit-order/env/soffit-order-canary.env
  cloud/alwatr/soffit-order/env/soffit-order.env
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx-pwa/Dockerfile
  cloud/container/nginx-storage/Dockerfile
Labels: enhancement

#1149 refactor(fetch): use delay from util
  core/fetch/src/fetch.ts
  core/fetch/src/type.ts
  core/type/src/user.ts
Labels: enhancement, bugfix

#1150 chore: encrypt all http demo
  .gitattributes
  cloud/alwatr/flight-finder/env/example.env
  services/comment/demo.http
  services/form-registration/demo.http
  services/storage-server/demo.http
  services/telegram-notifier/demo.http
  uniquely/com-api/demo-data.http
  uniquely/com-api/demo.http
  uniquely/flight-finder-api/demo.http
Labels: enhancement

#1152 fix(cloud/deploy): rsync symlinks
  cloud/classic/lib/deploy.sh
Labels: bugfix

#1155 feat(crypto): add some pre config
  core/crypto/src/hash.ts
  core/crypto/src/index.ts
  core/crypto/src/pre-config.ts
  core/crypto/src/user.ts
  demo/crypto/rand.ts
  demo/crypto/user.ts
  uniquely/com-api/src/lib/config.ts
  uniquely/com-api/src/lib/crypto.ts
Labels: new-feature

#1151 fix: com-api v2 issues
  cloud/alwatr/soffit-order/compose.yml
  cloud/alwatr/soffit-order/env/soffit-order-canary.env
  core/storage-client/src/storage-client.ts
  uniquely/com-api/src/lib/config.ts
Labels: bugfix

#1157 feat(com-api): new user.token, prevent to save it in user-list storage
  core/type/src/user.ts
  uniquely/com-api/src/lib/patch-user.ts
  uniquely/com-api/src/root-user.ts
  uniquely/com-api/src/route/patch-user.ts
Labels: new-feature

#1158 fix(nginx-storage): secure auth paths with token
  cloud/container/nginx-storage/Dockerfile
  cloud/container/nginx-storage/conf/http.d/42-map-bearer-token.conf.template
  cloud/container/nginx-storage/conf/location.d/40-json.conf.template
Labels: bugfix

#1165 feat(nginx): add hub and vault folder
  cloud/container/nginx-storage/conf/location.d/40-json.conf.template
Labels: new-feature

#1174 fix(storage-client): remove some extra types
  core/storage-client/src/storage-client.ts
Labels: enhancement

#1175 feat(type): add `priceListName` to `ComUser`
  core/type/src/customer-order-management.ts
Labels: enhancement

#1176 fix(nginx): serve the content of symbolic links based on the last modified time of the original file
  .github/workflows/publish-special-container.yml
  cloud/alwatr/soffit-order/env/soffit-order-beta.env
  cloud/alwatr/soffit-order/env/soffit-order-canary.env
  cloud/alwatr/soffit-order/env/soffit-order.env
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx-pwa/Dockerfile
  cloud/container/nginx-storage/Dockerfile
  cloud/container/nginx/Dockerfile
  cloud/container/nginx/conf/templates/location.d/30-secure.conf.template
Labels: bugfix

#1177 feat(com-pwa): preload product images
  uniquely/com-pwa/src/manager/context-provider/price-storage.ts
  uniquely/com-pwa/src/manager/context-provider/product-storage.ts
Labels: enhancement, new-feature

#1111 feat(soffit-order): compatible with new api [and admin pages]
  core/type/src/customer-order-management.ts
  uniquely/com-pwa/src/config.ts
  uniquely/com-pwa/src/content/l18e-fa.json
  uniquely/com-pwa/src/manager/context-provider/chat-storage.ts
  uniquely/com-pwa/src/manager/context-provider/order-storage.ts
  uniquely/com-pwa/src/manager/context-provider/price-storage.ts
  uniquely/com-pwa/src/manager/context-provider/product-storage.ts
  uniquely/com-pwa/src/manager/context-provider/sign-in.ts
  uniquely/com-pwa/src/manager/context-provider/user-list-storage.ts
  uniquely/com-pwa/src/manager/context-provider/user.ts
  uniquely/com-pwa/src/manager/submit-order-command-handler.ts
  uniquely/com-pwa/src/ui/alwatr-pwa.ts
  uniquely/com-pwa/src/ui/page/order.ts
  uniquely/com-pwa/src/ui/page/sign-in.ts
  uniquely/com-pwa/src/ui/page/user-list.ts
  uniquely/com-pwa/src/ui/stuff/select-product.ts
  uniquely/com-pwa/src/ui/stuff/user-info-box.ts
  uniquely/soffit-pwa/res/image/sample-1.jpg
  uniquely/soffit-pwa/res/image/sample-2.jpg
  uniquely/soffit-pwa/res/image/sample-3.jpg
  uniquely/soffit-pwa/res/image/sample-4.jpg
Labels: new-feature

#1183 feat(soffit-order): dynamic lading and pallet calculate
  core/math/src/math.ts
  core/type/src/customer-order-management.ts
  uniquely/com-api/src/lib/patch-user.ts
  uniquely/com-pwa/src/config.ts
  uniquely/com-pwa/src/content/l18e-fa.json
  uniquely/com-pwa/src/manager/context-provider/user.ts
  uniquely/com-pwa/src/manager/controller/order.ts
  uniquely/com-pwa/src/ui/page/order.ts
  uniquely/com-pwa/src/ui/stuff/order-shipping-form.ts
  uniquely/com-pwa/src/ui/stuff/select-product.ts
Labels: enhancement

#1188 feat(nginx): refactor and optimize open_file_cache
  .github/workflows/publish-special-container.yml
  cloud/alwatr/soffit-order/env/soffit-order-beta.env
  cloud/alwatr/soffit-order/env/soffit-order-canary.env
  cloud/alwatr/soffit-order/env/soffit-order.env
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx-pwa/Dockerfile
  cloud/container/nginx-storage/Dockerfile
  cloud/container/nginx/Dockerfile
  cloud/container/nginx/conf/templates/http.d/60-performance.conf.template
Labels: new-feature, bugfix

#1190 refactor(storage-engine): emergency saving strategy
  core/storage-engine/src/storage-engine.ts
  core/util/src/node/fs.ts
Labels: enhancement, new-feature, bugfix

#1189 feat(com-api): admin user-list-inc-order route
  core/type/src/customer-order-management.ts
  uniquely/com-api/demo.http
  uniquely/com-api/src/index.ts
  uniquely/com-api/src/lib/user-order.ts
  uniquely/com-api/src/route/admin/user-list-inc-order.ts
  uniquely/com-api/src/route/put-order.ts
  uniquely/com-api/src/route/user-list.ts
Labels: new-feature

#1195 refactor(com-api)!: new user auth dir
  uniquely/com-api/src/lib/config.ts
  uniquely/com-api/src/lib/patch-user.ts
  uniquely/com-api/src/lib/storage.ts
  uniquely/com-api/src/lib/user-order.ts
Labels: enhancement, breaking-change

#1196 fix(storage-server/link): make dest folder if not exist
  services/storage-server/src/route/link.ts
Labels: bugfix

#1198 fix(storage-server): remove json extension
  services/storage-server/src/route/link.ts
  uniquely/com-api/src/lib/patch-user.ts
Labels: bugfix

#1200 fix(util/fs): makeLinkForce throw error
  core/util/src/node/fs.ts
Labels: bugfix

#1206 fix(com-pwa): admin back signal issue
  uniquely/com-pwa/src/ui/page/admin-order-list.ts
  uniquely/com-pwa/src/ui/page/admin-order.ts
  uniquely/com-pwa/src/ui/page/home.ts
  uniquely/com-pwa/src/ui/page/order-list.ts
Labels: bugfix
