Repository AliMD/alwatr, pull requests merged in 2023-09, with the labels that each got.

#1504 chore(yarn): upgrade
  yarn.lock
Labels: dependencies

#1474 feat(v2fly): add new server, export vmess link script
  cloud/classic/prepare-node/config/pazh-fl/ssh-auth
  cloud/classic/prepare-node/env/pazh-fl.env
  cloud/classic/v2fly/add-uuid.sh
  cloud/classic/v2fly/connect.sh
  cloud/classic/v2fly/env/dev-edge-fl.env
  cloud/classic/v2fly/env/dev-middle-mci2.env
  cloud/classic/v2fly/env/fl.env
  cloud/classic/v2fly/env/mci1.env
  cloud/classic/v2fly/env/pazh-edge-fl-1.env
  cloud/classic/v2fly/env/pazh-edge-fl-2.env
  cloud/classic/v2fly/env/pazh-edge-ir.env
  cloud/classic/v2fly/env/pazh-ir.env
  cloud/classic/v2fly/env/pazh-middle-1.env
  cloud/classic/v2fly/env/pazh-middle-2.env
  cloud/classic/v2fly/env/pazh-middle-3.env
  cloud/classic/v2fly/env/pazh-us.env
  cloud/classic/v2fly/export-vmess-url.sh
  cloud/classic/v2fly/secret/dev/vmess-client.json
  cloud/classic/v2fly/secret/dev/vmess-edge.json
  cloud/classic/v2fly/secret/dev/vmess-middle.json
  cloud/classic/v2fly/secret/pazh/c.json
  cloud/classic/v2fly/secret/pazh/ir.json
  cloud/classic/v2fly/secret/pazh/us.json
  cloud/classic/v2fly/secret/pazh/vmess-client-1.json
  cloud/classic/v2fly/secret/pazh/vmess-edge-fl-1.json
  cloud/classic/v2fly/secret/pazh/vmess-edge-fl-2.json
  cloud/classic/v2fly/secret/pazh/vmess-edge-ir.json
  cloud/classic/v2fly/secret/pazh/vmess-middle-1.json
  cloud/classic/v2fly/secret/pazh/vmess-middle-2.json
  cloud/classic/v2fly/secret/pazh/vmess-middle-3.json
Labels: new-feature

#1488 feat: move adminer
  cloud/classic/adminer/env/mci1.env
  cloud/classic/adminer/env/mci2.env
Labels: new-feature

#1410 feat(ui-kit2): review and rewrite
  .eslintrc.json
  ui/demo-pwa/src/share/app-navigation-context.ts
  ui/demo-pwa/src/ui/alwatr-pwa.ts
  ui/demo-pwa/web-dev-server.config.js
  ui/playground/button.html
  ui/playground/web-dev-server.config.js
  ui/pwa-helper/pwa-dev-server.config.js
  ui/ui-kit2/fab/extended-fab.ts
  ui/ui-kit2/fab/fab.ts
  ui/ui-kit2/icon-button/icon-button.ts
  ui/ui-kit2/icon/icon.css
  ui/ui-kit2/icon/icon.ts
  ui/ui-kit2/navigation-bar/navigation-bar.ts
  ui/ui-kit2/navigation-drawer/navigation-drawer.ts
  ui/ui-kit2/navigation-rail/navigation-rail.ts
  ui/ui-kit2/top-app-bar/center-top-app-bar.ts
  ui/ui-kit2/top-app-bar/large-top-app-bar.ts
  ui/ui-kit2/top-app-bar/medium-top-app-bar.ts
  ui/ui-kit2/top-app-bar/top-app-bar.ts
  uniquely/flight-finder-pwa/web-dev-server.config.js
  web-dev-server.config.js
Labels: new-feature

#1508 feat: switch to lerna-lite
  lerna.json
  package.json
  yarn.lock
Labels: dependencies

#1554 fix(logger): change localStorage debug key to `alwatrDebug`
  core/logger/README.md
  core/logger/src/logger.ts
Labels: enhancement

#1555 feat(util): browser-task
  core/util/src/browser-task.ts
Labels: new-feature

#1576 fix(v2fly): ws transport
  cloud/classic/v2fly/env/dev-edge-fl.env
  cloud/classic/v2fly/env/dev-middle-mci2.env
  cloud/classic/v2fly/secret/dev/vmess-client.json
  cloud/classic/v2fly/secret/dev/vmess-edge.json
  cloud/classic/v2fly/secret/dev/vmess-middle.json
Labels: new-feature, bugfix

#1581 feat(prepare-node): onix1
  cloud/classic/prepare-node/config/onix-digi/resolv.conf
  cloud/classic/prepare-node/config/onix1/resolv.conf
  cloud/classic/prepare-node/config/onix1/ssh-auth
  cloud/classic/prepare-node/env/onix-digi.env
  cloud/classic/prepare-node/env/onix1.env
Labels: enhancement
