Repository AliMD/alwatr, pull requests merged in 2023-06, with the labels that each got.

#1218 fix(pwa): build clean flag
  uniquely/com-pwa/package.json
  uniquely/soffit-pwa/package.json
Labels: bugfix

#1222 fix(es-bench): bench calc issue
  demo/es-bench/bench.ts
  demo/es-bench/index.html
  demo/es-bench/object-vs-map.ts
Labels: enhancement, bugfix

#1207 feat(signal2): add `signal2`
  cloud/alwatr/soffit-order/env/soffit-order.env
  core/signal2/README.md
  core/signal2/package.json
  core/signal2/src/base.ts
  core/signal2/src/context.ts
  core/signal2/src/event.ts
  core/signal2/src/index.ts
  core/signal2/src/multithread-context.ts
  core/signal2/src/simple-signal.ts
  core/signal2/src/type.ts
  core/signal2/tsconfig.json
  demo/es-bench/bench.ts
  demo/es-bench/compare.ts
  demo/index.html
  demo/signal2/multithread-context/index.html
  demo/signal2/multithread-context/index.ts
  demo/signal2/multithread-context/main.ts
  demo/signal2/multithread-context/share-context.ts
  demo/signal2/multithread-context/worker.ts
  demo/signal2/simple/index.html
  demo/signal2/simple/index.ts
  demo/tsconfig.json
  tsconfig.json
Labels: new-feature

#1197 feat(fsm2): rewrite from scratch.
  core/fsm2/CHANGELOG.md
  core/fsm2/README.md
  core/fsm2/package.json
  core/fsm2/src/base.ts
  core/fsm2/src/fsm.ts
  core/fsm2/src/index.ts
  core/fsm2/src/type.ts
  core/fsm2/tsconfig.json
  core/util/src/index.ts
  core/util/src/string.ts
  demo/finite-state-machine2/light-machine.ts
  demo/tsconfig.json
  tsconfig.json
Labels: new-feature

#1221 feat(com-pwa): bold text for count
  uniquely/com-pwa/src/ui/page/order.ts
Labels: enhancement

#1220 chore(ui-kit): publish css to npm
  ui/ui-kit/package.json
Labels: bugfix

#1208 feat(workflow): review and cleanup all CI/CD process
  .github/dependabot.yml
  .github/workflows/add-to-project.yml
  .github/workflows/build-lint.yaml
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/publish-alwatr-container.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-special-container.yml
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/alwatr-services.dockerfile
  services/telegram-notifier/Dockerfile
Labels: enhancement

#1232 refactor(signal): review everything and change all configs
  core/fsm2/src/base.ts
  core/fsm2/src/fsm.ts
  core/signal2/src/base.ts
  core/signal2/src/context.ts
  core/signal2/src/event.ts
  core/signal2/src/index.ts
  core/signal2/src/multithread-context.ts
  core/signal2/src/simple-signal.ts
  core/signal2/src/type.ts
  demo/finite-state-machine2/light-machine.ts
  demo/signal2/context/index.ts
  demo/signal2/multithread-context/main.ts
  demo/signal2/multithread-context/share-context.ts
  demo/signal2/simple/index.ts
Labels: enhancement

#1219 feat(server-context): server/api request base classes
  core/fsm2/src/fsm.ts
  core/server-context/CHANGELOG.md
  core/server-context/README.md
  core/server-context/package.json
  core/server-context/src/api-request.ts
  core/server-context/src/index.ts
  core/server-context/src/server-request.ts
  core/server-context/tsconfig.json
  demo/index.html
  demo/server-context/api-request.ts
  demo/server-context/index.html
  demo/server-context/server-request.ts
  tsconfig.json
  yarn.lock
Labels: new-feature

#1211 feat(com-pwa): sort user based last order
  uniquely/com-pwa/src/ui/page/admin-order-list.ts
  uniquely/com-pwa/src/ui/page/home.ts
  uniquely/com-pwa/src/ui/stuff/user-inc-order-box.ts
Labels: enhancement

#1243 chore(com-api): add new agency
  uniquely/com-api/demo.http
Labels: enhancement

#1245 bugfix(cloud): disable ALWATR_DEBUG in dockerfile
  cloud/container/alwatr-services.dockerfile
  services/telegram-notifier/Dockerfile
Labels: bugfix

#1261 feat(cloud): nocodb
  cloud/classic/nocodb/compose.yml
  cloud/classic/nocodb/deploy.sh
  cloud/classic/nocodb/env/srv1.env
Labels: new-feature

#1052 feat(keep): new PWA!
  .github/workflows/publish-alwatr-container.yml
  cloud/alwatr/keep/compose.yml
  cloud/alwatr/keep/deploy.sh
  cloud/alwatr/keep/env/keep-beta.env
  cloud/alwatr/keep/env/keep.env
  tsconfig.json
  ui/ui-kit/style/theme/palette-40.css
  uniquely/keep-pwa/README.md
  uniquely/keep-pwa/esbuild.mjs
  uniquely/keep-pwa/package.json
  uniquely/keep-pwa/res/config.js
  uniquely/keep-pwa/res/image/favicon.ico
  uniquely/keep-pwa/res/image/icon-192-maskable.png
  uniquely/keep-pwa/res/image/icon-192.png
  uniquely/keep-pwa/res/image/icon-512-maskable.png
  uniquely/keep-pwa/res/image/icon-512.png
  uniquely/keep-pwa/res/image/keep.svg
  uniquely/keep-pwa/res/index.html
  uniquely/keep-pwa/res/manifest.webmanifest
  uniquely/keep-pwa/res/robots.txt
  uniquely/keep-pwa/res/service-worker.js
  uniquely/keep-pwa/src/alwatr-pwa.ts
  uniquely/keep-pwa/src/config.ts
  uniquely/keep-pwa/src/content/home-page-en.ts
  uniquely/keep-pwa/src/content/home-page-fa.ts
  uniquely/keep-pwa/src/content/l18e-en.json
  uniquely/keep-pwa/src/content/l18e-fa.json
  uniquely/keep-pwa/src/manager/change-language.ts
  uniquely/keep-pwa/src/manager/context-provider/home-page-content.ts
  uniquely/keep-pwa/src/manager/context-provider/l18e.ts
  uniquely/keep-pwa/src/manager/context.ts
  uniquely/keep-pwa/src/manager/index.ts
  uniquely/keep-pwa/src/manager/logger.ts
  uniquely/keep-pwa/src/manager/submit-form-command-handler.ts
  uniquely/keep-pwa/src/type.ts
  uniquely/keep-pwa/src/ui/alwatr-pwa.ts
  uniquely/keep-pwa/src/ui/page/404.ts
  uniquely/keep-pwa/src/ui/page/home.ts
  uniquely/keep-pwa/src/ui/stuff/app-footer.ts
  uniquely/keep-pwa/src/ui/stuff/collaboration-box.ts
  uniquely/keep-pwa/src/ui/stuff/collaboration-form.ts
  uniquely/keep-pwa/tsconfig.json
  uniquely/keep-pwa/web-dev-server.config.js
Labels: new-feature

#1250 feat(router2): add `router2` class base
  core/router2/CHANGELOG.md
  core/router2/README.md
  core/router2/package.json
  core/router2/src/index.ts
  core/router2/src/router2.ts
  core/router2/src/type.ts
  core/router2/tsconfig.json
  core/util/src/_logger.ts
  core/util/src/index.ts
  core/util/src/render-state.ts
  demo/index.html
  demo/package.json
  demo/router2/index.html
  demo/router2/index.ts
  demo/tsconfig.json
  tsconfig.json
Labels: new-feature

#1269 feat(icon2): a lit directive to show the icons
  tsconfig.json
  ui/element/src/lit.ts
  ui/icon2/CHANGELOG.md
  ui/icon2/README.md
  ui/icon2/package.json
  ui/icon2/src/icon2.ts
  ui/icon2/tsconfig.json
  ui/pwa-helper/esbuild.mjs
Labels: new-feature

#1270 fix(es-bench): calc memory usages
  demo/es-bench/bench.ts
  demo/es-bench/import-tmp.ts
  demo/es-bench/import.ts
Labels: bugfix

#1271 feat(nocodb): use internal image
  .github/workflows/publish-special-container.yml
  cloud/classic/nocodb/compose.yml
  cloud/classic/nocodb/env/srv1.env
  cloud/container/nocodb/.dockerignore
  cloud/container/nocodb/Dockerfile
  cloud/container/nocodb/README.md
Labels: new-feature

#1272 bugfix(cloud): clone all image from ghcr
  .github/workflows/publish-special-container.yml
  cloud/classic/php-apache/php/Dockerfile
  cloud/classic/traefik-proxy/compose.yml
  cloud/classic/wordpress/nginx/Dockerfile
  cloud/classic/wordpress/php/Dockerfile
  cloud/container/adminer/README.md
  cloud/container/mariadb/README.md
  cloud/container/nginx/Dockerfile
  cloud/container/nocodb/README.md
  cloud/container/php/Dockerfile
  cloud/container/php/README.md
  cloud/container/traefik/README.md
  cloud/container/wordpress/README.md
  cloud/container/wordpress/php7.4/Dockerfile
  cloud/container/wordpress/php8.1/Dockerfile
Labels: enhancement, bugfix

#1238 feat(server-context): AlwatrServerContext & dynamic extra state/event type
  core/server-context/src/api-request.ts
  core/server-context/src/index.ts
  core/server-context/src/server-context.ts
  core/server-context/src/server-request.ts
  demo/server-context/server-context.ts
Labels: new-feature

#1281 hotfix: esbuild
  services/comment/package.json
  services/flight-crawler/package.json
  services/form-registration/package.json
  services/storage-server/package.json
  services/telegram-notifier/package.json
  ui/demo-pwa/package.json
  uniquely/com-api/package.json
  uniquely/com-pwa/package.json
  uniquely/flight-finder-api/package.json
  uniquely/keep-pwa/package.json
  uniquely/soffit-pwa/package.json
  yarn.lock
Labels: minor, bugfix

#1282 feat(fract): elegant simple render strategy powered by lit written in tiny TypeScript module for who hate react!
  .vscode/settings.json
  core/fract/README.md
  core/fract/package.json
  core/fract/src/directive.ts
  core/fract/src/dynamic-directive.ts
  core/fract/src/index.ts
  core/fract/src/lit.ts
  core/fract/tsconfig.json
  tsconfig.json
  ui/icon2/src/icon2.ts
  ui/icon2/tsconfig.json
Labels: new-feature

#1283 bugfix(cloud): change wordpress version
  .github/workflows/publish-special-container.yml
  cloud/container/wordpress/php7.4/Dockerfile
Labels: bugfix

#1284 feat(fract): map, mapObject, export more
  core/fract/src/directive.ts
  core/fract/src/dynamic-directive.ts
  core/fract/src/index.ts
  core/fract/src/lit-html.ts
  core/fract/src/lit.ts
  core/fract/src/map.ts
Labels: new-feature

#1285 feat(fract): AlwatrObserveDirective
  core/fract/package.json
  core/fract/src/directives/map.ts
  core/fract/src/directives/observe.ts
  core/fract/src/index.ts
  core/fract/src/lit-html.ts
  core/fract/tsconfig.json
Labels: new-feature

#1287 feat(logger): add logModule
  core/logger/src/logger.ts
  core/logger/src/type.ts
Labels: new-feature

#1288 feat(util): defaultExport
  core/util/src/default-export.ts
  core/util/src/index.ts
Labels: new-feature

#1290 feat(ui-kit): navigation-bar and icon2
  ui/ui-kit/package.json
  ui/ui-kit/src/navigation-bar/context.ts
  ui/ui-kit/src/navigation-bar/navigation-bar.ts
  ui/ui-kit/tsconfig.json
Labels: new-feature

#1293 feat(icon2): flip icon in rtl
  ui/icon/package.json
  ui/ui-kit/src/icon/icon.scss
  ui/ui-kit/src/icon/icon.ts
Labels: new-feature

#1292 fix(signal2): handle promise catch
  core/signal2/src/observable.ts
Labels: bugfix

#1294 feat(ui-kit): new alwatrNavigationBar and alwatrTopAppBar ui directive
  ui/ui-kit/icon/icon.scss
  ui/ui-kit/navigation-bar2/navigation-bar.scss
  ui/ui-kit/package.json
  ui/ui-kit/src/navigation-bar/context.ts
  ui/ui-kit/src/navigation-bar/navigation-bar.ts
  ui/ui-kit/src/navigation-bar2/navigation-bar.scss
  ui/ui-kit/src/navigation-bar2/navigation-bar.ts
  ui/ui-kit/src/navigation-bar2/type.ts
  ui/ui-kit/src/top-app-bar2/top-app-bar.scss
  ui/ui-kit/src/top-app-bar2/top-app-bar.ts
  ui/ui-kit/src/top-app-bar2/type.ts
  ui/ui-kit/top-app-bar2/top-app-bar.scss
Labels: new-feature

#1291 feat(pwa-helper/esbuild): support scss files
  ui/pwa-helper/esbuild.mjs
Labels: bugfix

#1295 chore(tsc): compile to ES2020
  tsconfig.base.json
Labels: new-feature

#1296 fix(router): build issue
  core/router2/src/router2.ts
Labels: bugfix

#1297 feat(pwa-demo2): new simple pwa demo with alwatr2 🎉
  ui/demo-pwa/old/alwatr-pwa.ts
  ui/demo-pwa/old/page-card.ts
  ui/demo-pwa/old/page-chat.ts
  ui/demo-pwa/package.json
  ui/demo-pwa/res/index.html
  ui/demo-pwa/res/manifest.webmanifest
  ui/demo-pwa/src/alwatr-pwa.ts
  ui/demo-pwa/src/config.ts
  ui/demo-pwa/src/icons.ts
  ui/demo-pwa/src/share/logger.ts
  ui/demo-pwa/src/ui/app.scss
  ui/demo-pwa/src/ui/app.ts
  ui/demo-pwa/src/ui/root-element.ts
  ui/demo-pwa/tsconfig.json
  yarn.lock
Labels: new-feature

#1212 chore: alwatr ascii arts
  logo.md
Labels: documentation, good first issue
