Repository AliMD/alwatr, pull requests merged in 2023-08, with the labels that each got.

#1398 feat(fract): export `when`
  core/fract/src/lit-html.ts
Labels: enhancement

#1397 lint(eslint): disable lit/attribute-value-entities rule
  .eslintrc.json
Labels: enhancement

#1396 feat(playground): add navigation rail to app
  ui/playground/app.html
  ui/playground/index.html
  ui/playground/navigation-rail.html
Labels: enhancement

#1399 feat(demo-pwa): move app from playground
  ui/demo-pwa/src/icons.ts
  ui/demo-pwa/src/ui/alwatr-pwa.ts
Labels: new-feature

#1387 feat(ui-kit2): app navigations and top-app-bar directive and context
  ui/demo-pwa/res/index.html
  ui/demo-pwa/src/share/app-navigation-context.ts
  ui/demo-pwa/src/ui/alwatr-pwa.ts
  ui/ui-kit2/drawer/drawer.ts
  ui/ui-kit2/icon-button/icon-button.ts
  ui/ui-kit2/navigation-bar/navigation-bar.ts
  ui/ui-kit2/navigation-drawer/navigation-drawer.ts
  ui/ui-kit2/navigation-rail/navigation-rail.ts
  ui/ui-kit2/top-app-bar/top-app-bar.ts
Labels: new-feature

#1403 feat(ui-kit2): add fab & extended fab directive
  ui/playground/index.html
  ui/ui-kit2/fab/extended-fab.ts
  ui/ui-kit2/fab/fab.ts
Labels: new-feature

#1442 feat(prepare-node): srv4 resolve
  cloud/classic/prepare-node/config/onix-digi/resolv.conf
Labels: new-feature

#1448 fix(cloud/prepare): deploy script issues
  cloud/classic/lib/deploy.sh
  cloud/classic/prepare-node/config/mci1/resolv.conf
  cloud/classic/prepare-node/deploy.sh
  cloud/classic/prepare-node/env/mci1.env
Labels: bugfix

#1449 feat(cloud): update scripts and migrate servers
  .github/workflows/publish-special-container.yml
  cloud/classic/lib/deploy.sh
  cloud/classic/prepare-node/config/fl/resolv.conf
  cloud/classic/prepare-node/env/fl.env
  cloud/classic/prepare-node/env/srv1.env
  cloud/classic/prepare-node/env/srv3.env
  cloud/classic/traefik-proxy/env/fl.env
  cloud/classic/traefik-proxy/env/mci1.env
  cloud/classic/traefik-proxy/env/srv1.env
  cloud/classic/traefik-proxy/env/srv3.env
  cloud/classic/v2fly/compose.yml
  cloud/classic/v2fly/connect.sh
  cloud/classic/v2fly/deploy.sh
  cloud/classic/v2fly/env/fl.env
  cloud/classic/v2fly/env/mci1.env
  cloud/classic/v2fly/env/pazh-ir.env
  cloud/classic/v2fly/env/pazh-us.env
  cloud/classic/v2fly/secret/dev/vmess-client.json
  cloud/classic/v2fly/secret/dev/vmess-edge.json
  cloud/classic/v2fly/secret/dev/vmess-middle.json
  cloud/classic/v2fly/secret/pazh/c.json
  cloud/classic/v2fly/secret/pazh/ir.json
  cloud/classic/v2fly/secret/pazh/us.json
  cloud/labs/v2fly/env/alwatr-fl.env
  cloud/labs/v2fly/env/alwatr-ir.env
  cloud/labs/v2fly/env/pazh-ir.env
  cloud/labs/v2fly/env/pazh-us.env
  cloud/labs/v2fly/secret/dev/vmess-edge.json
  cloud/labs/v2fly/secret/dev/vmess-tcp-client.json
  cloud/labs/v2fly/secret/dev/vmess-tcp-middle.json
  cloud/labs/v2fly/secret/dev/vmess-ws-client.json
  cloud/labs/v2fly/secret/dev/vmess-ws-middle.json
  cloud/labs/v2fly/secret/pazh/c.json
  cloud/labs/v2fly/secret/pazh/ir.json
  cloud/labs/v2fly/secret/pazh/us.json
Labels: enhancement

#1450 feat(cloud/deploy): move service to another server
  .gitattributes
  cloud/alwatr/keep/env/keep-beta.env
  cloud/alwatr/keep/env/keep.env
  cloud/alwatr/soffit-order/env/soffit-order-beta.env
  cloud/alwatr/soffit-order/env/soffit-order-canary.env
  cloud/alwatr/soffit-order/env/soffit-order.env
  cloud/alwatr/soffit-ws/env/soffit-beta.env
  cloud/alwatr/soffit-ws/env/soffit.env
  cloud/classic/adminer/env/mci1.env
  cloud/classic/adminer/env/srv3.env
  cloud/classic/lib/common.sh
  cloud/classic/lib/deploy.sh
  cloud/classic/mariadb/env/alwatr-srv3.env
  cloud/classic/mariadb/env/baran-fl.env
  cloud/classic/mariadb/env/baran-ir.env
  cloud/classic/mariadb/env/baran.env
  cloud/classic/mariadb/env/mci1.env
  cloud/classic/prepare-node/config/pazh-ir/ssh-auth
  cloud/classic/prepare-node/config/pazh-us/ssh-auth
  cloud/classic/prepare-node/config/ssh-auth
  cloud/classic/prepare-node/config/ssh-banner
  cloud/classic/prepare-node/config/ssh-config
  cloud/classic/prepare-node/config/ssh-rsa
  cloud/classic/prepare-node/config/ssh-rsa.pub
  cloud/classic/prepare-node/deploy.sh
  cloud/classic/wordpress/env/baran-demo.env
  cloud/classic/wordpress/env/baran-www.env
  cloud/classic/wordpress/env/mashin.env
  cloud/classic/wordpress/env/mdpedia-ar.env
  cloud/classic/wordpress/env/mdpedia-en.env
  cloud/classic/wordpress/env/mdpedia-fa.env
  cloud/classic/wordpress/env/ympedia-intro.env
  cloud/classic/wordpress/nginx/Dockerfile
  cloud/classic/wordpress/php/Dockerfile
Labels: enhancement

#1453 feat(cloud): enhance php fix-permission
  cloud/classic/mariadb/env/baran-fl.env
  cloud/classic/mariadb/env/baran-ir.env
  cloud/classic/mariadb/env/baran.env
  cloud/classic/php-apache/_up.sh
  cloud/classic/php-apache/php/.dockerignore
  cloud/classic/php-apache/php/Dockerfile
  cloud/classic/php-apache/php/fix-permission.sh
  cloud/classic/wordpress/_up.sh
  cloud/classic/wordpress/php/.dockerignore
  cloud/classic/wordpress/php/Dockerfile
  cloud/classic/wordpress/php/fix-permission.sh
Labels: new-feature

#1454 chore(cloud): clean old static file service
  cloud/classic/static-file/README.md
  cloud/classic/static-file/compose.yml
  cloud/classic/static-file/deploy.sh
  cloud/classic/static-file/env/example.env
  cloud/classic/static-file/nginx
Labels: bugfix

#1455 feat: upgrade nginx 1.8.0-1.25-alpine
  .github/workflows/publish-special-container.yml
  cloud/alwatr/keep/env/keep-beta.env
  cloud/alwatr/keep/env/keep.env
  cloud/alwatr/soffit-order/env/soffit-order-beta.env
  cloud/alwatr/soffit-order/env/soffit-order-canary.env
  cloud/alwatr/soffit-order/env/soffit-order.env
  cloud/classic/wordpress/env/baran-demo.env
  cloud/classic/wordpress/env/baran-www.env
  cloud/classic/wordpress/env/example.env
  cloud/classic/wordpress/env/ympedia-intro.env
  cloud/classic/wordpress/nginx/Dockerfile
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx-pwa/Dockerfile
  cloud/container/nginx-storage/Dockerfile
  cloud/container/nginx/Dockerfile
Labels: new-feature

#1456 feat(nginx): customizable error page
  cloud/container/nginx/conf/templates/location.d/10-error-page.conf.template
Labels: new-feature

#1393 feat(cloud): add cdn deployment
  .github/workflows/publish-special-container.yml
  cloud/classic/static-site/compose.yml
  cloud/classic/static-site/deploy.sh
  cloud/classic/static-site/env/ssc-test.env
  cloud/container/nginx-ws/.dockerignore
  cloud/container/nginx-ws/Dockerfile
  cloud/container/nginx-ws/README.md
  cloud/container/nginx-ws/conf/templates/location.d/90-ws.conf.template
Labels: new-feature

#1452 feat:‌ final move server
  cloud/alwatr/flight-finder/env/counterme.env
  cloud/alwatr/keep/env/keep-beta.env
  cloud/alwatr/keep/env/keep.env
  cloud/alwatr/soffit-order/env/soffit-order-beta.env
  cloud/alwatr/soffit-order/env/soffit-order-canary.env
  cloud/alwatr/soffit-order/env/soffit-order.env
  cloud/alwatr/soffit-ws/env/soffit-beta.env
  cloud/alwatr/soffit-ws/env/soffit.env
  cloud/classic/mariadb/env/alwatr-fl.env
  cloud/classic/mariadb/env/alwatr-srv1.env
  cloud/classic/mariadb/env/example.env
  cloud/classic/nocodb/env/alwatr-table.env
  cloud/classic/nocodb/env/srv3.env
  cloud/classic/prepare-node/env/srv4.env
Labels: enhancement

#1460 feat(nginx): force domain
  .github/workflows/publish-special-container.yml
  cloud/alwatr/keep/env/keep-beta.env
  cloud/alwatr/keep/env/keep.env
  cloud/alwatr/soffit-order/env/soffit-order-beta.env
  cloud/alwatr/soffit-order/env/soffit-order-canary.env
  cloud/alwatr/soffit-order/env/soffit-order.env
  cloud/classic/static-site/env/ssc-test.env
  cloud/classic/wordpress/env/baran-demo.env
  cloud/classic/wordpress/env/baran-www.env
  cloud/classic/wordpress/env/example.env
  cloud/classic/wordpress/env/ympedia-intro.env
  cloud/classic/wordpress/nginx/Dockerfile
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx-pwa/Dockerfile
  cloud/container/nginx-storage/Dockerfile
  cloud/container/nginx-ws/Dockerfile
  cloud/container/nginx/Dockerfile
  cloud/container/nginx/conf/entrypoint.d/10-envsubst-on-templates.sh
  cloud/container/nginx/conf/entrypoint.d/20-tune-worker-processes.sh
  cloud/container/nginx/conf/entrypoint.d/30-cleanup-conf.sh
  cloud/container/nginx/conf/entrypoint.sh
  cloud/container/nginx/conf/templates/location.d/40-force-domain.conf.template
Labels: new-feature

#1465 fix: rsync and ssh key permission
  cloud/classic/lib/deploy.sh
  cloud/classic/prepare-node/deploy.sh
Labels: enhancement

#1467 fix(nginx): entrypoints permission
  cloud/container/nginx/Dockerfile
  cloud/container/nginx/conf/entrypoint.d/30-cleanup-conf.sh
Labels: bugfix

#1468 chore: nginx 1.9.2-1.25-alpine
  .github/workflows/publish-special-container.yml
  cloud/alwatr/keep/env/keep-beta.env
  cloud/alwatr/keep/env/keep.env
  cloud/alwatr/soffit-order/env/soffit-order-beta.env
  cloud/alwatr/soffit-order/env/soffit-order-canary.env
  cloud/alwatr/soffit-order/env/soffit-order.env
  cloud/classic/static-site/env/ssc-test.env
  cloud/classic/wordpress/env/baran-demo.env
  cloud/classic/wordpress/env/baran-www.env
  cloud/classic/wordpress/env/example.env
  cloud/classic/wordpress/env/ympedia-intro.env
  cloud/classic/wordpress/nginx/Dockerfile
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx-pwa/Dockerfile
  cloud/container/nginx-storage/Dockerfile
  cloud/container/nginx-ws/Dockerfile
Labels: bugfix

#1470 chore(cloud): move server
  cloud/alwatr/soffit-order/env/soffit-order-beta.env
  cloud/alwatr/soffit-order/env/soffit-order-canary.env
  cloud/alwatr/soffit-order/env/soffit-order.env
  cloud/alwatr/soffit-ws/env/soffit-beta.env
  cloud/alwatr/soffit-ws/env/soffit.env
  cloud/classic/nocodb/env/alwatr-table.env
Labels: enhancement
