Repository AliMD/alwatr, pull requests merged in 2023-04, with the labels that each got.

#983 feat(com): cdn
  cloud/classic/com-pwa/compose.yml
  cloud/classic/com-pwa/env/order.soffit.co.env
  uniquely/com-api/demo-data.http
  uniquely/com-pwa/res/config.js
  uniquely/com-pwa/src/ui/stuff/order-detail-base.ts
  uniquely/com-pwa/src/ui/stuff/select-product.ts
Labels: new-feature

#978 feat(button): use content property and move to manager
  ui/ui-kit/src/button/button.ts
  ui/ui-kit/src/button/icon-button.ts
  ui/ui-kit/src/snackbar/element.ts
  uniquely/com-pwa/src/manager/buttons.ts
  uniquely/com-pwa/src/ui/page/new-order.ts
  uniquely/com-pwa/src/ui/page/order-detail.ts
  uniquely/com-pwa/src/ui/page/order-list.ts
  uniquely/soffit-pwa/src/ui/stuff/lottery-form.ts
Labels: enhancement, performance

#993 feat(cloud/com): add chat service
  cloud/classic/com-pwa/compose.yml
  cloud/classic/com-pwa/env/order.soffit.co.env
Labels: new-feature

#994 feat(com-pwa): chat storage context provider
  uniquely/com-pwa/src/manager/context-provider/chat-storage.ts
  uniquely/com-pwa/src/manager/index.ts
Labels: new-feature

#1008 chore: pwa version
  ui/pwa-helper/package.json
  uniquely/com-pwa/src/manager/controller/new-order.ts
Labels: enhancement

#1009 fix(ui/text-field): set empty string for undefined value
  ui/ui-kit/src/text-field/text-field.ts
  uniquely/com-pwa/src/ui/page/order-detail.ts
Labels: bugfix

#1016 feat(com-pwa): change order_shipping_car i18n key
  core/type/src/customer-order-management.ts
  uniquely/com-pwa/src/content/l18e-fa.json
Labels: enhancement

#1010 feat(nano-server): prefix pattern
  core/nano-server/src/nano-server.ts
  core/nano-server/src/type.ts
Labels: new-feature

#1018 fix(nano-server): prefixPattern, logger
  core/nano-server/src/nano-server.ts
  core/nano-server/src/type.ts
Labels: enhancement, bugfix

#867 feat(ui/icon): svg property
  demo/icon/index.ts
  ui/icon/src/icon.ts
Labels: enhancement, new-feature

#1019 fix(cloud): exclude deploy backup
  cloud/classic/lib/deploy.sh
  cloud/classic/wordpress/env/baran-demo.env
  cloud/classic/wordpress/env/baran-www.env
  cloud/classic/wordpress/env/baran.env
Labels: bugfix

#1021 docs(fsm): docs methods
  core/fsm/src/core.ts
  core/fsm/src/index.ts
Labels: documentation

#1045 fix(fetch): compatible with node
  core/fetch/src/fetch.ts
Labels: bugfix

#1049 fix(telegram-notifier): escaping send message
  services/telegram-notifier/src/bot/send-message.ts
Labels: bugfix

#1050 feat(com-pwa): review, refactor, release v1
  .vscode/settings.json
  core/fetch/src/fetch.ts
  core/fsm/src/core.ts
  core/router/src/core.ts
  ui/pwa-helper/src/pwa-element.ts
  uniquely/com-pwa/res/config.js
  uniquely/com-pwa/src/content/home-page-fa.ts
  uniquely/com-pwa/src/content/l18e-fa.json
  uniquely/com-pwa/src/manager/buttons.ts
  uniquely/com-pwa/src/manager/context-provider/order-storage.ts
  uniquely/com-pwa/src/manager/controller/order-detail.ts
  uniquely/com-pwa/src/manager/controller/order.ts
  uniquely/com-pwa/src/manager/index.ts
  uniquely/com-pwa/src/manager/submit-order-command-handler.ts
  uniquely/com-pwa/src/ui/alwatr-pwa.ts
  uniquely/com-pwa/src/ui/page/404.ts
  uniquely/com-pwa/src/ui/page/new-order.ts
  uniquely/com-pwa/src/ui/page/order-list.ts
  uniquely/com-pwa/src/ui/page/order.ts
  uniquely/com-pwa/src/ui/stuff/order-detail-base.ts
Labels: new-feature

#1057 feat(nginx): optimize pwa spa serve
  .github/workflows/publish-special-container.yml
  cloud/classic/com-pwa/env/soffit-com.env
  cloud/classic/static-file/compose.yml
  cloud/classic/static-file/env/example.env
  cloud/classic/wordpress/compose.yml
  cloud/classic/wordpress/env/baran-demo.env
  cloud/classic/wordpress/env/baran-www.env
  cloud/classic/wordpress/env/example.env
  cloud/classic/wordpress/env/mashin-ro.env
  cloud/classic/wordpress/nginx/Dockerfile
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx/Dockerfile
  cloud/container/nginx/conf/templates/location.d/50-pwa.template
Labels: new-feature

#1064 feat(nginx): optimize base for cdn and enhance performance
  .github/workflows/publish-alwatr-container.yml
  .github/workflows/publish-special-container.yml
  cloud/container/alpine/Dockerfile
  cloud/container/nginx/Dockerfile
  cloud/container/nginx/README.md
  cloud/container/nginx/conf/templates/http.d/00-main.conf.template
  cloud/container/nginx/conf/templates/http.d/60-performance.conf.template
  cloud/container/nginx/conf/templates/location.d/20-server-info.conf.template
  cloud/container/nginx/conf/templates/location.d/30-secure.conf.template
  cloud/container/nginx/conf/templates/location.d/31-secure-wp.conf.skiped
  cloud/container/nginx/conf/templates/location.d/50-pwa.conf.template
Labels: new-feature, performance

#1065 feat(nginx-pwa): new nginx container, optimized for pwa
  .github/workflows/publish-special-container.yml
  .vscode/settings.json
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx-pwa/.dockerignore
  cloud/container/nginx-pwa/Dockerfile
  cloud/container/nginx-pwa/README.md
  cloud/container/nginx-pwa/conf/location.d/90-pwa.conf.template
  cloud/container/tdlib/Dockerfile
Labels: new-feature

#1076 feat(container/nginx-storage): error.json for error
  cloud/container/nginx-storage/.dockerignore
  cloud/container/nginx-storage/Dockerfile
  cloud/container/nginx-storage/_error.json
  cloud/container/nginx-storage/conf/location.d/10-error-page.conf.template
Labels: new-feature

#1060 feat(com-pwa): new sign-in page and auth process
  core/type/src/customer-order-management.ts
  core/type/src/user.ts
  ui/element/src/lit.ts
  ui/pwa-helper/src/pwa-element.ts
  ui/ui-kit/src/button/button.ts
  ui/ui-kit/src/card/surface.ts
  ui/ui-kit/src/text-field/text-field.ts
  uniquely/com-pwa/res/config.js
  uniquely/com-pwa/src/content/l18e-fa.json
  uniquely/com-pwa/src/manager/buttons.ts
  uniquely/com-pwa/src/manager/context-provider/user.ts
  uniquely/com-pwa/src/ui/alwatr-pwa.ts
  uniquely/com-pwa/src/ui/page/order-list.ts
  uniquely/com-pwa/src/ui/page/order.ts
  uniquely/com-pwa/src/ui/page/sign-in.ts
  uniquely/com-pwa/src/ui/stuff/select-product.ts
Labels: new-feature

#1035 feat(com-api): update price list
  uniquely/com-api/demo-data.http
Labels: new-feature

#1078 fix(nginx): NGINX_ACCESS_LOG default value
  .github/workflows/publish-special-container.yml
  cloud/classic/com-pwa/env/soffit-com.env
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx-pwa/Dockerfile
  cloud/container/nginx-storage/Dockerfile
  cloud/container/nginx/Dockerfile
Labels: bugfix

#1079 fix(nginx-storage): ssi syntax error
  .github/workflows/publish-special-container.yml
  cloud/classic/com-pwa/env/soffit-com.env
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx-pwa/Dockerfile
  cloud/container/nginx-storage/Dockerfile
  cloud/container/nginx-storage/_error.json
Labels: bugfix

#1080 fix(nginx-storage): ssi types
  cloud/container/nginx-storage/conf/location.d/10-error-page.conf.template
Labels: bugfix

#1086 feat(validator): sanitizePhoneNumber
  core/validator/src/validator.ts
  demo/es-bench/reg-cost.ts
  demo/index.html
  demo/validator/index.html
  demo/validator/phone.ts
Labels: new-feature

#1085 chore(com-api): add new product
  uniquely/com-api/demo-data.http
Labels: new-feature

#1092 feat(util): setLocalStorageItem
  core/util/src/local-storage.ts
Labels: new-feature

#1097 feat(type/user): add `lpe`
  core/type/src/user.ts
Labels: new-feature

#1096 feat(crypto): self validate hash and user factory
  core/token/package.json
  core/token/src/hash.ts
  core/token/src/index.ts
  core/token/src/token.ts
  core/token/src/type.ts
  core/token/src/user.ts
  core/token/tsconfig.json
  demo/token/benchmark.ts
  demo/token/hash.ts
  demo/token/token.ts
Labels: new-feature
