Repository AliMD/alwatr, pull requests merged in 2023-01, with the labels that each got.

#534 feat: validator
  core/validator/README.md
  core/validator/package.json
  core/validator/src/type.ts
  core/validator/src/validator.ts
  core/validator/tsconfig.json
  demo/package.json
  demo/tsconfig.json
  demo/validator/validator.ts
  tsconfig.json
  yarn.lock
Labels: new-feature

#613 refactor(ff-*): move job types to @alwatr/type
  core/type/src/flight-finder.ts
  services/flight-crawler/src/crawl.ts
  services/flight-crawler/src/lib/storage.ts
  services/flight-crawler/src/lib/type.ts
  uniquely/flight-finder-api/src/lib/storage.ts
  uniquely/flight-finder-api/src/route/job/put.ts
  uniquely/flight-finder-pwa/src/component/job-item.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
  uniquely/flight-finder-pwa/src/director/job-add.ts
  uniquely/flight-finder-pwa/src/director/job-document-storage.ts
  uniquely/flight-finder-pwa/src/type.ts
Labels: enhancement, minor

#608 feat(ui/style): layout system
  ui/demo-pwa/src/page-chat.ts
  ui/demo-pwa/style/helper/colors.css
  ui/demo-pwa/style/helper/elevation.css
  ui/demo-pwa/style/helper/motion.css
  ui/demo-pwa/style/helper/shape.css
  ui/demo-pwa/style/helper/state.css
  ui/demo-pwa/style/helper/typography.css
  ui/demo-pwa/style/mdc-grid-temp.css
  ui/demo-pwa/style/root.css
  ui/demo-pwa/style/tokens/elevation.css
  ui/demo-pwa/style/tokens/motion.css
  ui/demo-pwa/style/tokens/palette.css
  ui/demo-pwa/style/tokens/scrollbar.css
  ui/demo-pwa/style/tokens/shape.css
  ui/demo-pwa/style/tokens/spacing.css
  ui/demo-pwa/style/tokens/state.css
  ui/demo-pwa/style/tokens/typography.css
  ui/demo-pwa/style/tokens/z-index.css
  ui/font/sahel.css
  ui/font/vazirmatn-roundot.css
  ui/font/vazirmatn.css
  ui/ui-kit/src/chat/chat-avatar.ts
  ui/ui-kit/src/chat/chat-bubble.ts
  ui/ui-kit/src/chat/chat-footer.ts
  ui/ui-kit/src/chat/chat-list.ts
  ui/ui-kit/src/chat/chat-message.ts
  ui/ui-kit/src/chat/chat-text-input.ts
  ui/ui-kit/src/chat/chat.ts
  ui/ui-kit/src/elavation/style.ts
  ui/ui-kit/src/icon-button/standard-icon-button.ts
Labels: new-feature

#621 feat(type): new types
  core/i18n/package.json
  core/i18n/src/i18n.ts
  core/i18n/src/type.ts
  core/i18n/tsconfig.json
  core/type/src/customer-order-management.ts
  core/type/src/i18n.ts
  core/type/src/index.ts
  core/type/src/photo.ts
  core/type/src/storage.ts
  core/type/src/user.ts
Labels: enhancement

#628 feat(token): generate and verify token without expiration time
  core/token/src/token.ts
  core/token/src/type.ts
Labels: new-feature

#639 refactor(ui): color system
  ui/demo-pwa/color.html
  ui/demo-pwa/style/helper/demo.css
  ui/demo-pwa/style/tokens/palette.css
Labels: enhancement

#579 feat(ui-kit): alwatr-card element (elevated, filled, outlined cards)
  ui/demo-pwa/src/page-card.ts
  ui/demo-pwa/src/pwa-root.ts
  ui/demo-pwa/style/tokens/elevation.css
  ui/demo-pwa/style/tokens/palette.css
  ui/demo-pwa/web-dev-server.config.js
  ui/ui-kit/src/card/card.ts
  ui/ui-kit/src/chat/chat.ts
  ui/ui-kit/src/style/helper/focus-ring.ts
Labels: enhancement

#642 feat(ui/color): separate HCT/HSL color palette
  ui/demo-pwa/style/body.css
  ui/demo-pwa/style/helper/demo.css
  ui/demo-pwa/style/index.css
  ui/demo-pwa/style/tokens/color.css
  ui/demo-pwa/style/tokens/palette-hct.css
  ui/demo-pwa/style/tokens/palette-hsl.css
  ui/demo-pwa/style/tokens/palette.css
Labels: new-feature

#630 feat(type): storage id in AlwatrStorageMeta
  core/storage-engine/src/storage-engine.ts
  core/type/src/storage.ts
  ui/ui-kit/src/chat/chat.ts
Labels: enhancement, minor

#656 docs(services): update all name and descriptions
  services/README.md
  services/comment/README.md
  services/comment/package.json
  services/flight-crawler/README.md
  services/flight-crawler/package.json
  services/starter/.vscode/extensions.json
  services/starter/.vscode/settings.json
  services/starter/CHANGELOG.md
  services/starter/README.md
  services/starter/demo.http
  services/starter/package.json
  services/starter/src/config.ts
  services/starter/src/index.ts
  services/starter/src/lib/nano-server.ts
  services/starter/src/route/echo.ts
  services/starter/src/route/home.ts
  services/starter/tsconfig.json
  services/storage-server/README.md
  services/telegram-notifier/README.md
  services/telegram-notifier/package.json
  tsconfig.json
  uniquely/com-api/README.md
  uniquely/com-api/package.json
  uniquely/flight-finder-api/README.md
  uniquely/flight-finder-api/package.json
  uniquely/flight-finder-pwa/README.md
Labels: documentation, enhancement

#677 refactor: use global _ALWATR_VERSION_ for package version
  cloud/labs/ipsec/env/example.env
  cloud/labs/openvpn/env/example.env
  cloud/labs/v2fly/env/example.env
  core/fetch/src/fetch.ts
  core/i18n/src/i18n.ts
  core/logger/src/global-alwatr.ts
  core/logger/src/logger.ts
  core/math/src/math.ts
  core/nano-server/src/nano-server.ts
  core/router/src/core.ts
  core/signal/src/core.ts
  core/storage-client/src/storage-client.ts
  core/storage-engine/src/storage-engine.ts
  core/token/src/token.ts
  core/type/src/global.ts
  core/type/src/index.ts
  ui/element/src/index.ts
  ui/icon/src/icon.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
Labels: new-feature

#676 feat(pwa): new manual build process with esbuild and external css modules
  .vscode/settings.json
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/alwatr-services.dockerfile
  core/logger/src/global-alwatr.ts
  tsconfig.base.json
  ui/demo-pwa/esbuild.mjs
  ui/demo-pwa/package.json
  ui/demo-pwa/res/color.html
  ui/demo-pwa/res/image/favicon.ico
  ui/demo-pwa/res/image/icon-180.png
  ui/demo-pwa/res/image/icon-192-maskable.png
  ui/demo-pwa/res/image/icon-192.png
  ui/demo-pwa/res/image/icon-512-maskable.png
  ui/demo-pwa/res/image/icon-512.png
  ui/demo-pwa/res/index.html
  ui/demo-pwa/res/l10n/en-US.json
  ui/demo-pwa/res/l10n/fa-IR.json
  ui/demo-pwa/res/manifest.json
  ui/demo-pwa/res/robots.txt
  ui/demo-pwa/rollup.config.js
  ui/demo-pwa/src/alwatr-pwa.ts
  ui/demo-pwa/style/index.css
  ui/demo-pwa/tsconfig.json
  ui/demo-pwa/web-dev-server.config.js
  ui/element/src/index.ts
  ui/element/src/mixins/logging.ts
  ui/element/src/pwa-element.ts
  ui/element/src/surface-element.ts
  ui/ui-kit/style/helper/colors.css
  ui/ui-kit/style/helper/demo.css
  ui/ui-kit/style/helper/elevation-extra.css
  ui/ui-kit/style/helper/mdc-grid-temp.css
  ui/ui-kit/style/helper/typography.css
  ui/ui-kit/style/pwa.css
  ui/ui-kit/style/theme/color.css
  ui/ui-kit/style/theme/palette-300.css
  ui/ui-kit/style/theme/palette-dynamic.css
  ui/ui-kit/style/token.css
  ui/ui-kit/style/token/motion.css
  ui/ui-kit/style/token/radius.css
  ui/ui-kit/style/token/safe-area.css
  ui/ui-kit/style/token/scrollbar.css
  ui/ui-kit/style/token/spacing.css
  ui/ui-kit/style/token/surface.css
  ui/ui-kit/style/token/typography.css
  ui/ui-kit/style/token/z-index.css
Labels: new-feature

#668 feat(ui/element): export `unsafeHTML`
  ui/element/src/index.ts
Labels: enhancement

#665 feat(ui-kit/icon-box): new component
  ui/demo-pwa/esbuild.mjs
  ui/demo-pwa/src/page-card.ts
  ui/element/src/surface-element.ts
  ui/ui-kit/src/card/card.ts
  ui/ui-kit/src/card/icon-box.ts
  ui/ui-kit/style/token/motion.css
Labels: enhancement

#681 feat(element): separate _initLocale, _initRouter and _routeChanged
  ui/element/src/pwa-element.ts
Labels: new-feature

#680 feat(pwa): service worker
  ui/demo-pwa/esbuild.mjs
  ui/demo-pwa/package.json
  ui/demo-pwa/workbox.config.js
  ui/element/src/helper/service-worker.ts
  ui/element/src/pwa-element.ts
  yarn.lock
Labels: new-feature

#659 feat(soffit-pwa): deploy
  .github/workflows/publish-alwatr-container.yml
  cloud/classic/flight-finder/compose.yml
  cloud/classic/soffit-form/compose.yml
  cloud/classic/soffit-pwa/compose.yml
  cloud/classic/soffit-pwa/deploy.sh
  cloud/classic/soffit-pwa/env/example.env
  services/form-registration/README.md
  services/form-registration/demo.http
  services/form-registration/package.json
  services/form-registration/src/config.ts
  services/form-registration/src/index.ts
  services/form-registration/src/lib/nano-server.ts
  services/form-registration/src/lib/storage.ts
  services/form-registration/src/route/home.ts
  services/form-registration/src/route/put.ts
  services/form-registration/src/route/storage.ts
  services/form-registration/tsconfig.json
  tsconfig.json
  uniquely/soffit-pwa/README.md
  uniquely/soffit-pwa/esbuild.mjs
  uniquely/soffit-pwa/package.json
  uniquely/soffit-pwa/res/image/favicon.ico
  uniquely/soffit-pwa/res/image/icon-180.png
  uniquely/soffit-pwa/res/image/icon-192-maskable.png
  uniquely/soffit-pwa/res/image/icon-192.png
  uniquely/soffit-pwa/res/image/icon-512-maskable.png
  uniquely/soffit-pwa/res/image/icon-512.png
  uniquely/soffit-pwa/res/image/soffit.png
  uniquely/soffit-pwa/res/index.html
  uniquely/soffit-pwa/res/l10n/en-US.json
  uniquely/soffit-pwa/res/l10n/fa-IR.json
  uniquely/soffit-pwa/res/manifest.json
  uniquely/soffit-pwa/res/robots.txt
  uniquely/soffit-pwa/src/alwatr-pwa.ts
  uniquely/soffit-pwa/src/page-home.ts
  uniquely/soffit-pwa/tsconfig.json
  uniquely/soffit-pwa/web-dev-server.config.js
  uniquely/soffit-pwa/workbox.config.js
Labels: enhancement, ci

#685 feat(soffit-pwa): page home link
  ui/ui-kit/src/card/icon-box.ts
  uniquely/soffit-pwa/src/page-home.ts
Labels: enhancement

#686 feat(soffit-pwa): theme
  uniquely/soffit-pwa/res/image/favicon.ico
  uniquely/soffit-pwa/res/image/icon-180.png
  uniquely/soffit-pwa/res/image/icon-192-maskable.png
  uniquely/soffit-pwa/res/image/icon-192.png
  uniquely/soffit-pwa/res/image/icon-512-maskable.png
  uniquely/soffit-pwa/res/image/icon-512.png
  uniquely/soffit-pwa/res/image/screenshot/page-home.jpg
  uniquely/soffit-pwa/res/index.html
  uniquely/soffit-pwa/res/manifest.json
  uniquely/soffit-pwa/src/page-home.ts
Labels: enhancement

#687 fix(soffit-pwa): deploy issues
  ui/element/src/helper/service-worker.ts
  uniquely/soffit-pwa/res/manifest.json
Labels: enhancement

#688 fix(demo-ui): offline available pwa config
  ui/demo-pwa/esbuild.mjs
Labels: new-feature

#690 feat(soffit-pwa): screenshots, version, manifest, enhance offline
  uniquely/soffit-pwa/package.json
  uniquely/soffit-pwa/res/image/screenshot-1.jpg
  uniquely/soffit-pwa/res/image/screenshot-2.jpg
  uniquely/soffit-pwa/res/image/screenshot/page-home.jpg
  uniquely/soffit-pwa/res/index.html
  uniquely/soffit-pwa/res/manifest.webmanifest
  uniquely/soffit-pwa/src/page-home.ts
Labels: new-feature

#695 fix: compatible with new esbuild api
  package.json
  ui/demo-pwa/esbuild.mjs
  ui/demo-pwa/package.json
  ui/demo-pwa/web-dev-server.config.js
  uniquely/flight-finder-pwa/package.json
  uniquely/flight-finder-pwa/web-dev-server.config.js
  uniquely/soffit-pwa/package.json
  uniquely/soffit-pwa/web-dev-server.config.js
  web-dev-server.config.js
  yarn.lock
Labels: new-feature

#696 feat(surface)!: new surface element in ui-kit, remove old SurfaceElement class and add active-outline state
  ui/element/src/index.ts
  ui/ui-kit/src/card/card.ts
  ui/ui-kit/src/card/surface-element.ts
Labels: new-feature

#697 feat(ui/style): mobile only style
  ui/ui-kit/style/mobile-only.css
  ui/ui-kit/style/token/scrollbar.css
Labels: new-feature

#698 feat(ui-kit): simple button element
  ui/ui-kit/src/button/button.ts
Labels: new-feature

#699 refactor(icon-button)!: rename ols standard-icon-button element
  ui/ui-kit/src/button/icon-button.ts
Labels: new-feature

#700 feat(icon-box): ass slot, highlight, pre-line, enhance typescale, enhance template
  ui/ui-kit/src/card/icon-box.ts
Labels: new-feature

#701 feat(ui-kit): text-field element
  ui/ui-kit/src/text-field/text-field.ts
Labels: new-feature

#702 fix(ui-kit/chat): compatibility with new icon-button
  ui/ui-kit/src/chat/chat-footer.ts
  ui/ui-kit/src/chat/chat-text-input.ts
Labels: new-feature

#703 fix: demo-pwa and ui-kit surface element file name and imports
  ui/demo-pwa/src/page-card.ts
  ui/ui-kit/src/button/button.ts
  ui/ui-kit/src/button/icon-button.ts
  ui/ui-kit/src/card/icon-box.ts
  ui/ui-kit/src/card/surface.ts
  ui/ui-kit/src/text-field/text-field.ts
Labels: new-feature

#684 feat(soffit-pwa): page form
  uniquely/soffit-pwa/src/alwatr-pwa.ts
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/page-home.ts
Labels: new-feature

#693 feat(soffit-form): submit form
  .gitignore
  ui/demo-pwa/esbuild.mjs
  ui/demo-pwa/res/service-worker.js
  ui/ui-kit/src/button/button.ts
  ui/ui-kit/src/card/icon-box.ts
  ui/ui-kit/src/card/surface.ts
  ui/ui-kit/src/text-field/text-field.ts
  uniquely/soffit-pwa/package.json
  uniquely/soffit-pwa/res/config.js
  uniquely/soffit-pwa/res/index.html
  uniquely/soffit-pwa/res/service-worker.js
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/tech-dep/config.ts
  uniquely/soffit-pwa/src/tech-dep/radio-group.ts
  uniquely/soffit-pwa/tsconfig.json
Labels: new-feature

#705 feat(soffit/form): expand/collapse animation
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/lottery-form.ts
Labels: new-feature

#707 feat(soffit/form): improve animation and clear extra styles
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/tech-dep/radio-group.ts
Labels: new-feature

#709 Feat/for soffit
  ui/ui-kit/src/card/icon-box.ts
  ui/ui-kit/src/card/surface.ts
  ui/ui-kit/style/token/motion.css
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/tech-dep/radio-group.ts
  uniquely/soffit-pwa/src/tech-dep/util.ts
Labels: new-feature

#710 feat(soffit-pwa): form validator and simple message
  core/math/src/unicode-digits.ts
  core/validator/src/validator.ts
  ui/ui-kit/src/card/icon-box.ts
  ui/ui-kit/src/text-field/text-field.ts
  ui/ui-kit/tsconfig.json
  uniquely/soffit-pwa/package.json
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/tsconfig.json
Labels: new-feature

#704 feat(cloud): soffit form deploy
  cloud/classic/soffit-form/compose.yml
  cloud/classic/soffit-form/deploy.sh
  cloud/classic/soffit-form/env/example.env
  cloud/classic/soffit-pwa/compose.yml
  cloud/classic/soffit-pwa/env/example.env
  core/nano-server/src/nano-server.ts
  services/form-registration/demo.http
  services/form-registration/src/route/put.ts
  services/form-registration/src/route/storage.ts
  ui/demo-pwa/package.json
  uniquely/soffit-pwa/res/config.js
  uniquely/soffit-pwa/src/lottery-form.ts
Labels: enhancement

#711 fix(soffit-pwa): server deploy issues
  cloud/classic/soffit-pwa/compose.yml
  uniquely/soffit-pwa/res/config.js
Labels: minor, bugfix

#725 refactor: clean scripts
  core/math/package.json
  core/router/package.json
  core/signal/package.json
  core/token/package.json
  core/validator/package.json
  demo/package.json
  labs/zx-example/package.json
  package.json
  services/comment/package.json
  services/flight-crawler/package.json
  services/form-registration/package.json
  services/storage-server/package.json
  services/telegram-notifier/package.json
  ui/demo-pwa/package.json
  ui/font/package.json
  ui/icon/package.json
  uniquely/com-api/package.json
  uniquely/flight-finder-api/package.json
  uniquely/flight-finder-pwa/package.json
  uniquely/soffit-pwa/package.json
  yarn.lock
Labels: new-feature

#720 feat(signal)!: new signal api and interface
  .vscode/settings.json
  core/i18n/src/i18n.ts
  core/i18n/src/type.ts
  core/signal/README.md
  core/signal/package.json
  core/signal/src/command-handler.ts
  core/signal/src/command-trigger.ts
  core/signal/src/context-consumer.ts
  core/signal/src/context-provider.ts
  core/signal/src/core.ts
  core/signal/src/event-listener.ts
  core/signal/src/event-trigger.ts
  core/signal/src/index.ts
  core/signal/src/requestable-context-consumer.ts
  core/signal/src/requestable-context-provider.ts
  core/signal/src/signal.ts
  core/signal/src/type.ts
  core/signal/tsconfig.json
  core/type/src/type-helper.ts
  ui/element/src/mixins/signal.ts
Labels: new-feature, breaking-change

#733 feat(fetch): add update_cache to CacheStrategy
  core/fetch/src/fetch.ts
  core/fetch/src/type.ts
Labels: new-feature

#732 feat(i18n)!: new i18n from scratch!
  core/i18n/package.json
  core/i18n/src/core.ts
  core/i18n/src/i18n.ts
  core/i18n/src/index.ts
  core/i18n/src/type.ts
  core/i18n/tsconfig.json
  core/type/src/i18n.ts
  ui/element/src/mixins/localize.ts
Labels: new-feature

#734 feat(i18n): review
  core/i18n/src/core.ts
  ui/element/src/mixins/signal.ts
Labels: documentation, bugfix

#735 feat(router): new api from scratch!
  core/router/package.json
  core/router/src/core.ts
  core/router/src/index.ts
  core/router/src/router.ts
  core/router/src/signal.ts
  core/router/src/trigger-click.ts
  core/router/src/trigger-popstate.ts
  core/router/src/type.ts
  core/router/tsconfig.json
  core/type/src/service-response.ts
Labels: new-feature, breaking-change

#717 feat(alwatr-util): new core package
  core/util/README.md
  core/util/package.json
  core/util/src/index.ts
  core/util/src/until.ts
  core/util/tsconfig.json
  tsconfig.json
  uniquely/soffit-pwa/package.json
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/tech-dep/util.ts
  uniquely/soffit-pwa/tsconfig.json
Labels: new-feature

#736 fix: compatible with new api's and build issues
  core/i18n/src/core.ts
  core/i18n/src/index.ts
  core/nano-server/src/nano-server.ts
  core/router/src/core.ts
  core/router/src/index.ts
  core/router/src/trigger-click.ts
  core/router/src/trigger-popstate.ts
  core/router/src/type.ts
  core/type/src/customer-order-management.ts
  core/type/src/i18n.ts
  demo/router/index.html
  demo/router/index.ts
  demo/signal/index.html
  demo/signal/index.ts
  ui/demo-pwa/src/alwatr-pwa.ts
  ui/element/src/mixins/direction.ts
  ui/element/src/mixins/localize.ts
  ui/element/src/pwa-element.ts
  ui/ui-kit/src/chat/chat-footer.ts
  ui/ui-kit/src/chat/chat-text-input.ts
  uniquely/flight-finder-pwa/src/alwatr-pwa.ts
  uniquely/flight-finder-pwa/src/component/job-add-form.ts
  uniquely/flight-finder-pwa/src/component/job-item.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
  uniquely/flight-finder-pwa/src/director/job-add.ts
  uniquely/flight-finder-pwa/src/director/job-delete.ts
  uniquely/flight-finder-pwa/src/director/job-document-storage.ts
  uniquely/flight-finder-pwa/src/director/toast.ts
  uniquely/flight-finder-pwa/src/type.ts
  uniquely/soffit-pwa/src/alwatr-pwa.ts
Labels: enhancement, new-feature, breaking-change, bugfix

#740 feat(element): rewrite all mixins with new api
  ui/demo-pwa/package.json
  ui/demo-pwa/src/alwatr-pwa.ts
  ui/element/src/index.ts
  ui/element/src/lit.ts
  ui/element/src/mixins/direction.ts
  ui/element/src/mixins/localize.ts
  ui/element/src/mixins/logging.ts
  ui/element/src/mixins/signal.ts
  ui/element/src/pwa-element.ts
  ui/icon/src/icon.ts
  ui/ui-kit/src/card/icon-box.ts
  ui/ui-kit/src/chat/chat-bubble.ts
  ui/ui-kit/src/chat/chat-message.ts
  ui/ui-kit/src/chat/chat-text-input.ts
Labels: enhancement, new-feature, breaking-change

#741 feat(soffit-pwa): form close animation
  ui/demo-pwa/res/l10n/en-US.json
  ui/demo-pwa/res/l10n/fa-IR.json
  uniquely/flight-finder-pwa/package.json
  uniquely/soffit-pwa/res/l10n/en-US.json
  uniquely/soffit-pwa/res/l10n/fa-IR.json
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/page-home.ts
Labels: new-feature

#742 fix: clean ff old packages
  .github/workflows/build.yaml
  package.json
  tsconfig.json
  uniquely/flight-finder-pwa/package.json
  web-dev-server.config.js
  yarn.lock
Labels: enhancement, bugfix

#743 feat(element/direction): compute dir mode and improve performance
  .github/workflows/publish-alwatr-container.yml
  ui/element/src/mixins/direction.ts
Labels: enhancement, new-feature, performance

#744 chore(yarn): clean and upgrade
  package.json
  services/comment/package.json
  services/flight-crawler/package.json
  services/form-registration/package.json
  services/storage-server/package.json
  services/telegram-notifier/package.json
  ui/demo-pwa/package.json
  uniquely/com-api/package.json
  uniquely/flight-finder-api/package.json
  uniquely/flight-finder-pwa/package.json
  uniquely/soffit-pwa/package.json
  yarn.lock
Labels: dependencies

#719 feat(snackbar): new ui-kit snackbar element
  ui/demo-pwa/src/alwatr-pwa.ts
  ui/ui-kit/package.json
  ui/ui-kit/src/snackbar/snackbar.ts
  ui/ui-kit/style/token/typography.css
  ui/ui-kit/tsconfig.json
  uniquely/soffit-pwa/src/page-home.ts
Labels: new-feature

#750 feat(signal): separate request command with response
  core/signal/src/command-trigger.ts
  core/signal/src/core.ts
Labels: new-feature

#751 fix(ui): some visual issues
  .vscode/settings.json
  ui/ui-kit/src/button/button.ts
  ui/ui-kit/src/card/surface.ts
  ui/ui-kit/style/mobile-only.css
Labels: bugfix
