Repository AliMD/alwatr, pull requests merged in 2023-02, with the labels that each got.

#753 feat(snackbar): command signal and controller
  core/math/src/math.ts
  core/signal/src/core.ts
  ui/ui-kit/package.json
  ui/ui-kit/src/snackbar/controller.ts
  ui/ui-kit/src/snackbar/element.ts
  ui/ui-kit/src/snackbar/show-snackbar.ts
  ui/ui-kit/src/snackbar/type.ts
  ui/ui-kit/tsconfig.json
  uniquely/soffit-pwa/src/page-home.ts
Labels: new-feature

#759 feat(pwa-helper): get config
  ui/pwa-helper/src/config.ts
  uniquely/soffit-pwa/src/config.ts
  uniquely/soffit-pwa/src/lottery-form.ts
Labels: new-feature

#752 feat(soffit-pwa): new card
  .vscode/settings.json
  cloud/classic/soffit-pwa/compose.yml
  cloud/classic/soffit-pwa/env/beta.soffit.co
  cloud/classic/soffit-pwa/env/example.env
  package.json
  services/form-registration/demo.http
  services/form-registration/src/config.ts
  services/form-registration/src/index.ts
  services/form-registration/src/route/put.ts
  services/form-registration/src/route/storage.ts
  tsconfig.json
  ui/pwa-helper/src/config.ts
  ui/pwa-helper/src/pwa-element.ts
  ui/ui-kit/src/card/icon-box.ts
  ui/ui-kit/src/snackbar/controller.ts
  ui/ui-kit/src/snackbar/element.ts
  ui/ui-kit/src/snackbar/show-snackbar.ts
  ui/ui-kit/style/token/z-index.css
  uniquely/soffit-pwa/res/image/soffit.png
  uniquely/soffit-pwa/res/image/soffit.svg
  uniquely/soffit-pwa/src/content.ts
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/page-home.ts
  uniquely/soffit-pwa/src/supply-chain-box.ts
  uniquely/soffit-pwa/src/supply-chain-form.ts
  uniquely/soffit-pwa/src/tech-dep/radio-group.ts
  yarn.lock
Labels: enhancement

#764 feat(i18n): add replaceNumber and auto detect setLocale from html
  core/i18n/package.json
  core/i18n/src/core.ts
  core/i18n/src/index.ts
  core/i18n/tsconfig.json
  core/math/src/unicode-digits.ts
  demo/math/translate-unicode-digits.ts
  ui/ui-kit/src/chat/chat-footer.ts
  ui/ui-kit/src/text-field/text-field.ts
Labels: new-feature

#765 feat(spffir-pwa): service worker signals and user snackbar message on events
  ui/demo-pwa/esbuild.mjs
  ui/demo-pwa/package.json
  ui/pwa-helper/esbuild.mjs
  ui/pwa-helper/package.json
  ui/pwa-helper/src/director.ts
  ui/pwa-helper/src/logger.ts
  ui/pwa-helper/src/pwa-element.ts
  ui/pwa-helper/src/signal/register-service-worker-command.ts
  ui/pwa-helper/src/signal/sw-user-notify.ts
  ui/pwa-helper/tsconfig.json
  ui/ui-kit/src/snackbar/controller.ts
  ui/ui-kit/src/snackbar/show-snackbar.ts
  uniquely/soffit-pwa/esbuild.mjs
  uniquely/soffit-pwa/package.json
  uniquely/soffit-pwa/src/alwatr-pwa.ts
  uniquely/soffit-pwa/src/director.ts
  uniquely/soffit-pwa/src/lottery-form.ts
Labels: new-feature

#766 feat(nginx): optimize for pwa
  .github/workflows/publish-special-container.yml
  cloud/container/alwatr-pwa.dockerfile
  cloud/container/nginx/Dockerfile
  cloud/container/nginx/conf/templates/http.d/40-map-expire.conf.template
  cloud/container/nginx/conf/templates/http.d/60-performance.conf.template
  cloud/container/nginx/conf/templates/location.d/40-secure.conf.template
  cloud/container/nginx/conf/templates/location.d/50-pwa.template
  cloud/container/nginx/conf/templates/location.d/90-secure-wp.conf.skiped
Labels: enhancement

#767 feat(pwa, i18n): dynamic loader
  .vscode/settings.json
  core/i18n/src/core.ts
  package.json
  ui/demo-pwa/package.json
  ui/element/src/mixins/direction.ts
  ui/element/src/mixins/signal.ts
  ui/pwa-helper/esbuild.mjs
  uniquely/flight-finder-pwa/package.json
  uniquely/soffit-pwa/package.json
  uniquely/soffit-pwa/src/director.ts
  uniquely/soffit-pwa/src/l18r/en.json
  uniquely/soffit-pwa/src/l18r/fa.json
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/tsconfig.json
Labels: new-feature

#770 fix(github-actions): specific all versions
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/lint.yaml
  .github/workflows/lock-closed.yml
  .github/workflows/publish-alwatr-container.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-special-container.yml
  .github/workflows/stale.yml
  .github/workflows/sync-labels.yml
Labels: ci

#773 feat(math): uuid
  core/math/src/math.ts
  demo/math/translate-unicode-digits.ts
Labels: new-feature

#776 feat(element): Alwatr logger index
  ui/element/src/mixins/logging.ts
Labels: new-feature

#769 feat(soffit-pwa): new version with i18n, content loader, form submit signal
  core/signal/src/command-trigger.ts
  core/signal/src/core.ts
  core/type/src/type-helper.ts
  ui/demo-pwa/src/page-card.ts
  ui/demo-pwa/src/page-chat.ts
  ui/icon/src/icon.ts
  ui/pwa-helper/esbuild.mjs
  ui/pwa-helper/package.json
  ui/pwa-helper/src/pwa-element.ts
  ui/ui-kit/src/button/icon-button.ts
  ui/ui-kit/src/card/icon-box.ts
  ui/ui-kit/src/chat/chat-avatar.ts
  ui/ui-kit/src/chat/chat-bubble.ts
  ui/ui-kit/src/chat/chat-footer.ts
  ui/ui-kit/src/chat/chat-list.ts
  ui/ui-kit/src/chat/chat-message.ts
  ui/ui-kit/src/chat/chat-text-input.ts
  ui/ui-kit/src/chat/chat.ts
  ui/ui-kit/src/snackbar/element.ts
  uniquely/flight-finder-pwa/src/component/job-add-form.ts
  uniquely/flight-finder-pwa/src/component/job-item.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
  uniquely/soffit-pwa/package.json
  uniquely/soffit-pwa/src/alwatr-pwa.ts
  uniquely/soffit-pwa/src/content/en.ts
  uniquely/soffit-pwa/src/content/fa.ts
  uniquely/soffit-pwa/src/director.ts
  uniquely/soffit-pwa/src/director/content-provider.ts
  uniquely/soffit-pwa/src/director/form-submit.ts
  uniquely/soffit-pwa/src/director/index.ts
  uniquely/soffit-pwa/src/director/l18e-loader.ts
  uniquely/soffit-pwa/src/director/logger.ts
  uniquely/soffit-pwa/src/l18r/en.json
  uniquely/soffit-pwa/src/l18r/fa.json
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/page-home.ts
  uniquely/soffit-pwa/src/supply-chain-box.ts
  uniquely/soffit-pwa/src/supply-chain-form.ts
  uniquely/soffit-pwa/src/tech-dep/radio-group.ts
  uniquely/soffit-pwa/src/type.ts
  uniquely/soffit-pwa/workbox.config.js
  web-dev-server.config.js
  yarn.lock
Labels: new-feature

#775 feat(form-registration): remoteAddress and deviceId
  core/fetch/package.json
  core/fetch/src/fetch.ts
  core/fetch/src/type.ts
  core/fetch/tsconfig.json
  core/math/src/math.ts
  core/nano-server/src/type.ts
  demo/math/translate-unicode-digits.ts
  services/form-registration/demo.http
  services/form-registration/src/lib/storage.ts
  services/form-registration/src/route/put.ts
  services/form-registration/src/type.ts
  uniquely/soffit-pwa/src/director/index.ts
  uniquely/soffit-pwa/src/director/submit-form-handler.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/tech-dep/radio-group.ts
Labels: new-feature

#781 fix(element): logger mixin issue
  ui/element/src/mixins/logging.ts
Labels: bugfix

#786 feat(icon-button): new standard icon button
  ui/pwa-helper/package.json
  ui/ui-kit/src/button/icon-button.ts
  ui/ui-kit/src/card/icon-box.ts
  ui/ui-kit/src/card/surface.ts
  ui/ui-kit/style/pwa.css
Labels: new-feature

#787 fix(typescript): rollback to v4.9.5
  .vscode/settings.json
  core/math/src/math.ts
  package.json
  services/comment/package.json
  services/flight-crawler/package.json
  services/form-registration/package.json
  services/storage-server/package.json
  services/telegram-notifier/package.json
  tsconfig.base.json
  ui/demo-pwa/package.json
  ui/ui-kit/package.json
  uniquely/com-api/package.json
  uniquely/flight-finder-api/package.json
  uniquely/flight-finder-pwa/package.json
  uniquely/soffit-pwa/package.json
  uniquely/soffit-pwa/src/content/en.ts
  uniquely/soffit-pwa/src/content/fa.ts
  uniquely/soffit-pwa/src/type.ts
  uniquely/soffit-pwa/tsconfig.json
  yarn.lock
Labels: new-feature

#788 feat(icon-button): new content prop with click signal event
  core/type/src/event-signal.ts
  core/type/src/index.ts
  ui/ui-kit/src/button/icon-button.ts
  ui/ui-kit/src/card/icon-box.ts
  uniquely/soffit-pwa/src/director/l18e-loader.ts
Labels: new-feature

#623 feat(top-app-bar): new `alwatr-top-app-bar` element
  ui/ui-kit/src/button/icon-button.ts
  ui/ui-kit/src/top-app-bar/top-app-bar.ts
  uniquely/soffit-pwa/src/alwatr-pwa.ts
  uniquely/soffit-pwa/src/page-product.ts
Labels: enhancement, new-feature

#789 feat(soffit): home page top app bar
  ui/ui-kit/src/top-app-bar/top-app-bar.ts
  uniquely/soffit-pwa/src/content/en.ts
  uniquely/soffit-pwa/src/content/fa.ts
  uniquely/soffit-pwa/src/director/change-language.ts
  uniquely/soffit-pwa/src/director/index.ts
  uniquely/soffit-pwa/src/page-home.ts
  uniquely/soffit-pwa/src/type.ts
Labels: new-feature

#790 feat(soffit, snackbar): enhance spacing
  ui/ui-kit/src/button/button.ts
  ui/ui-kit/src/snackbar/element.ts
  ui/ui-kit/style/token/radius.css
  uniquely/soffit-pwa/src/content/en.ts
  uniquely/soffit-pwa/src/content/fa.ts
  uniquely/soffit-pwa/src/director/change-language.ts
  uniquely/soffit-pwa/src/page-home.ts
Labels: new-feature

#627 feat(com-api): routes and refactor all services types
  .vscode/settings.json
  core/fetch/src/fetch.ts
  core/nano-server/src/nano-server.ts
  core/storage-client/src/storage-client.ts
  core/type/src/customer-order-management.ts
  core/type/src/flight-finder.ts
  core/type/src/service-response.ts
  core/type/src/storage.ts
  core/type/src/user.ts
  core/validator/package.json
  core/validator/src/validator.ts
  core/validator/tsconfig.json
  demo/token/benchmark.ts
  demo/tsconfig.json
  services/comment/src/route/patch.ts
  services/comment/src/route/storage.ts
  services/flight-crawler/src/lib/type.ts
  services/form-registration/src/route/put.ts
  services/storage-server/src/route/delete.ts
  services/storage-server/src/route/get.ts
  services/storage-server/src/route/has.ts
  services/storage-server/src/route/keys.ts
  services/storage-server/src/route/patch.ts
  services/storage-server/src/route/storage.ts
  services/telegram-notifier/src/route/notify.ts
  tsconfig.json
  uniquely/com-api/demo.http
  uniquely/com-api/package.json
  uniquely/com-api/src/config.ts
  uniquely/com-api/src/index.ts
  uniquely/com-api/src/lib/config.ts
  uniquely/com-api/src/lib/server.ts
  uniquely/com-api/src/lib/storage.ts
  uniquely/com-api/src/lib/token.ts
  uniquely/com-api/src/route/get-order.ts
  uniquely/com-api/src/route/get-product.ts
  uniquely/com-api/src/route/home.ts
  uniquely/com-api/src/route/put-order.ts
  uniquely/com-api/tsconfig.json
  uniquely/flight-finder-api/src/route/job/delete.ts
  uniquely/flight-finder-api/src/route/job/get.ts
  uniquely/flight-finder-api/src/route/job/put.ts
Labels: new-feature

#797 feat(com-pwa): Customer Order Management PWA
  cloud/classic/com-pwa/compose.yml
  cloud/classic/com-pwa/deploy.sh
  cloud/classic/com-pwa/env/order.soffit.co.env
  cloud/classic/lib/deploy.sh
  cloud/classic/soffit-pwa/compose.yml
  tsconfig.json
  ui/pwa-helper/esbuild.mjs
  ui/pwa-helper/package.json
  ui/pwa-helper/pwa-dev-server.config.js
  ui/pwa-helper/src/config.ts
  ui/pwa-helper/src/director.ts
  ui/pwa-helper/src/logger.ts
  ui/pwa-helper/src/signal/back-click-event.ts
  ui/ui-kit/style/theme/palette-85.css
  uniquely/com-api/src/lib/config.ts
  uniquely/com-pwa/README.md
  uniquely/com-pwa/esbuild.mjs
  uniquely/com-pwa/package.json
  uniquely/com-pwa/res/config.js
  uniquely/com-pwa/res/image
  uniquely/com-pwa/res/index.html
  uniquely/com-pwa/res/manifest.webmanifest
  uniquely/com-pwa/res/robots.txt
  uniquely/com-pwa/res/service-worker.js
  uniquely/com-pwa/src/alwatr-pwa.ts
  uniquely/com-pwa/src/config.ts
  uniquely/com-pwa/src/content/home-page-fa.ts
  uniquely/com-pwa/src/director/content-provider.ts
  uniquely/com-pwa/src/director/index.ts
  uniquely/com-pwa/src/director/l18e-loader.ts
  uniquely/com-pwa/src/director/logger.ts
  uniquely/com-pwa/src/l18r/fa.json
  uniquely/com-pwa/src/page-404.ts
  uniquely/com-pwa/src/page-home.ts
  uniquely/com-pwa/src/type.ts
  uniquely/com-pwa/tsconfig.json
  uniquely/com-pwa/web-dev-server.config.js
  uniquely/soffit-pwa/res/config.js
  uniquely/soffit-pwa/web-dev-server.config.js
Labels: new-feature

#798 fix(fetch): getClientId in nodejs
  core/fetch/src/fetch.ts
  core/logger/src/logger.ts
Labels: new-feature

#799 feat(nano-server): getRemoteAddress, requireClientId
  core/nano-server/src/nano-server.ts
  core/nano-server/src/type.ts
  package.json
  services/form-registration/src/route/put.ts
  uniquely/com-api/src/route/put-order.ts
Labels: new-feature, bugfix

#802 feat(util): parseJson, getLocalStorageItem, getClientId
  core/math/src/math.ts
  core/util/package.json
  core/util/src/client-id.ts
  core/util/src/index.ts
  core/util/src/json.ts
  core/util/src/local-storage.ts
  core/util/tsconfig.json
  demo/math/translate-unicode-digits.ts
Labels: new-feature

#803 feat(fetch): fetchContext
  core/fetch/package.json
  core/fetch/src/fetch.ts
  core/fetch/tsconfig.json
Labels: new-feature

#800 feat(soffit-order): add product route
  cloud/classic/com-pwa/compose.yml
  cloud/classic/com-pwa/env/order.soffit.co.env
  uniquely/com-api/add-product.http
  uniquely/com-api/demo.http
  uniquely/com-api/src/index.ts
  uniquely/com-api/src/lib/config.ts
  uniquely/com-api/src/route/get-order.ts
  uniquely/com-api/src/route/get-product.ts
  uniquely/com-api/src/route/patch-product.ts
  uniquely/com-api/src/route/put-order.ts
Labels: new-feature

#804 feat(fetch): enhance fetchContext with dispatchOptions and use cache_only request in first time
  core/fetch/src/fetch.ts
Labels: new-feature

#805 fix(signal): API issues
  core/fetch/src/fetch.ts
  core/signal/src/context-provider.ts
  core/signal/src/core.ts
  core/signal/src/index.ts
  core/signal/src/requestable-context-consumer.ts
Labels: new-feature

#801 feat(com-pwa): directors, server transactions, context providers
  cloud/classic/com-pwa/compose.yml
  core/type/src/index.ts
  ui/ui-kit/src/card/icon-box.ts
  uniquely/com-api/add-product.http
  uniquely/com-pwa/package.json
  uniquely/com-pwa/res/config.js
  uniquely/com-pwa/src/config.ts
  uniquely/com-pwa/src/content/home-page-fa.ts
  uniquely/com-pwa/src/context.ts
  uniquely/com-pwa/src/director/index.ts
  uniquely/com-pwa/src/director/order-storage-context-provider.ts
  uniquely/com-pwa/src/director/product-storage-context-provider.ts
  uniquely/com-pwa/src/director/submit-order-command-handler.ts
  uniquely/com-pwa/src/director/user-context-provider.ts
  uniquely/com-pwa/src/l18r/fa.json
  uniquely/com-pwa/src/page-404.ts
  uniquely/com-pwa/src/page-home.ts
  uniquely/com-pwa/tsconfig.json
  uniquely/soffit-pwa/package.json
  uniquely/soffit-pwa/res/image/sample-1.jpg
  uniquely/soffit-pwa/res/image/sample-2.jpg
  uniquely/soffit-pwa/res/image/sample-3.jpg
  uniquely/soffit-pwa/res/image/sample-4.jpg
  uniquely/soffit-pwa/src/content/home-page-fa.ts
  uniquely/soffit-pwa/src/director/index.ts
  uniquely/soffit-pwa/src/director/submit-form-command-handler.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/tsconfig.json
  uniquely/soffit-pwa/web-dev-server.config.js
Labels: new-feature

#807 feat(cards): tinted (without elevate)
  ui/ui-kit/src/card/icon-box.ts
  ui/ui-kit/src/card/surface.ts
  ui/ui-kit/src/top-app-bar/top-app-bar.ts
Labels: new-feature

#808 feat(i18n): l18eReadyPromise, localeKeys type
  core/i18n/src/core.ts
  core/i18n/src/index.ts
  core/type/src/i18n.ts
Labels: enhancement

#806 feat(com-pwa): order list page
  core/type/src/customer-order-management.ts
  ui/ui-kit/src/top-app-bar/top-app-bar.ts
  uniquely/com-pwa/src/alwatr-pwa.ts
  uniquely/com-pwa/src/app-footer.ts
  uniquely/com-pwa/src/content/home-page-fa.ts
  uniquely/com-pwa/src/context.ts
  uniquely/com-pwa/src/director/content-provider.ts
  uniquely/com-pwa/src/director/order-storage-context-provider.ts
  uniquely/com-pwa/src/director/product-storage-context-provider.ts
  uniquely/com-pwa/src/l18r/fa.json
  uniquely/com-pwa/src/page-404.ts
  uniquely/com-pwa/src/page-home.ts
  uniquely/com-pwa/src/page-order-list.ts
  uniquely/soffit-pwa/src/content/product-page-en.ts
  uniquely/soffit-pwa/src/content/product-page-fa.ts
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/supply-chain-box.ts
Labels: new-feature

#811 feat(com-pwa): screenshots and improve layout and scrolls
  ui/pwa-helper/package.json
  uniquely/com-pwa/res/manifest.webmanifest
  uniquely/com-pwa/src/page-404.ts
  uniquely/com-pwa/src/page-home.ts
  uniquely/soffit-pwa/res/image/screenshot-1.png
  uniquely/soffit-pwa/res/image/screenshot-2.png
Labels: new-feature

#819 feat(icon): add toman icon
  ui/icon/svg/toman.svg
Labels: new-feature

#822 feat: add es benchmarks tests
  demo/es-bench/bench.ts
  demo/es-bench/for-in-vs-of.ts
  demo/es-bench/index.html
  demo/index.html
  demo/package.json
Labels: new-feature

#823 feat(element): mapIterable, mapObject directives
  ui/element/src/directives/map.ts
  ui/element/src/index.ts
Labels: enhancement

#824 feat(element): toggle mixin
  ui/element/src/index.ts
  ui/element/src/mixins/toggle.ts
Labels: new-feature

#825 refactor(pwa): remove ui managers from director worker
  ui/pwa-helper/src/director.ts
  ui/pwa-helper/src/pwa-element.ts
  uniquely/com-pwa/src/director/index.ts
  uniquely/soffit-pwa/src/director/index.ts
Labels: enhancement, bugfix

#826 feat(ui-kit): selectable product card
  ui/ui-kit/src/button/icon-button.ts
  ui/ui-kit/src/card/product-card.ts
  ui/ui-kit/src/card/surface.ts
Labels: new-feature

#652 feat(com-pwa): page-product-list and enhance renders
  uniquely/com-pwa/res/config.js
  uniquely/com-pwa/src/alwatr-pwa.ts
  uniquely/com-pwa/src/content/home-page-fa.ts
  uniquely/com-pwa/src/director/logger.ts
  uniquely/com-pwa/src/director/order-storage-context-provider.ts
  uniquely/com-pwa/src/director/product-storage-context-provider.ts
  uniquely/com-pwa/src/l18r/fa.json
  uniquely/com-pwa/src/page-404.ts
  uniquely/com-pwa/src/page-home.ts
  uniquely/com-pwa/src/page-order-list.ts
  uniquely/com-pwa/src/page-product-list.ts
  uniquely/flight-finder-api/src/route/job/get.ts
  uniquely/soffit-pwa/src/content/home-page-fa.ts
  uniquely/soffit-pwa/src/director/change-language.ts
Labels: enhancement

#829 feat(element): router mixin
  ui/element/src/index.ts
  ui/element/src/mixins/localize.ts
  ui/element/src/mixins/router.ts
Labels: new-feature

#830 feat(com-api)!: limit productStorageList and product-list storage param
  uniquely/com-api/demo-data.http
  uniquely/com-api/demo.http
  uniquely/com-api/src/lib/config.ts
  uniquely/com-api/src/route/get-product-list.ts
Labels: new-feature

#832 feat(com-pwa): price list
  cloud/classic/com-pwa/compose.yml
  cloud/classic/com-pwa/env/order.soffit.co.env
  cloud/classic/soffit-pwa/env/beta.soffit.co.env
  cloud/classic/soffit-pwa/env/soffit.co.env
  core/i18n/src/core.ts
  ui/element/src/directives/map.ts
  ui/pwa-helper/package.json
  ui/ui-kit/src/card/product-card.ts
  uniquely/com-api/demo.http
  uniquely/com-api/src/route/patch-product-list.ts
  uniquely/com-pwa/src/config.ts
  uniquely/com-pwa/src/director/order-storage-context-provider.ts
  uniquely/com-pwa/src/director/product-storage-context-provider.ts
  uniquely/com-pwa/src/director/submit-order-command-handler.ts
  uniquely/com-pwa/src/l18r/fa.json
  uniquely/com-pwa/src/page-404.ts
  uniquely/com-pwa/src/page-product-list.ts
Labels: new-feature

#818 refactor(element): remove dummy & smart element & add base element
  ui/demo-pwa/src/page-card.ts
  ui/demo-pwa/src/page-chat.ts
  ui/element/src/base-element.ts
  ui/element/src/index.ts
  ui/element/src/smart-element.ts
  ui/icon/src/icon.ts
  ui/pwa-helper/src/pwa-element.ts
  ui/ui-kit/src/card/surface.ts
  ui/ui-kit/src/chat/chat-avatar.ts
  ui/ui-kit/src/chat/chat-bubble.ts
  ui/ui-kit/src/chat/chat-footer.ts
  ui/ui-kit/src/chat/chat-list.ts
  ui/ui-kit/src/chat/chat-message.ts
  ui/ui-kit/src/chat/chat-text-input.ts
  ui/ui-kit/src/chat/chat.ts
  uniquely/com-pwa/src/app-footer.ts
  uniquely/com-pwa/src/page-404.ts
  uniquely/com-pwa/src/page-home.ts
  uniquely/com-pwa/src/page-order-list.ts
  uniquely/com-pwa/src/page-product-list.ts
  uniquely/flight-finder-pwa/src/component/job-add-form.ts
  uniquely/flight-finder-pwa/src/component/job-item.ts
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
  uniquely/soffit-pwa/src/lottery-box.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/page-home.ts
  uniquely/soffit-pwa/src/page-product.ts
  uniquely/soffit-pwa/src/tech-dep/radio-group.ts
Labels: enhancement, minor

#834 feat(ui-kit): move radio group from soffit-pwa
  ui/ui-kit/src/radio-group/radio-group.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/supply-chain-form.ts
Labels: new-feature

#845 feat: Alwatr Finite State Machines
  core/fsm/README.md
  core/fsm/package.json
  core/fsm/src/core.ts
  core/fsm/tsconfig.json
  demo/finite-state-machine/light-machine.ts
  demo/tsconfig.json
  tsconfig.json
Labels: new-feature

#846 feat(fsm): rewrite with signal power
  core/fsm/package.json
  core/fsm/src/core.ts
  core/fsm/tsconfig.json
  demo/finite-state-machine/light-machine.ts
Labels: new-feature

#847 feat(util): polyfil requestAnimationFrame, requestIdleCallbackFallback
  core/util/src/delay.ts
  core/util/src/index.ts
  core/util/src/polyfill.ts
Labels: new-feature

#848 fix(signal): nodejs compatibility
  core/signal/package.json
  core/signal/src/core.ts
  core/signal/tsconfig.json
Labels: enhancement

#849 refactor(signal)!: change subscribe default receivePrevious to NextCycle
  core/signal/src/core.ts
  core/signal/src/type.ts
Labels: breaking-change, bugfix

#841 fix(telegram-notifier): escaping special characters on sendMessage
  services/telegram-notifier/src/bot/send-message.ts
Labels: bugfix

#840 fix(ff-pwa): current year
  uniquely/flight-finder-pwa/src/component/job-add-form.ts
Labels: minor, bugfix

#851 refactor(icon): style
  ui/icon/src/icon.ts
Labels: enhancement

#852 feat(element/toggle): selected property
  ui/element/src/mixins/toggle.ts
Labels: new-feature

#853 feat(ui-kit): enhance button, product-card, text-field
  ui/ui-kit/src/button/button.ts
  ui/ui-kit/src/card/product-card.ts
  ui/ui-kit/src/card/surface.ts
  ui/ui-kit/src/text-field/text-field.ts
  ui/ui-kit/style/pwa.css
Labels: new-feature, bugfix

#854 feat(cloud): optimize nginx, `backup` command and `up -b` switch
  cloud/classic/lib/deploy.sh
  cloud/classic/mariadb/env/baran.env
  cloud/classic/wordpress/env/baran.env
  cloud/classic/wordpress/nginx/nginx.conf
Labels: new-feature

#855 feat(fetch): fetchContext work on background, skip online request when offline
  core/fetch/src/fetch.ts
Labels: new-feature

#860 feat(i18n): work background without delay
  core/i18n/src/core.ts
Labels: enhancement

#861 feat(router): internal redirect render template to another route
  core/router/src/core.ts
  core/router/src/type.ts
Labels: new-feature

#862 fix(router): home page for sub page routes
  core/router/src/core.ts
Labels: bugfix

#863 feat(router): keepSectionSlice for redirect
  core/router/src/core.ts
Labels: enhancement

#864 fix(validator): change ValidType to StringifyableRecord
  core/validator/src/type.ts
  core/validator/src/validator.ts
Labels: bugfix

#865 fix(router): add _routeContextUpdated to interface
  ui/element/src/mixins/router.ts
Labels: bugfix

#857 feat(pwa-helper): move top-app-bar & footer to pwa element
  ui/pwa-helper/src/context.ts
  ui/pwa-helper/src/pwa-element.ts
  ui/ui-kit/src/top-app-bar/top-app-bar.ts
Labels: new-feature

#856 feat/(com-pwa): order shipping page & submit order director
  uniquely/com-pwa/src/context.ts
  uniquely/com-pwa/src/director/submit-order-command-handler.ts
  uniquely/com-pwa/src/l18r/fa.json
  uniquely/com-pwa/src/page-order-shipping.ts
Labels: new-feature

#858 feat(com-pwa): pages layout
  uniquely/com-pwa/src/alwatr-pwa.ts
  uniquely/com-pwa/src/app-footer.ts
  uniquely/com-pwa/src/context.ts
  uniquely/com-pwa/src/page-404.ts
  uniquely/com-pwa/src/page-home.ts
  uniquely/com-pwa/src/page-order-list.ts
  uniquely/com-pwa/src/page-product-list.ts
Labels: enhancement

#859 feat(soffit-pwa): page layout
  uniquely/soffit-pwa/src/alwatr-pwa.ts
  uniquely/soffit-pwa/src/app-footer.ts
  uniquely/soffit-pwa/src/content/product-page-en.ts
  uniquely/soffit-pwa/src/content/product-page-fa.ts
  uniquely/soffit-pwa/src/context.ts
  uniquely/soffit-pwa/src/director/change-language.ts
  uniquely/soffit-pwa/src/director/content-provider.ts
  uniquely/soffit-pwa/src/director/submit-form-command-handler.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/page-404.ts
  uniquely/soffit-pwa/src/page-home.ts
  uniquely/soffit-pwa/src/page-product.ts
Labels: enhancement

#868 feat(button): add signalId for click event
  ui/ui-kit/src/button/button.ts
  ui/ui-kit/src/button/icon-button.ts
Labels: new-feature

#869 feat(fsm): new state context type & demo
  core/fsm/src/core.ts
  demo/finite-state-machine/light-machine.ts
Labels: new-feature

#870 refactor(type): StringifyableRecord to interface
  core/type/src/type-helper.ts
Labels: enhancement

#871 feat(element): UnresolvedMixin
  ui/element/src/index.ts
  ui/element/src/mixins/router.ts
  ui/element/src/mixins/unresolved.ts
  ui/pwa-helper/src/pwa-element.ts
  ui/ui-kit/style/pwa.css
Labels: new-feature

#872 feat(ui/top-app-bar): headlineKey and default values
  ui/ui-kit/src/top-app-bar/top-app-bar.ts
Labels: enhancement

#879 feat(signal): dispatch NextCycle option
  core/signal/src/core.ts
  core/signal/src/type.ts
Labels: new-feature

#880 refactor(fsm)!: add state prop and remove gotState
  core/fsm/src/core.ts
Labels: enhancement

#873 feat(element): state mixin
  ui/element/package.json
  ui/element/src/index.ts
  ui/element/src/mixins/state-machine.ts
  ui/element/tsconfig.json
Labels: new-feature

#874 feat(pwa-helper): scheduleUpdate by animation frame in pwa-element
  ui/pwa-helper/esbuild.mjs
  ui/pwa-helper/src/pwa-element.ts
Labels: enhancement, performance

#875 fix(icon): vertical-align style
  ui/icon/src/icon.ts
Labels: bugfix

#876 feat(button): add icon
  ui/ui-kit/src/button/button.ts
Labels: enhancement

#887 chore(soffit-pwa): update home page content
  core/i18n/src/core.ts
  ui/pwa-helper/src/config.ts
  uniquely/soffit-pwa/src/content/home-page-fa.ts
  uniquely/soffit-pwa/src/director/l18e-loader.ts
  uniquely/soffit-pwa/src/l18e/en.json
  uniquely/soffit-pwa/src/l18e/fa.json
Labels: enhancement
