Repository AliMD/alwatr, pull requests merged in 2023-03, with the labels that each got.

#889 feat(fsm): transition with partial context and fix issues
  core/fsm/package.json
  core/fsm/src/core.ts
  demo/finite-state-machine/light-machine.ts
Labels: new-feature

#890 fix(signal): NextCycle with own detail
  core/signal/src/core.ts
  core/signal/src/type.ts
Labels: bugfix

#891 feat(fetch): handle offline for all requests
  core/fetch/src/fetch.ts
Labels: enhancement

#892 feat(element/StateMachineMixin)!: reflect state to host attrib, limit scheduleUpdate to animation frame, remove FIRST_UPDATED transition
  ui/element/src/mixins/state-machine.ts
Labels: performance, bugfix

#893 feat(ui-kit): IconButtonContent.disabled, surface tinted attrib, click signal with detail, product-card toman icon
  core/type/src/event-signal.ts
  ui/ui-kit/src/button/button.ts
  ui/ui-kit/src/button/icon-button.ts
  ui/ui-kit/src/card/product-card.ts
  ui/ui-kit/src/card/surface.ts
Labels: enhancement, bugfix

#894 feat(math): calcDiscount
  core/math/src/math.ts
Labels: new-feature

#895 fix(router): make url from router respect empty sectionList
  core/router/src/core.ts
Labels: bugfix

#896 feat(pwa-helper): handle back to home event
  ui/pwa-helper/src/pwa-element.ts
  ui/pwa-helper/src/signal/back-click-event.ts
  ui/pwa-helper/src/signal/back-to-home-click.ts
  ui/pwa-helper/src/signal/browser-back-click.ts
Labels: new-feature

#900 fix(ui-kit): icon button styles
  ui/ui-kit/src/button/button.ts
  ui/ui-kit/src/text-field/text-field.ts
Labels: new-feature

#901 feat(i18n): make number with fixed descimal
  core/i18n/src/core.ts
Labels: new-feature

#902 feat(signal): defineCommand return ListenerSpec
  core/signal/src/core.ts
Labels: new-feature

#903 feat/pwa helper
  ui/pwa-helper/package.json
  ui/pwa-helper/src/context.ts
  ui/pwa-helper/src/pwa-element.ts
Labels: new-feature

#904 feat(element): add live directive
  ui/element/src/lit.ts
Labels: new-feature

#810 feat(com-pwa): order pages
  .vscode/settings.json
  core/type/src/customer-order-management.ts
  ui/ui-kit/src/button/button.ts
  ui/ui-kit/src/button/icon-button.ts
  ui/ui-kit/src/card/product-card.ts
  ui/ui-kit/src/chat/chat-footer.ts
  ui/ui-kit/src/chat/chat-list.ts
  ui/ui-kit/src/chat/chat-text-input.ts
  ui/ui-kit/src/radio-group/radio-group.ts
  ui/ui-kit/src/text-field/text-field.ts
  uniquely/com-api/demo.http
  uniquely/com-pwa/package.json
  uniquely/com-pwa/res/index.html
  uniquely/com-pwa/src/alwatr-pwa.ts
  uniquely/com-pwa/src/config.ts
  uniquely/com-pwa/src/content/home-page-fa.ts
  uniquely/com-pwa/src/content/l18e-fa.json
  uniquely/com-pwa/src/director/index.ts
  uniquely/com-pwa/src/director/logger.ts
  uniquely/com-pwa/src/director/order-storage-context-provider.ts
  uniquely/com-pwa/src/director/product-storage-context-provider.ts
  uniquely/com-pwa/src/director/submit-order-command-handler.ts
  uniquely/com-pwa/src/l18r/fa.json
  uniquely/com-pwa/src/manager/context-provider/home-page-content.ts
  uniquely/com-pwa/src/manager/context-provider/l18e.ts
  uniquely/com-pwa/src/manager/context-provider/order-storage.ts
  uniquely/com-pwa/src/manager/context-provider/price-storage.ts
  uniquely/com-pwa/src/manager/context-provider/product-storage.ts
  uniquely/com-pwa/src/manager/context-provider/user.ts
  uniquely/com-pwa/src/manager/context.ts
  uniquely/com-pwa/src/manager/controller/new-order.ts
  uniquely/com-pwa/src/manager/controller/order-detail.ts
  uniquely/com-pwa/src/manager/controller/order-list.ts
  uniquely/com-pwa/src/manager/controller/order-tracking.ts
  uniquely/com-pwa/src/manager/index.ts
  uniquely/com-pwa/src/manager/logger.ts
  uniquely/com-pwa/src/manager/submit-order-command-handler.ts
  uniquely/com-pwa/src/old/page-order-detail.ts.txt
  uniquely/com-pwa/src/old/page-order-shipping.ts.txt
  uniquely/com-pwa/src/old/page-order.ts.txt
  uniquely/com-pwa/src/page-order-list.ts
  uniquely/com-pwa/src/page-order-shipping.ts
  uniquely/com-pwa/src/page-product-list.ts
  uniquely/com-pwa/src/ui/alwatr-pwa.ts
  uniquely/com-pwa/src/ui/page/404.ts
  uniquely/com-pwa/src/ui/page/home.ts
  uniquely/com-pwa/src/ui/page/new-order.ts
  uniquely/com-pwa/src/ui/page/order-detail.ts
  uniquely/com-pwa/src/ui/page/order-list.ts
  uniquely/com-pwa/src/ui/page/order-tracking.ts
  uniquely/com-pwa/src/ui/stuff/app-footer.ts
  uniquely/com-pwa/src/ui/stuff/order-detail-base.ts
  uniquely/com-pwa/src/ui/stuff/order-list.ts
  uniquely/com-pwa/src/ui/stuff/order-shipping-form.ts
  uniquely/com-pwa/src/ui/stuff/order-status-box.ts
  uniquely/com-pwa/src/ui/stuff/select-product.ts
  uniquely/com-pwa/tsconfig.json
  uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
  uniquely/soffit-pwa/src/lottery-form.ts
  uniquely/soffit-pwa/src/supply-chain-form.ts
Labels: new-feature

#906 feat/com pwa qty
  core/type/src/customer-order-management.ts
  uniquely/com-pwa/src/manager/controller/new-order.ts
  uniquely/com-pwa/src/old/page-order-detail.ts.txt
  uniquely/com-pwa/src/old/page-order-shipping.ts.txt
  uniquely/com-pwa/src/old/page-order.ts.txt
  uniquely/com-pwa/src/ui/stuff/order-detail-base.ts
Labels: new-feature

#911 fix(icon): 404 cache issue
  ui/icon/src/preload.ts
Labels: new-feature

#910 fix(com-pwa): review
  cloud/labs/shadowsocks/env/example.env
  core/type/src/customer-order-management.ts
  core/type/src/type-helper.ts
  core/validator/src/type.ts
  core/validator/src/validator.ts
  uniquely/com-pwa/src/content/l18e-fa.json
  uniquely/com-pwa/src/manager/controller/new-order.ts
  uniquely/com-pwa/src/ui/page/new-order.ts
  uniquely/com-pwa/src/ui/page/order-detail.ts
  uniquely/com-pwa/src/ui/page/order-list.ts
  uniquely/com-pwa/src/ui/stuff/order-detail-base.ts
  uniquely/com-pwa/src/ui/stuff/order-shipping-form.ts
  uniquely/soffit-pwa/src/lottery-form.ts
Labels: new-feature, bugfix

#915 fix(com-pwa): color theme
  uniquely/com-pwa/res/index.html
  uniquely/com-pwa/res/manifest.webmanifest
Labels: bugfix

#916 perf: make google lighthouse happy
  core/i18n/src/core.ts
  ui/pwa-helper/package.json
  uniquely/com-pwa/src/manager/context-provider/home-page-content.ts
  uniquely/com-pwa/src/manager/context-provider/l18e.ts
  uniquely/com-pwa/src/ui/alwatr-pwa.ts
  uniquely/com-pwa/src/ui/stuff/app-footer.ts
  uniquely/soffit-pwa/src/app-footer.ts
Labels: new-feature

#917 chore(demo/es-bench): bench many func
  demo/es-bench/index.html
  demo/es-bench/memory-many-func.js
Labels: new-feature

#921 fix(workflow): publish container signing
  .github/workflows/publish-alwatr-container.yml
  .github/workflows/publish-special-container.yml
Labels: bugfix

#924 perf(pwa): optimize first load and rendering
  cloud/container/nginx/conf/templates/http.d/60-performance.conf.template
  ui/font/sahel.css
  ui/font/vazirmatn-roundot.css
  ui/font/vazirmatn.css
  ui/pwa-helper/esbuild.mjs
  ui/ui-kit/style/pwa.css
  uniquely/com-pwa/res/index.html
Labels: performance

#926 feat(ui-kit/snackbar): message/actionLabelMessage l10n key
  ui/ui-kit/src/snackbar/controller.ts
  ui/ui-kit/src/snackbar/type.ts
  uniquely/com-pwa/src/manager/context-provider/order-storage.ts
  uniquely/com-pwa/src/manager/context-provider/price-storage.ts
  uniquely/com-pwa/src/manager/context-provider/product-storage.ts
  uniquely/com-pwa/src/manager/controller/new-order.ts
  uniquely/soffit-pwa/src/director/submit-form-command-handler.ts
Labels: new-feature

#933 feat(element): ScheduleUpdateToFrameMixin
  ui/element/src/mixins/schedule-update-to-frame.ts
Labels: new-feature

#942 feat(bench): improve bench mark logs, test logger benchmark impact
  demo/es-bench/bench.ts
  demo/es-bench/for-in-vs-of.ts
  demo/es-bench/logger.ts
Labels: new-feature

#943 feat(type): new type helpers
  core/type/src/type-helper.ts
Labels: new-feature

#944 fix(pwa-helper): show user notify version
  ui/pwa-helper/src/signal/sw-user-notify.ts
Labels: new-feature

#945 feat(signal): new RequestableContext with state
  core/signal/src/core.ts
  core/signal/src/requestable-context-consumer.ts
  core/signal/src/requestable-context-provider.ts
  core/signal/src/type.ts
Labels: new-feature

#946 feat(icon,icon-button): issues
  ui/icon/src/icon.ts
  ui/ui-kit/src/button/icon-button.ts
Labels: new-feature

#950 feat(element/mixins/signal): _addSignalListener
  ui/element/src/mixins/signal.ts
Labels: new-feature

#951 fix(signal): dont receivePrevious when listener is disabled
  core/signal/src/core.ts
Labels: new-feature

#954 fix: compatible with new _addSignalListener signal mixin
  ui/element/src/mixins/direction.ts
  ui/element/src/mixins/localize.ts
  ui/element/src/mixins/router.ts
  ui/pwa-helper/src/pwa-element.ts
  ui/ui-kit/src/top-app-bar/top-app-bar.ts
  uniquely/com-pwa/src/ui/page/home.ts
  uniquely/com-pwa/src/ui/page/new-order.ts
  uniquely/com-pwa/src/ui/page/order-detail.ts
  uniquely/com-pwa/src/ui/page/order-tracking.ts
  uniquely/soffit-pwa/src/page-home.ts
  uniquely/soffit-pwa/src/page-product.ts
Labels: bugfix

#955 feat(element): export lit guard
  ui/element/src/lit.ts
Labels: new-feature

#956 fix(fsm): initial exec actions
  core/fsm/src/core.ts
Labels: new-feature

#959 feat(fetch): enhance types and add StringifyableFetchOptions
  core/fetch/src/fetch.ts
  core/fetch/src/type.ts
  core/storage-client/src/storage-client.ts
Labels: enhancement, new-feature, bugfix

#960 feat(fsm): add destroy, reset, unsubscribe api
  core/fsm/src/core.ts
  core/fsm/src/index.ts
  core/fsm/src/type.ts
Labels: new-feature

#961 refactor(type): AlwatrDocumentStorage type with AlwatrServiceResponseSuccessWithMeta
  core/type/src/service-response.ts
  core/type/src/storage.ts
Labels: enhancement

#958 feat(context): new package for server context over `FSM` and `context signal` <fucking awesome>
  core/context/CHANGELOG.md
  core/context/README.md
  core/context/package.json
  core/context/src/core.ts
  core/context/src/index.ts
  core/context/src/server-context.ts
  core/context/src/simple-context.ts
  core/context/src/type.ts
  core/context/tsconfig.json
Labels: new-feature

#963 refactor(context): review and enhance core api
  core/context/src/core.ts
  core/context/src/server-context.ts
  core/context/src/type.ts
Labels: new-feature

#964 refactor(SignalMixin): rename _addSignalListeners
  ui/element/src/mixins/direction.ts
  ui/element/src/mixins/localize.ts
  ui/element/src/mixins/router.ts
  ui/element/src/mixins/signal.ts
  ui/pwa-helper/src/pwa-element.ts
  ui/ui-kit/src/top-app-bar/top-app-bar.ts
  uniquely/soffit-pwa/src/page-home.ts
  uniquely/soffit-pwa/src/page-product.ts
Labels: enhancement

#965 fix(context): merge request option issue
  core/context/src/core.ts
Labels: bugfix

#962 feat(com/order-list): update order list with new `fsm` and new `context` ;)
  core/context/package.json
  tsconfig.json
  uniquely/com-pwa/package.json
  uniquely/com-pwa/src/content/l18e-fa.json
  uniquely/com-pwa/src/manager/buttons.ts
  uniquely/com-pwa/src/manager/context-provider/order-storage.ts
  uniquely/com-pwa/src/manager/context-provider/price-storage.ts
  uniquely/com-pwa/src/manager/context-provider/product-price-storage.ts
  uniquely/com-pwa/src/manager/context-provider/user.ts
  uniquely/com-pwa/src/manager/controller/order-list.ts
  uniquely/com-pwa/src/manager/index.ts
  uniquely/com-pwa/src/manager/submit-order-command-handler.ts
  uniquely/com-pwa/src/ui/page/home.ts
  uniquely/com-pwa/src/ui/page/order-list.ts
  uniquely/com-pwa/tsconfig.json
Labels: new-feature

#922 refactor(soffit-pwa): move l18e to content folder
  core/context/package.json
  core/context/tsconfig.json
  demo/tsconfig.json
  tsconfig.json
  uniquely/soffit-pwa/src/alwatr-pwa.ts
  uniquely/soffit-pwa/src/content/agency-page-en.ts
  uniquely/soffit-pwa/src/content/agency-page-fa.ts
  uniquely/soffit-pwa/src/content/home-page-en.ts
  uniquely/soffit-pwa/src/content/home-page-fa.ts
  uniquely/soffit-pwa/src/content/l18e-en.json
  uniquely/soffit-pwa/src/content/l18e-fa.json
  uniquely/soffit-pwa/src/director/content-provider.ts
  uniquely/soffit-pwa/src/director/index.ts
  uniquely/soffit-pwa/src/director/logger.ts
  uniquely/soffit-pwa/src/manager/change-language.ts
  uniquely/soffit-pwa/src/manager/context-provider/agency-page-content.ts
  uniquely/soffit-pwa/src/manager/context-provider/home-page-content.ts
  uniquely/soffit-pwa/src/manager/context-provider/product-page-content.ts
  uniquely/soffit-pwa/src/manager/context.ts
  uniquely/soffit-pwa/src/manager/index.ts
  uniquely/soffit-pwa/src/manager/l18e.ts
  uniquely/soffit-pwa/src/manager/logger.ts
  uniquely/soffit-pwa/src/manager/submit-form-command-handler.ts
  uniquely/soffit-pwa/src/type.ts
  uniquely/soffit-pwa/src/ui/alwatr-pwa.ts
  uniquely/soffit-pwa/src/ui/page/404.ts
  uniquely/soffit-pwa/src/ui/page/agency.ts
  uniquely/soffit-pwa/src/ui/page/home.ts
  uniquely/soffit-pwa/src/ui/page/product.ts
  uniquely/soffit-pwa/src/ui/stuff/app-footer.ts
  uniquely/soffit-pwa/src/ui/stuff/lottery-box.ts
  uniquely/soffit-pwa/src/ui/stuff/lottery-form.ts
  uniquely/soffit-pwa/src/ui/stuff/supply-chain-box.ts
  uniquely/soffit-pwa/src/ui/stuff/supply-chain-form.ts
Labels: new-feature

#996 perf(pwa): optimize index.html
  uniquely/com-pwa/res/index.html
  uniquely/soffit-pwa/res/index.html
Labels: performance

#995 fix(pwa-helper/esbuild): hash entryNames
  ui/pwa-helper/esbuild.mjs
Labels: enhancement

#992 chore(workflow): enable for all pull request
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
  .github/workflows/lint.yaml
Labels: new-feature

#1002 Feat/logger
  core/logger/src/logger.ts
  core/logger/src/type.ts
  ui/element/src/mixins/logging.ts
Labels: new-feature

#1003 chore: new es benchs
  .eslintignore
  demo/es-bench/bench.ts
  demo/es-bench/for-in-vs-of.ts
  demo/es-bench/index.html
  demo/es-bench/logger.ts
  demo/es-bench/many-bind.ts
  demo/es-bench/memory-arrow-func.ts
  demo/es-bench/object-vs-map.ts
  package.json
Labels: performance

#957 feat(com-pwa): refactor order-detail and new-order with new `FSM` and `context` api
  core/context/src/core.ts
  core/context/src/server-context.ts
  tsconfig.json
  ui/element/src/mixins/logging.ts
  ui/ui-kit/src/card/icon-box.ts
  ui/ui-kit/src/snackbar/controller.ts
  ui/ui-kit/src/text-field/text-field.ts
  ui/ui-kit/style/token/surface.css
  uniquely/com-pwa/src/config.ts
  uniquely/com-pwa/src/manager/context-provider/price-storage.ts
  uniquely/com-pwa/src/manager/context-provider/product-price-storage.ts
  uniquely/com-pwa/src/manager/context-provider/product-storage.ts
  uniquely/com-pwa/src/manager/controller/new-order.ts
  uniquely/com-pwa/src/manager/controller/order-detail.ts
  uniquely/com-pwa/src/manager/controller/order-tracking.ts
  uniquely/com-pwa/src/manager/index.ts
  uniquely/com-pwa/src/ui/alwatr-pwa.ts
  uniquely/com-pwa/src/ui/page/new-order.ts
  uniquely/com-pwa/src/ui/page/order-detail.ts
  uniquely/com-pwa/src/ui/page/order-list.ts
  uniquely/com-pwa/src/ui/page/order-tracking.ts
  uniquely/com-pwa/src/ui/stuff/order-detail-base.ts
  uniquely/com-pwa/src/ui/stuff/order-shipping-form.ts
  uniquely/com-pwa/src/ui/stuff/order-status-box.ts
Labels: enhancement
